### PR TITLE
3028 update ignite CI tests to 0.4.6

### LINKED ISSUE #3028: Update to ignite 0.4.6
**Is your feature request related to a problem? Please describe.**
As ignite already released 0.4.6 version, need to update our CI test to align with it.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #3028 .

### Description
This PR updated the ignite CI dependency to 0.4.6.
And we don't change the `minimum` dependency version in the code as no need to work with the latest ignite.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
> Fixes #3028 .
> 
> ### Description
> This PR updated the ignite CI dependency to 0.4.6 as @vfdev-5 released it last week.
> And we don't change the `minimum` dependency version in the code as no need to work with the latest ignite.
> 
> ### Status
> **Ready**
> 
> ### Types of changes
> * [x]  Non-breaking change (fix or new feature that would not break existing functionality).
> * [ ]  Breaking change (fix or new feature that would cause existing functionality to change).
> * [ ]  New tests added to cover the changes.
> * [ ]  Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
> * [ ]  Quick tests passed locally by running `./runtests.sh --quick --unittests`.
> * [ ]  In-line docstrings updated.
> * [ ]  Documentation updated, tested `make html` command in the `docs/` folder.



> Fixes #3028 .
> 
> ### Description
> This PR updated the ignite CI dependency to 0.4.6 as @vfdev-5 released it last week.
> And we don't change the `minimum` dependency version in the code as no need to work with the latest ignite.
> 
> ### Status
> **Ready**
> 
> ### Types of changes
> * [x]  Non-breaking change (fix or new feature that would not break existing functionality).
> * [ ]  Breaking change (fix or new feature that would cause existing functionality to change).
> * [ ]  New tests added to cover the changes.
> * [ ]  Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
> * [ ]  Quick tests passed locally by running `./runtests.sh --quick --unittests`.
> * [ ]  In-line docstrings updated.
> * [ ]  Documentation updated, tested `make html` command in the `docs/` folder.

Hi Nic, the PR description is unclear to me
- Are you sure 0.4.6 was released in the last week?
- The description says that we don't change the min version but in the code the version number had an updated?

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Sorry I didn't notify the CI failure, will add you guys to review when I resolved the error.
And BTW, this PR follows the same logic we did for ignite v0.4.5 update, we only update CI environment and pip install to test with latest ignite, the min_version in the code is still 0.4.4: https://github.com/Project-MONAI/MONAI/pull/2451

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> Sorry I didn't notify the CI failure, will add you guys to review when I resolved the error.
> And BTW, this PR follows the same logic we did for ignite v0.4.5 update, we only update CI environment and pip install to test with latest ignite, the min_version in the code is still 0.4.4: #2451
> 
> Thanks.

Sure thanks for the clarification!

**Review by vfdev-5 — APPROVED** [review]
Looks good to me, thanks @Nic-Ma !

**Pull request merged**
