### PR TITLE
rename `n_classes` to `num_classes`

### LINKED ISSUE #2841: Unify general classes argument - `n_classes` vs `num_classes`
**Is your feature request related to a problem? Please describe.**
it complicated easily mode switching in kind of hyperparameter searches

**Describe the solution you'd like**
unify `n_classes` and `num_classes` across model arguments

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Borda**
Fixes #2841

### Description
unify `n_classes` and `num_classes` across model arguments

### Status
**Ready/Work in progress/Hold**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by rijobro** [comment]
This is obviously a breaking change, but definitely a useful one.

Similarly, we use `dimensions` in a few places (e.g., `UNet`), but use `spatial_dims` in the majority of other cases. 

We also have a couple of different ways of specifying image size if that's necessary, but it's probably more effort than it's worth to correct that.

**Review by rijobro — APPROVED** [review]

**Comment by wyli** [comment]
this PR is probably needed,  it is also a good opportunity to test and roll out the `deprecated_arg` utility before v1.0 https://github.com/Project-MONAI/MONAI/blob/1ffa909146a947e99bef4345f16e6a52f50ba06b/monai/utils/deprecated.py#L109-L119  `n_class` user could get a specific error message @Nic-Ma

**Comment by Borda** [comment]
> Please note to execute the integration

is I am new in this repository, due to GH policy I need to have approved each CI run by maintainers

> update related tutorials

what steps do you suggest, as this is a breaking change, shall this be merged first and update tutorials or do it in parallel?

**Comment by Nic-Ma** [comment]
I already triggered the integration tests by command, CC @wyli .
Please try to update related tutorials or examples when this PR merged.

Thanks.

**Comment by wyli** [comment]
this will break the current pretrained model loading... (the following works for the dev branch)
```py
import os
from monai.apps.mmars import MODEL_DESC
from monai.apps.mmars import load_from_mmar

# download the MMAR from NGC to local "./" folder
for x in MODEL_DESC:
    pretrained_model = load_from_mmar(item=x, mmar_dir="./", map_location="cpu")
```

mainly for the breaking changes in:
- monai/networks/nets/torchvision_fc.py
- monai/networks/nets/resnet.py
could you please help make them backward compatible for now?

**Comment by Borda** [comment]
any suggestion on this typing issue: 
```
monai/networks/nets/resnet.py:322:5: error: Returning Any from function declared to return "ResNet"
```
while I have not touched any return types... could be related to using the `deprecated_arg` wrapper?

**Comment by wyli** [comment]
> any suggestion on this typing issue:
> 
> ```
> monai/networks/nets/resnet.py:322:5: error: Returning Any from function declared to return "ResNet"
> ```
> 
> while I have not touched any return types... could be related to using the `deprecated_arg` wrapper?

you're right, I think the wrapper needs some enhancements, do you have time to look into `deprecated_arg` or please just put a "type ignore" to skip the check

**Comment by ericspod** [comment]
The decorator might have an issue with it's type or an issue with constructors but it's being used correct I believe.

**Pull request merged**
