### PR TITLE
blend images

### PR DESCRIPTION
**Pull request by rijobro**
### Description
Utility function for superposing a segmentation on top of an image. Image can be single channel or RGB, label is converted to RGB and superposed.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

image

### CODE REVIEW

**Review by wyli — APPROVED** [review]
Thanks, it looks good to me.

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

Does this PR fix issue https://github.com/Project-MONAI/MONAI/issues/3240?

Thanks.

**Comment by rijobro** [comment]
no you can use the new `blend_image` functionality, but it is still rendered as black and white in tensorboard unfortunately.

**Comment by Nic-Ma** [comment]
OK, let me try to update the plot function, we developed it very long time ago.

Thanks.

**Pull request merged**
