### PR TITLE
Update WSIReader with cuCIM

### PR DESCRIPTION
**Pull request by behxyz**
### Description
The official CuImage package will be released soon on PyPI under the name of `cuCIM`. This PR update WSIReader to this new naming from `cuClaraImage`.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @behxyz ,

As `cuCIM` is available for public installation, could you please help enable the installation and CI tests?

Thanks.

**Comment by behxyz** [comment]
Hi @Nic-Ma, it is not public yet but once it's public, I will take care of that. That'd be the topic of another PR.

**Comment by Nic-Ma** [comment]
Hi @behxyz ,

May I know when it will public release?

Thanks.

**Comment by wyli** [comment]
perhaps the PyPI package's metadata is incomplete? I tried pip install and check the file `lib/python3.7/site-packages/cucim-0.0.0.dist-info/METADATA` the version is 0.0.0 :
```
Metadata-Version: 2.1
Name: cucim
Version: 0.0.0
Summary: A GPU Image I/O and Processing Toolkit
Home-page: https://github.com/gigony/cucim
Author: Gigon Bae
Author-email: gigony@gmail.com
License: Apache Software License 2.0
Keywords: cucim
Platform: UNKNOWN

```

**Comment by behxyz** [comment]
@Nic-Ma, @wyli 
cuCIM is released! Yay! https://pypi.org/project/cucim/0.18.0/
It only supports Linux and according to the developer there is no plan to support Mac or Windows.
I can see that for Windows platform we are only importing the first 12 dependencies so it passes the windows testing as well! However, it is not the case for Mac platform.

**Comment by behxyz** [comment]
> @Nic-Ma, @wyli
> cuCIM is released! Yay! https://pypi.org/project/cucim/0.18.0/
> It only supports Linux and according to the developer there is no plan to support Mac or Windows.
> I can see that for Windows platform we are only importing the first 12 dependencies so it passes the windows testing as well! However, it is not the case for Mac platform.

I have excluded `cucim` on MacOS platform for CI/CD.

**Review by wyli — APPROVED** [review]
thanks, this looks good to me, could you please confirm @Nic-Ma

**Comment by wyli** [comment]
sorry I didn't know there's an auto-merge @Nic-Ma

**Comment by Nic-Ma** [comment]
Hi @behxyz and @wyli ,

PR looks good to me.
Thanks for the great work!!

**Pull request merged**
