### PR TITLE
4966 fix deepedit get clicks

### PR DESCRIPTION
**Pull request by wojiazaiyugang**
Fixes https://github.com/Project-MONAI/MONAI/issues/4966

### Description
A few sentences describing the changes proposed in this pull request.

### Status
**Ready/Work in progress/Hold**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by wyli — APPROVED** [review]
it looks good to me

fyi @SachidanandAlle @diazandr3s I'm merging this PR.

**Comment by SachidanandAlle** [comment]
This breaks the MONAILabel client (3D Slicer, OHIF).. they don't not send guidance..  as the way click points is sent is changed..
the tutorial needed fix rather than the transform.. if possible please revert back this change...

**Comment by tangy5** [comment]
Followups: User/Client side: The SmartEdit / Deepgrow Update click triggers the AddGuidanceFromPointsDeepEditd transformation call, and it return an error: KeyError: 'guidance'. Seems the no "guidence" key sent from the client as Sachi mentioned.

**Pull request merged**
