### PR TITLE
Change nn.Upsample to monai Upsample to make determ training in DiNTs possible

### LINKED ISSUE #6110: Auto3dSeg GPU Customization Test Non-Determinsistically Failing
**Describe the bug**
When running the test `python -m tests.test_integration_gpu_customization` it sometimes fails.

**To Reproduce**
1. Go to head of MONAI repo
2. Create and activate conda env using `conda env create --file environment-dev.yml && conda activate monai`
3. Run commands `python -m tests.test_integration_gpu_customization`

**Expected behavior**
Test passes every time.

**Actual behaviour**

Test occasionally fails (when DINTS is selected as best algorithm for ensembling, I believe) with following outputs:

```shell

======================================================================
ERROR: test_ensemble_gpu_customization (__main__.TestEnsembleGpuCustomization)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/azureuser/localfiles/Repos/MONAI/tests/test_integration_gpu_customization.py", line 149, in test_ensemble_gpu_customization
    preds = ensemble(pred_param)
  File "/home/azureuser/localfiles/Repos/MONAI/monai/apps/auto3dseg/ensemble_builder.py", line 164, in __call__
    pred = infer_instance.predict(predict_files=[file], predict_params=param)
  File "/home/azureuser/localfiles/Repos/MONAI/monai/apps/auto3dseg/bundle_gen.py", line 271, in predict
    inferer = self.get_inferer(**params)
  File "/home/azureuser/localfiles/Repos/MONAI/monai/apps/auto3dseg/bundle_gen.py", line 255, in get_inferer
    return infer_class.InferClass(configs_path, *args, **kwargs)
  File "/tmp/tmprkmn_prz/workdir/dints_0/scripts/infer.py", line 84, in __init__
  File "/anaconda/envs/monai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DiNTS:
        Missing key(s) in state_dict:
        ...
        Unexpected key(s) in state_dict:
        ...
```

**Screenshots**

image

image

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'

================================
Printing MONAI config...
================================
MONAI version: 0+untagged.2538.g579fe65
Numpy version: 1.23.5
Pytorch version: 1.13.1
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 579fe65c96dce810ab06fcdbf37c142de8ef6815
MONAI __file__: /home/azureuser/localfiles/Repos/MONAI/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.11
ITK version: 5.3.0
Nibabel version: 5.0.1
scikit-image version: 0.20.0
Pillow version: 9.4.0
Tensorboard version: 2.12.0
gdown version: 4.6.4
TorchVision version: 0.14.1
tqdm version: 4.65.0
lmdb version: 1.4.0
psutil version: 5.9.4
pandas version: 1.5.3
einops version: 0.6.0
transformers version: 4.21.3
mlflow version: 2.2.1
pynrrd version: 1.0.0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 20.04.5 LTS
Platform: Linux-5.15.0-1031-azure-x86_64-with-glibc2.31
Processor: x86_64
Machine: x86_64
Python version: 3.10.9
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: [popenfile(path='/home/azureuser/.vscode-server/data/logs/20230307T104704/remoteagent.log', fd=19, position=6400, mode='a', flags=33793), popenfile(path='/home/azureuser/.vscode-server/data/logs/20230307T104704/ptyhost.log', fd=20, position=0, mode='a', flags=33793)]
Num physical CPUs: 24
Num logical CPUs: 24
Num usable CPUs: 24
CPU usage (%): [3.7, 3.7, 3.7, 3.7, 3.7, 4.0, 3.7, 3.4, 3.4, 3.4, 3.4, 3.7, 3.4, 3.7, 3.4, 3.7, 3.4, 3.7, 5.7, 3.4, 3.4, 3.7, 4.0, 99.7]
CPU freq. (MHz): 2594
Load avg. in last 1, 5, 15 mins (%): [3.9, 9.4, 8.6]
Disk usage (%): 66.3
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 440.9
Available memory (GB): 433.0
Used memory (GB): 5.0

================================
Printing GPU config...
================================
Num GPUs: 4
Has CUDA: True
CUDA version: 11.6
cuDNN enabled: True
cuDNN version: 8302
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
GPU 0 Name: Tesla P100-PCIE-16GB
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 56
GPU 0 Total memory (GB): 15.9
GPU 0 CUDA capability (maj.min): 6.0
GPU 1 Name: Tesla P100-PCIE-16GB
GPU 1 Is integrated: False
GPU 1 Is multi GPU board: False
GPU 1 Multi processor count: 56
GPU 1 Total memory (GB): 15.9
GPU 1 CUDA capability (maj.min): 6.0
GPU 2 Name: Tesla P100-PCIE-16GB
GPU 2 Is integrated: False
GPU 2 Is multi GPU board: False
GPU 2 Multi processor count: 56
GPU 2 Total memory (GB): 15.9
GPU 2 CUDA capability (maj.min): 6.0
GPU 3 Name: Tesla P100-PCIE-16GB
GPU 3 Is integrated: False
GPU 3 Is multi GPU board: False
GPU 3 Multi processor count: 56
GPU 3 Total memory (GB): 15.9
GPU 3 CUDA capability (maj.min): 6.0
```

**Additional context**
This test does not always fail. ~50% of the time, it passes, seeming to load the segresnet checkpoint instead for ensembling:

```shell
=> loaded checkpoint /tmp/tmpqmdgiqwz/workdir/segresnet_0/model/model.pt (epoch 1) (best_metric 0.4888312518596649)
Total parameters count 87164200 distributed False
monai.transforms.io.dictionary LoadImaged.__init__:image_only: Current default value of argument `image_only=False` has been deprecated since version 1.1. It will be changed to `image_only=True` in version 1.3.
Inference complete, time 0.26s shape torch.Size([2, 24, 24, 24]) {'image': '/tmp/tmpqmdgiqwz/dataroot/val_001.fake.nii.gz'}
segresnet_0
.
----------------------------------------------------------------------
Ran 1 test in 202.620s

OK
```

### PR DESCRIPTION
**Pull request by mingxin-zheng**
Part of #6110 .

### Description

A few sentences describing the changes proposed in this pull request.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by wyli — APPROVED** [review]
Thanks for the investigations

**Comment by mingxin-zheng** [comment]
Hi @wyli , I paused the auto-merge because I found a bug. It'll be good if @dongyang0122 can review it. Thanks!

**Review by dongyang0122 — COMMENTED** [review]
The changes look good to me. Thanks for the explanation! Is this upsamling dependent on PyTorch version?

**Pull request closed without merging**
