### PR TITLE
Make Auto3DSeg algo able to find algorithm templates

### LINKED ISSUE #6435: Unable to load the Auto3DSeg algo after the working directory is moved
**Describe the bug**

It is possible that the working directory is moved between systems for the Auto3DSeg algo training, because the training job is distributed between systems.
Now it is unable to load the trained algo if they are moved.

### PR DESCRIPTION
**Pull request by mingxin-zheng**
Fixes #6435 .

### Description

In this PR, the changes are
- Make `template_path` a property that's available for all Algo classes to find the path to instantiate the class. The default value of `template_path` is None.
- Enhance `algo_from_pickle` function by making it search in a few candidate directories to instantiate the `Algo` class if needed.
- Remove checking if an algo instance is `BundleAlgo` in HPO logics because `template_path` is universal for all `Algo` now.
- Update out-of-date docstring for AutoRunner

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by wyli — APPROVED** [review]

**Comment by mingxin-zheng** [comment]
I found some deprecated documentation in AutoRunner about "CUDA_VISIBLE_DEVICES" usage. Removing them in this PR as well.

**Comment by mingxin-zheng** [comment]
Since `template_path` is in `Algo` in this PR, there is no need to check if the instance is `BundleAlgo` and changes the logics in HPO.

**Pull request merged**
