### PR TITLE
3482 Add ReferenceResolver to manage config items

### PR DESCRIPTION
**Pull request by Nic-Ma**
Task step 3-1 of #3482 .

### Description
This PR implemented the `ReferenceResolver` to manage all the `ConfigItem` and resolve the references.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by wyli — APPROVED** [review]
thanks, I made some more non-breaking changes. `find_refs_in_config` and `update_config_with_refs` share many similarities, I suspect we can somehow merge these two with an additional 'update: bool` flag. But I think it's also good in its current shape...

**Comment by Nic-Ma** [comment]
> thanks, I made some more non-breaking changes. `find_refs_in_config` and `update_config_with_refs` share many similarities, I suspect we can somehow merge these two with an additional 'update: bool` flag. But I think it's also good in its current shape...

Thanks for your review and update.
I would suggest to keep current shape of the 2 functions, we may revisit and update the logic during development, let's keep it simple and easy to ready.

Thanks.

**Pull request merged**
