### PR TITLE
update multimodal doc and model names (Transchex)

### PR DESCRIPTION
**Pull request by ahatamiz**
Signed-off-by: ahatamizadeh <ahatamizadeh@nvidia.com>

### Description
This PR updates the doc for multi-modal transformers by adding proper paper reference and updating the model name.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by ahatamiz** [comment]
Hi @wyli I have added the paper reference and improved the docs for this PR.

 Thanks

**Review by wyli — APPROVED** [review]
thanks, it looks good to me

**Pull request merged**
