### PR TITLE
871 Add AMP tutorial and compare performance

### LINKED ISSUE #871: Add PyTorch AMP training / evaluation examples
**Is your feature request related to a problem? Please describe.**
We already have AMP examples based on MONAI workflows, need to add AMP examples for pure PyTorch programs.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #871 .

### Description
This PR implemented a tutorial notebook to show how to use PyTorch AMP feature in training and evaluation.
And also compared the performance with charts.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by ericspod** [comment]
There's a few cells that don't have output ("Enable deterministic and train with AMP" and "Enable deterministic and train without AMP") and a few with outputs that don't layout correctly in Github ("Expected memory usage during training with AMP" and the one without AMP). That isn't a big issue though especially if it looks fine through other Jupyter viewers. Otherwise it looks fine. Is there any way of tracking memory usage as well as time?

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Thanks for your review.
1. About the layout issue, in jupyter notebook, it looks like:
image
I already updated to use screenshot images.
2. I don't think there is some API can track GPU memory usage during training except `nvidia-smi` in another terminal.
Maybe we can investigate some CUDA python API in future?
3. I deleted the training log because the log of 600 epochs is too long in the notebook, just same as other spleen notebooks.

Thanks.

**Comment by ericspod** [comment]
I had wanted the output from the training cells to see what the total train time was with and without AMP but it's fine. As for memory there's a lot more functionality in torch.cuda for tracking and profile memory so maybe we could look later into some way of profiling things.

**Comment by wyli** [comment]
> I had wanted the output from the training cells to see what the total train time was with and without AMP but it's fine. As for memory there's a lot more functionality in torch.cuda for tracking and profile memory so maybe we could look later into some way of profiling things.

agreed, perhaps could add this command for some basic memory usage information https://pytorch.org/docs/stable/cuda.html#torch.cuda.memory_summary

**Comment by Nic-Ma** [comment]
Hi @ericspod and @wyli ,

I added your suggestions to task: https://github.com/Project-MONAI/MONAI/issues/881.
Will do it tomorrow.

Thanks.

**Pull request merged**
