### PR TITLE
5505 - option for preserving input dtypes Load/Save

### LINKED ISSUE #5505: LoadImageD NibabelReader preserve original data type
It's currently seems impossible to load ".nib/.nib.gz" image in the original data type (e.g. label in uint8), it always converts to float.
In LoadImageD transform we have an option **dtype** , which states that if dtype==None, it should keep the original format, [but internally ](https://github.com/Project-MONAI/MONAI/blob/abdb591b926f22be262e5397a2e8638629d60f90/monai/transforms/io/dictionary.py#L99)

but internally NibabelReader always reads in dtype (usually float)  because of get_fdata(), and does not preserve original format
https://github.com/Project-MONAI/MONAI/blob/ef68f16dde33172b2eeae5397ac75aa717808875/monai/data/image_reader.py#L1008-L1018

I think we should replace
`_array = np.array(img.get_fdata(dtype=self.dtype))` 
with   np.asarray(img.dataobj)
`_array = np.asarray(img.dataobj)`  if dtype is None
(see here [https://nipy.org/nibabel/images_and_memory.html how to get in original data type](https://nipy.org/nibabel/images_and_memory.html#use-the-array-proxy-instead-of-get-fdata)) This has an additional benefit that .uncache() won't be necessary

(and ensure that LoadImageD doesn't copy/convert data unnecessarily of dtype==None (original type))

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Fixes #5505

### Description
- provides an option to preserve the input dtype when:
  - `LoadImge(dtype=None, ...)`
  - `SaveImage(output_dtype=None, ...)`

- deprecate `dtype` in `NibabelReader`, so the readers always preserve the dtype

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]

**Comment by myron** [comment]
@wyli  looks great, thank you!

**Pull request merged**
