### PR TITLE
5 (MVP)checkpoint event handler

### PR DESCRIPTION
**Pull request by Nic-Ma**
Hi All,

This PR is to implement a basic checkpoint event handler for our MVP example only.
Totally based on Ignite APIs.
Could you please help review it when you are available?
Thanks in advance.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
HI @ericspod ,

BTW, I totally understand that Jupyter Notebook can provide better user experience, especially for training steps, but I found that it's **not very clear to review diffs** if we modify notebook content.
So can we also add some python examples in later sprints?
Just like Ignite examples, it will be more clear to review and run locally.
And keep several beautiful Jupyter Notebooks for tutorials?
Thanks.

**Comment by ericspod** [comment]
This changed file was removed in the main branch so we perhaps we defer doing anything with that example for now.

**Comment by Nic-Ma** [comment]
> This changed file was removed in the main branch so we perhaps we defer doing anything with that example for now.

Hi @ericspod ,

I think this PR is 1 commit ahead of the master branch on the example code.
Do you mean you are doing some other PR that removed this example?
Thanks.

**Comment by ericspod** [comment]
Ah yes it was different version of this file that was moved.

**Comment by Nic-Ma** [comment]
> Ah yes it was different version of this file that was moved.

Hi @ericspod ,

Thanks for your review and approval!
I think we are ready for the demo of this MVP, right?
Maybe you can help show it at next sprint meeting.
Thanks.

**Pull request merged**
