### PR TITLE
[WIP] 2510 Add document to introduce `decollate batch`

### LINKED ISSUE #2510: Add document about migrating to `decollate` feature (7/July)
**Is your feature request related to a problem? Please describe.**
Need to add a documentation page about why we added `decollate` feature in v0.6 and how to use it, how to migrate.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #2510 .

### Description
This PR added a document to introduce the new `decollate batch` feature of MONAI v0.6.

### Status
**Work in progress**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Mark: I am drawing chart to describe the overall design, will make the page ready ASAP.

Thanks.

**Comment by wyli** [comment]
thanks, this should be a runnable colab notebook tutorial with code examples and results, we put it in the tutorials, and have links to it from "what's new", and from monai.io getting started page. we may need a "FAQ" section in the near future...

**Comment by Nic-Ma** [comment]
Hi @wyli ,

OK, let me change to develop a simple tutorial for decollate feature.

Thanks.

**Comment by wyli** [comment]
thanks, this is addressed by https://github.com/Project-MONAI/tutorials/pull/251

**Pull request closed without merging**
