### PR TITLE
3365 update highlight 0.8

### LINKED ISSUE #3365: Update highlights for v0.8 release
**Is your feature request related to a problem? Please describe.**
Need to update the highlight features page for v0.8 release.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #3365 .

### Description
This PR updated the highlights page for v0.8 release.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I have added all the items I think highlights, do you have any more items to add?
Please feel free to review or edit the PR content.

Thanks in advance.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I have updated the charts to align with `what's news in v0.8`, visualization charts with `PLS` orientation, and refined the description.
Please feel free to review and edit the content directly.

Thanks in advance.

**Review by rijobro — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
