### PR TITLE
Fix download failing on FIPS machines

### PR DESCRIPTION
**Pull request by MattTheCuber**
### Description
This PR fixes downloads failing on FIPS enabled machines due to insecure MD5 hashing. The two solutions are to disable MD5 hashing (SHA1 is allowed and faster), or use the `usedforsecurity=False` flag. This PR uses the second method. However, the `usedforsecurity` flag only works for Python 3.9 and later (which was accounted for). Let me know if you have a better implementation to solve this issue.

The error thrown on FIPS enabled machine is:
```ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS```

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by ericspod** [comment]
I think this change is fine. @Nic-Ma @KumoLiu just to check with you that there isn't any security implications to consider here.

**Comment by KumoLiu** [comment]
> I think this change is fine. @Nic-Ma @KumoLiu just to check with you that there isn't any security implications to consider here.

I checked the usage for this `check_hash`, looks only used for downloading, will merge this one first.

**Review by KumoLiu — APPROVED** [review]

**Pull request merged**
