### PR TITLE
2478 Update highlight features page for v0.6

### LINKED ISSUE #2478: Update feature highlight doc for v0.6.0 (7/July)
**Is your feature request related to a problem? Please describe.**
this is a sub-task of https://github.com/Project-MONAI/MONAI/issues/2477

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #2478 .

### Description
This PR updated the highlight features page for v0.6 release.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

1. Could you please help add the `MMAR tutorial`(if you are developing) link in the highlight features?
2. Do we have any new important features in the C++ and CUDA components?
3. And do you have any other highlight features that not involved in this PR?

Thanks in advance.

**Comment by Nic-Ma** [comment]
Hi @wyli , BTW, is the registration module totally completed now? If yes, let's also highlight it with the tutorial.

Thanks.

**Comment by Nic-Ma** [comment]
@wyli please feel free to edit or add / delete the content when you reviewing the PR.

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> 1. Could you please help add the `MMAR tutorial`(if you are developing) link in the highlight features?
> 2. Do we have any new important features in the C++ and CUDA components?
> 3. And do you have any other highlight features that not involved in this PR?
> 
> Thanks in advance.

sure, I'm updating the mmar tutorial according to https://github.com/Project-MONAI/tutorials/pull/246
for (2), @charliebudd could you please share the figures of GMM? we can include the full demo later in the tutorial repo

**Comment by Nic-Ma** [comment]
Hi @wyli ,

BTW, please copy the new content to `whatsnew.md` page when you finalized the highlights content.

Thanks in advance.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I want to add a section to highlight the `deollate` feature, is it OK for me to push a commit now?

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> I want to add a section to highlight the `deollate` feature, is it OK for me to push a commit now?
> 
> Thanks.

sure (I feel this doc is too dense, nobody would read through it...)

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Cool, thanks.
Actually, many Clara users read this document carefully as the start-point.
I was planning to split it into several separate pages after this v0.6 release.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I don't have more items to add, please feel free to review the PR and complete it.

Thanks very much for your enhancement and great figures.

**Review by wyli — APPROVED** [review]

**Pull request merged**
