### PR TITLE
3194 update vitautoenc for 2d

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

follow up of https://github.com/Project-MONAI/MONAI/pull/3194

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by finalelement — COMMENTED** [review]
LGTM!

**Review by Nic-Ma — APPROVED** [review]
Thanks for the enhancement.
Looks good to me, @finalelement could you please help also review and double confirm it?

Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

There is some error in the CI tests:
```
ValueError: Sequence must have length 3, got 2.
```

Thanks.

**Pull request merged**
