### PR TITLE
Update offset assign

### PR DESCRIPTION
**Pull request by wyli**
according to https://github.com/balbasty/nitorch/pull/65

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @charliebudd ,

Could you please help take a look at this PR for the C++ extension?

Thanks in advance.

**Review by charliebudd — APPROVED** [review]
This is more of an algorithmic change, and I'm unfamiliar with this algorithm. But nothing looks amiss to me.

**Pull request merged**
