### PR TITLE
863 Fix documentation warning

### LINKED ISSUE #863: sphinx documentation warnings
**Describe the bug**
building the documentation locally generates a couple of warnings:
```bash
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 16 source files that are out of date
updating environment: [new config] 16 added, 0 changed, 0 removed
/usr/local/anaconda3/envs/py36/lib/python3.6/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
/usr/local/anaconda3/envs/py36/lib/python3.6/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
reading sources... [100%] visualize                                                                                            
WARNING: autodoc: failed to import class 'handlers.CheckpointLoader' from module 'monai'; the following exception was raised:
cannot import name 'RemovableEventHandle'
WARNING: autodoc: failed to import class 'handlers.CheckpointSaver' from module 'monai'; the following exception was raised:
cannot import name 'RemovableEventHandle'
WARNING: autodoc: failed to import class 'handlers.ClassificationSaver' from module 'monai'; the following exception was raised:
cannot import name 'RemovableEventHandle'
WARNING: autodoc: failed to import class 'handlers.MeanDice' from module 'monai'; the following exception was raised:
cannot import name 'RemovableEventHandle'
WARNING: autodoc: failed to import class 'handlers.ROCAUC' from module 'monai'; the following exception was raised:
cannot import name 'RemovableEventHandle'
WARNING: autodoc: failed to import class 'handlers.MetricLogger' from module 'monai'; the following exception was raised:
cannot import name 'RemovableEventHandle'
WARNING: autodoc: failed to import class 'handlers.SegmentationSaver' from module 'monai'; the following exception was raised:
cannot import name 'RemovableEventHandle'
WARNING: autodoc: failed to import class 'handlers.StatsHandler' from module 'monai'; the following exception was raised:
cannot import name 'RemovableEventHandle'
WARNING: autodoc: failed to import class 'handlers.TensorBoardStatsHandler' from module 'monai'; the following exception was raised:
cannot import name 'RemovableEventHandle'
WARNING: autodoc: failed to import class 'handlers.LrScheduleHandler' from module 'monai'; the following exception was raised:
cannot import name 'RemovableEventHandle'
WARNING: autodoc: failed to import class 'handlers.ValidationHandler' from module 'monai'; the following exception was raised:
cannot import name 'RemovableEventHandle'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] visualize                              
```

**To Reproduce**
1. Go to `MONAI/docs`
2. ` pip install -U -r requirements.txt` to install doc deps
3. Run `make clean; make html`

**Expected behavior**
no warnings in the building log

**Environment (please complete the following information):**
```
MONAI version: 0.2.0+77.g783f6a1
Python version: 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 18:53:43)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy version: 1.19.1
Pytorch version: 1.6.0

Optional dependencies:
Pytorch Ignite version: 0.3.0
Nibabel version: 3.1.1
scikit-image version: 0.17.2
Pillow version: 7.2.0
Tensorboard version: 2.3.0
```

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #863 .

### Description
Fixed warining caused by `RemovableEventHandler`.

### Status
**Ready**

### Types of changes

- [ ] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by ericspod** [comment]
What was the warning issue with this?

**Comment by Nic-Ma** [comment]
> What was the warning issue with this?

Hi @ericspod ,

The root cause is that the import path of `RemovableEventHandle` is wrong in the code and actually we most of the handlers don't return it, so I removed it directly.

Thanks.

**Comment by ericspod** [comment]
If it's an issue with Ignite you could mention it, they're moving towards type checking things a lot too.

**Comment by Nic-Ma** [comment]
> If it's an issue with Ignite you could mention it, they're moving towards type checking things a lot too.

Not an ignite issue, the import path is wrong in these handlers.
Thanks.

**Pull request merged**
