### PR TITLE
4386 Update highlights for 0.9 release

### LINKED ISSUE #4386: Update highlights page for 0.9 release
**Is your feature request related to a problem? Please describe.**
As we are closing to the MONAI 0.9 release, would be nice to update the highlights page for new features.
And also need to prepare the `What's new in 0.9` page.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #4386 .

### Description
This PR updated the highlights page for MONAI 0.9 release.

### Status
**Work in progress**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I have updated the highlights page for all the important features of MONAI v0.9 except for the `MetaTensor` part.
Could you please help review it and add `MetaTensor` part if necessary?
Please feel free to edit it.

Thanks in advance.

**Comment by Nic-Ma** [comment]
Thanks for @yuchen-xu 's feedback, fixed the unsupported markdown links in the webpage.

**Review by wyli — APPROVED** [review]

**Pull request merged**
