### PR TITLE
Add support for metatensor in AddGuidanceFromPointsDeepEditd and ResizeGuidanceMultipleLabelDeepEditd

### LINKED ISSUE #7114: Add support for metatensor in `AddGuidanceFromPointsDeepEditd` and `ResizeGuidanceMultipleLabelDeepEditd`
Now it was hard-coded for `meta_dict`.
https://github.com/Project-MONAI/MONAI/blob/8d730cdddb061e248748cb2d9c81113ae0086adb/monai/apps/deepedit/transforms.py#L701

### PR DESCRIPTION
**Pull request by KumoLiu**
Fixes #7114 

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by wyli — APPROVED** [review]

**Comment by mingxin-zheng** [comment]
Thanks @KumoLiu for the fix!

**Comment by mingxin-zheng** [comment]
Hi @wyli Shall we use a new tag (rc5) or reuse the previous tag (rc4) after this merge?

**Comment by wyli** [comment]
> Hi @wyli Shall we use a new tag (rc5) or reuse the previous tag (rc4) after this merge?

Hi Mingxin, I'm going to tag rc5 after this PR

**Pull request merged**
