### PR TITLE
Remove Status from PR Template

### PR DESCRIPTION
**Pull request by drbeh**
### Description
This PR remove "Status" from PR template. The Status was very useful before GitHub introduced *Draft* PR. I believe right now it is redundant to have this and sometimes conflicting (e.g., Status Ready <> Draft PR), so I believe it is time to remove the "Status" from PR template.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Comment by drbeh** [comment]
@Nic-Ma @wyli @ericspod @rijobro, what do you think?

**Review by wyli — APPROVED** [review]
agreed, I think we can simplify the form

**Comment by ericspod** [comment]
Fair enough, we should also not put "WIP" or something similar in titles either.

**Pull request merged**
