### PR TITLE
4148 Enhance engine iteration logic and the typehints

### LINKED ISSUE #4148: Update engines according to discussion
**Is your feature request related to a problem? Please describe.**
According to the discussion in #4132 , would be nice to update:
1. Still defining `_iteration()` as a regular method, but unify all the `self.XXX` and `engine.XXX` to `engine.XXX`. Because (1) as you said users can easily copy-paste our code, (2) maybe someone will override the engine `run` logic someday and pass **other engine** as parameter instead of `self`: https://github.com/pytorch/ignite/blob/master/ignite/engine/engine.py#L859.
2. Check all the `engine: Engine` functions, if having MONAI specific logic, change the typehint to `Workflow`.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #4148 .

### Description
This PR enhanced the engine iteration logic and the typehints.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

I updated the engines in this PR, and I checked all the handlers don't have dependency on `Workflow`, so keep them with ignite `Engine`.
Seems `pre-commit-ci` also automatically changed several typehints, I saw @rijobro also used similar thing in MetaTensor:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/meta_tensor.py
Maybe this is the right way to go? We may need to automatically update all the typehints in the codebase with the `pre-commit-ci` tool later (I don't know how to trigger it..).
Could you please help the PR?

Thanks in advance.

**Comment by rijobro** [comment]
So you imported `from __future__ import annotations` so that you could use `SupervisedEvaluator` as type hint for `engine ` in `_iteration`?

And then from there, the `pre-commit-ci` made all the other changes? If that's the case, this is all OK with me.

**Comment by Nic-Ma** [comment]
> So you imported `from __future__ import annotations` so that you could use `SupervisedEvaluator` as type hint for `engine ` in `_iteration`?
> 
> And then from there, the `pre-commit-ci` made the other type hint changes (`a | None`)? If that's the case, this is all OK with me.

Hi @rijobro ,

Yes, I imported the `annotations` to make current class is available for typehints.

Thanks.

**Review by rijobro — APPROVED** [review]

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

The initial discussion about this PR is here: https://github.com/Project-MONAI/MONAI/pull/4132#issuecomment-1102756951.

Thanks.

**Comment by Nic-Ma** [comment]
I executed the integration test `test_integration_workflows.py` locally and it passed OK.

Thanks.

**Comment by ericspod** [comment]
I'm good with the changes, this way of defining optional values should be compatible with the versions of Python we're supporting now.

**Review by ericspod — APPROVED** [review]

**Pull request merged**
