### PR TITLE
1808 Drop post transforms from AUC metric

### LINKED ISSUE #1808: Need to drop activation and one-hot args in AUC
**Is your feature request related to a problem? Please describe.**
We already dropped activation and one-hot args in metrics except AUC, use post transforms instead.

**Describe the solution you'd like**
Drop the args in AUC metric.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #1808 .

### Description
This PR dropped the args of post transforms from AUC metric, it should be done by post transforms, same as other metrics.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Could you please help update the tutorials repo when this PR is merged? Just same as what you have done for other metrics before.

Thanks in advance.

**Comment by rijobro** [comment]
Obviously it makes sense to sync AUC with the rest of the metrics, but should we not be worried about the break in backwards compatibility?

**Comment by Nic-Ma** [comment]
> Obviously it makes sense to sync AUC with the rest of the metrics, but should we not be worried about the break in backwards compatibility?

Hi @rijobro ,

We changed other metrics to use post transforms in v0.4 release, seems no problems so far. So I think it's better to make it clear as soon as possible. @wyli @ericspod what do you think?

Thanks.

**Review by wyli — APPROVED** [review]
thanks!

**Pull request merged**
