### PR TITLE
RandCropByPosNegLabel(d) to return 1 element if num_samples==1

### PR DESCRIPTION
**Pull request by rijobro**
### Description
If `RandCropByPosNegLabel` or `RandCropByPosNegLabeld` is called with `num_samples==1`, then return just an element, rather than a list containing 1 element. This is useful if followed by something that doesn't expect a list of results or debugging (e.g., `DataStatsd`).

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by rijobro** [comment]
addresses https://github.com/Project-MONAI/MONAI/issues/876#issuecomment-784006128.

**Comment by Nic-Ma** [comment]
@rijobro thanks for raising this up with a PR.
But according to our experience with `DynUNet`, different return data types maybe not a good idea, users usually expect consistent output `shape` and `type` and develop the following logic.
@wyli @ericspod , what do you guys think?

Thanks.

**Comment by wyli** [comment]
I don't have a preference here but I think `DataStats` could be improved to at least print some information for any datatype...

**Comment by rijobro** [comment]
@Nic-Ma Good point. Although all these changes would be handled by the DataLoader, so I think that changing the output type wouldn't affect us in the same way as the output of `DynUNet`, because the batch created at the end will be just the same.

@wyli although we could change the `DataStatsd`, that was just one example. Presumably any transform that expects a dictionary but receives a list of dictionaries will have the same problem.

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

Actually, if a transform generates a list of dict instead of dict, the following transforms will execute on every item of the list.
Check this: https://github.com/Project-MONAI/MONAI/blob/master/monai/transforms/utils.py#L385
So I think it will not affect the `DataStat` transform.
Please feel free to correct me if I misunderstand your question.

Thanks.

**Comment by rijobro** [comment]
Ah, ok thanks @Nic-Ma ! I think I'll close this for now then.

**Pull request closed without merging**
