### PR TITLE
Uninstall opencv included in base image

### PR DESCRIPTION
**Pull request by KumoLiu**
Fixes [tutorial #1689](https://github.com/Project-MONAI/tutorials/issues/1689)

### Description

Uninstall opencv included in base image.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]

**Review by mingxin-zheng — APPROVED** [review]
Looks good to me. The `opencv` in the `pytorch` container doesn't include packages in `opencv-headless`, and potentially causes issues for video processing.

**Comment by binliunls** [comment]
Could you please run [this notebook](https://github.com/Project-MONAI/tutorials/blob/main/computer_assisted_intervention/video_seg.ipynb) after uninstall the opencv? The VideoFileDataset is using the opencv lib. I am afraid of removing the lib impacts it.

Thanks,
Bin

**Comment by KumoLiu** [comment]
> Could you please run [this notebook](https://github.com/Project-MONAI/tutorials/blob/main/computer_assisted_intervention/video_seg.ipynb) after uninstall the opencv? The VideoFileDataset is using the opencv lib. I am afraid of removing the lib impacts it.

Add `opencv-python-headless` in the requirement-dev and verify the notebook.

**Pull request merged**
