### PR TITLE
2032 add alias for DenseNets

### LINKED ISSUE #2032: issue with LoadNifti & denseNet121 in V.0.5.0
Previously the following codes was working 
but it showed error messages and could not continue: 

!pip install -q "monai[gdown, nibabel, tqdm]"

from monai.transforms import \
    Compose,  AddChanneld, ScaleIntensityd, ToTensord, RandRotated, RandFlipd, RandZoomd, Spacingd, SpatialPadd, CenterSpatialCropd , LoadNiftid  
from monai.networks.nets import densenet121

Below are the errors:

ImportError: cannot import name 'LoadNiftid' from 'monai.transforms' (/usr/local/lib/python3.7/dist-packages/monai/transforms/__init__.py)

ImportError: cannot import name 'densenet121' from 'monai.networks.nets' (/usr/local/lib/python3.7/dist-packages/monai/networks/nets/__init__.py)

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #2032 .

### Description
This PR added alias for all kinds of DenseNets.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by yiheng-wang-nv — APPROVED** [review]
Thanks!

**Comment by wyli** [comment]
we should do the same for seresnet.

**Comment by Nic-Ma** [comment]
> we should do the same for seresnet.

OK, let me try to add alias for SeResNet and AHNet, etc.
Thanks.

**Pull request merged**
