### PR TITLE
fix dints bug

### PR DESCRIPTION
**Pull request by dongyang0122**
Signed-off-by: dongy <dongy@nvidia.com>

Fixed a bug in dints network construction when num_depths is greater than 4.

A few sentences describing the changes proposed in this pull request.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by heyufan1995** [comment]
@heyufan1995

**Review by wyli — APPROVED** [review]

**Comment by dongyang0122** [comment]
> /black

Please consider to merge this PR. I have verified the changes with real datasets.

**Pull request merged**
