### PR TITLE
has_status_keys needs a default value for default_message

### LINKED ISSUE #6569: Lazy resampling integration test failure
**Describe the bug**
```
======================================================================
ERROR: test_training (__main__.IntegrationLazyResampling)
----------------------------------------------------------------------
Traceback (most recent call last):
test case: {'root_dir': '/tmp/tmpsh17fpf7', 'device': 'cuda:0', 'cachedataset': 0, 'readers': (None, None), 'num_workers': 2, 'lazy': False}
----------
Epoch 1/5
1/3, train_loss:0.6714
img2.nii.gz - [65, 19, 3, 22, 35, 67]
img2.nii.gz - [66, 18, 25, 0, 86, 16]
img2.nii.gz - [0, 84, 0, 25, 68, 34]
img2.nii.gz - [84, 0, 0, 25, 34, 68]
2/3, train_loss:0.5815
img1.nii.gz - [38, 46, 86, 14, 8, 19]
img1.nii.gz - [71, 13, 78, 22, 27, 0]
img1.nii.gz - [34, 50, 67, 33, 15, 12]
img1.nii.gz - [76, 8, 88, 12, 27, 0]
3/3, train_loss:0.6870
img0.nii.gz - [53, 31, 100, 0, 15, 12]
img0.nii.gz - [53, 31, 100, 0, 24, 3]
img0.nii.gz - [0, 84, 59, 41, 8, 19]
img0.nii.gz - [0, 84, 100, 0, 0, 27]
----------
Epoch 2/5
1/3, train_loss:0.7074
img1.nii.gz - [0, 84, 100, 0, 16, 11]
img1.nii.gz - [47, 37, 19, 81, 23, 4]
  File "tests/test_integration_lazy_samples.py", line 215, in test_training
    self.train_and_infer(i)
  File "tests/test_integration_lazy_samples.py", line 192, in train_and_infer
    results_expected = run_training_test(
  File "tests/test_integration_lazy_samples.py", line 154, in run_training_test
    invertible, reasons = has_status_keys(batch_data, TraceStatusKeys.PENDING_DURING_APPLY)
TypeError: has_status_keys() missing 1 required positional argument: 'default_msg'

----------------------------------------------------------------------
Ran 1 test in 17.147s

FAILED (errors=1)
```

### PR DESCRIPTION
**Pull request by atbenmurray**
Fixes #6569.

### Description

A few sentences describing the changes proposed in this pull request.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]
Please run the associated CI tests locally before we merge this PR.
Thanks in advance.

**Comment by atbenmurray** [comment]
> Please run the associated CI tests locally before we merge this PR. Thanks in advance.

Done.

======================================================================
ERROR: test_get_history (tests.test_auto3dseg_hpo.TestHPO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ben/git/monai_f_lazy_min/tests/test_auto3dseg_hpo.py", line 180, in test_get_history
    NNIGen().run_algo(obj_filename, self.work_dir)
  File "/home/ben/git/monai_f_lazy_min/monai/apps/auto3dseg/hpo_gen.py", line 231, in run_algo
    self.algo.train(self.params)
  File "/home/ben/git/monai_f_lazy_min/monai/apps/auto3dseg/bundle_gen.py", line 269, in train
    return self._run_cmd(cmd)
  File "/home/ben/git/monai_f_lazy_min/monai/apps/auto3dseg/bundle_gen.py", line 246, in _run_cmd
    return subprocess.run(cmd_list, env=ps_environ, check=True)
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['torchrun', '--nnodes=1', '--nproc_per_node=2', '/tmp/tmpdrsvo5n1/workdir/swinunetr_0_override_None/scripts/train.py', 'run', "--config_file='/tmp/tmpdrsvo5n1/workdir/swinunetr_0_override_None/configs/hyper_parameters.yaml','/tmp/tmpdrsvo5n1/workdir/swinunetr_0_override_None/configs/network.yaml','/tmp/tmpdrsvo5n1/workdir/swinunetr_0_override_None/configs/transforms_infer.yaml','/tmp/tmpdrsvo5n1/workdir/swinunetr_0_override_None/configs/transforms_train.yaml','/tmp/tmpdrsvo5n1/workdir/swinunetr_0_override_None/configs/transforms_validate.yaml'"]' returned non-zero exit status 1.

======================================================================
ERROR: test_run_algo (tests.test_auto3dseg_hpo.TestHPO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ben/git/monai_f_lazy_min/tests/test_auto3dseg_hpo.py", line 148, in test_run_algo
    NNIGen().run_algo(obj_filename, self.work_dir)
  File "/home/ben/git/monai_f_lazy_min/monai/apps/auto3dseg/hpo_gen.py", line 231, in run_algo
    self.algo.train(self.params)
  File "/home/ben/git/monai_f_lazy_min/monai/apps/auto3dseg/bundle_gen.py", line 269, in train
    return self._run_cmd(cmd)
  File "/home/ben/git/monai_f_lazy_min/monai/apps/auto3dseg/bundle_gen.py", line 246, in _run_cmd
    return subprocess.run(cmd_list, env=ps_environ, check=True)
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['torchrun', '--nnodes=1', '--nproc_per_node=2', '/tmp/tmp5tbn0574/workdir/swinunetr_0_override_None/scripts/train.py', 'run', "--config_file='/tmp/tmp5tbn0574/workdir/swinunetr_0_override_None/configs/hyper_parameters.yaml','/tmp/tmp5tbn0574/workdir/swinunetr_0_override_None/configs/network.yaml','/tmp/tmp5tbn0574/workdir/swinunetr_0_override_None/configs/transforms_infer.yaml','/tmp/tmp5tbn0574/workdir/swinunetr_0_override_None/configs/transforms_train.yaml','/tmp/tmp5tbn0574/workdir/swinunetr_0_override_None/configs/transforms_validate.yaml'"]' returned non-zero exit status 1.

======================================================================
ERROR: test_run_optuna (tests.test_auto3dseg_hpo.TestHPO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ben/git/monai_f_lazy_min/tests/test_auto3dseg_hpo.py", line 163, in test_run_optuna
    study.optimize(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/optuna/study/study.py", line 425, in optimize
    _optimize(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/home/ben/git/monai_f_lazy_min/monai/apps/auto3dseg/hpo_gen.py", line 336, in __call__
    self.run_algo(obj_filename, output_folder, template_path)
  File "/home/ben/git/monai_f_lazy_min/monai/apps/auto3dseg/hpo_gen.py", line 394, in run_algo
    self.algo.train(self.params)
  File "/home/ben/git/monai_f_lazy_min/monai/apps/auto3dseg/bundle_gen.py", line 269, in train
    return self._run_cmd(cmd)
  File "/home/ben/git/monai_f_lazy_min/monai/apps/auto3dseg/bundle_gen.py", line 246, in _run_cmd
    return subprocess.run(cmd_list, env=ps_environ, check=True)
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['torchrun', '--nnodes=1', '--nproc_per_node=2', '/tmp/tmphp864i25/optuna_test/swinunetr_0_override_learning_rate_0.0001/scripts/train.py', 'run', "--config_file='/tmp/tmphp864i25/optuna_test/swinunetr_0_override_learning_rate_0.0001/configs/hyper_parameters.yaml','/tmp/tmphp864i25/optuna_test/swinunetr_0_override_learning_rate_0.0001/configs/network.yaml','/tmp/tmphp864i25/optuna_test/swinunetr_0_override_learning_rate_0.0001/configs/transforms_infer.yaml','/tmp/tmphp864i25/optuna_test/swinunetr_0_override_learning_rate_0.0001/configs/transforms_train.yaml','/tmp/tmphp864i25/optuna_test/swinunetr_0_override_learning_rate_0.0001/configs/transforms_validate.yaml'", '--learning_rate=0.0001']' returned non-zero exit status 1.

======================================================================
ERROR: test_ensemble (tests.test_auto3dseg_ensemble.TestEnsembleBuilder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ben/git/monai_f_lazy_min/tests/test_auto3dseg_ensemble.py", line 174, in test_ensemble
    algo.train(_train_param)
  File "/tmp/tmpnplvhhyt/workdir/algorithm_templates/dints/scripts/algo.py", line 390, in train
  File "/home/ben/git/monai_f_lazy_min/monai/apps/auto3dseg/bundle_gen.py", line 246, in _run_cmd
    return subprocess.run(cmd_list, env=ps_environ, check=True)
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['torchrun', '--nnodes=1', '--nproc_per_node=2', '/tmp/tmpzixj5eoc/workdir/dints_0/scripts/train.py', 'run', "--config_file='/tmp/tmpzixj5eoc/workdir/dints_0/configs/hyper_parameters.yaml','/tmp/tmpzixj5eoc/workdir/dints_0/configs/hyper_parameters_search.yaml','/tmp/tmpzixj5eoc/workdir/dints_0/configs/network.yaml','/tmp/tmpzixj5eoc/workdir/dints_0/configs/network_search.yaml','/tmp/tmpzixj5eoc/workdir/dints_0/configs/transforms_infer.yaml','/tmp/tmpzixj5eoc/workdir/dints_0/configs/transforms_train.yaml','/tmp/tmpzixj5eoc/workdir/dints_0/configs/transforms_validate.yaml'", '--training#num_images_per_batch=2', '--training#num_epochs=2', '--training#num_epochs_per_validation=1']' returned non-zero exit status 1.

======================================================================
ERROR: test_cuda_0_2_batches_1_dimensions_1_channels_2_classes_2_mixtures (tests.test_gmm.GMMTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func
    return func(*(a + p.args), **p.kwargs, **kw)
  File "/home/ben/git/monai_f_lazy_min/tests/test_gmm.py", line 287, in test_cuda
    gmm = GaussianMixtureModel(features_tensor.size(1), mixture_count, class_count, verbose_build=True)
  File "/home/ben/git/monai_f_lazy_min/monai/networks/layers/gmm.py", line 44, in __init__
    self.compiled_extension = load_module(
  File "/home/ben/git/monai_f_lazy_min/monai/_extensions/loader.py", line 89, in load_module
    module = load(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'gmm_1_2_1_Linux_3_10_11_20_11_7'

======================================================================
ERROR: test_cuda_1_1_batches_1_dimensions_5_channels_2_classes_1_mixtures (tests.test_gmm.GMMTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func
    return func(*(a + p.args), **p.kwargs, **kw)
  File "/home/ben/git/monai_f_lazy_min/tests/test_gmm.py", line 287, in test_cuda
    gmm = GaussianMixtureModel(features_tensor.size(1), mixture_count, class_count, verbose_build=True)
  File "/home/ben/git/monai_f_lazy_min/monai/networks/layers/gmm.py", line 44, in __init__
    self.compiled_extension = load_module(
  File "/home/ben/git/monai_f_lazy_min/monai/_extensions/loader.py", line 89, in load_module
    module = load(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'gmm_5_2_1_Linux_3_10_11_20_11_7'

======================================================================
ERROR: test_cuda_2_1_batches_2_dimensions_2_channels_4_classes_4_mixtures (tests.test_gmm.GMMTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func
    return func(*(a + p.args), **p.kwargs, **kw)
  File "/home/ben/git/monai_f_lazy_min/tests/test_gmm.py", line 287, in test_cuda
    gmm = GaussianMixtureModel(features_tensor.size(1), mixture_count, class_count, verbose_build=True)
  File "/home/ben/git/monai_f_lazy_min/monai/networks/layers/gmm.py", line 44, in __init__
    self.compiled_extension = load_module(
  File "/home/ben/git/monai_f_lazy_min/monai/_extensions/loader.py", line 89, in load_module
    module = load(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'gmm_2_4_1_Linux_3_10_11_20_11_7'

======================================================================
ERROR: test_cuda_3_1_batches_3_dimensions_1_channels_2_classes_1_mixtures (tests.test_gmm.GMMTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func
    return func(*(a + p.args), **p.kwargs, **kw)
  File "/home/ben/git/monai_f_lazy_min/tests/test_gmm.py", line 287, in test_cuda
    gmm = GaussianMixtureModel(features_tensor.size(1), mixture_count, class_count, verbose_build=True)
  File "/home/ben/git/monai_f_lazy_min/monai/networks/layers/gmm.py", line 44, in __init__
    self.compiled_extension = load_module(
  File "/home/ben/git/monai_f_lazy_min/monai/_extensions/loader.py", line 89, in load_module
    module = load(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'gmm_1_2_1_Linux_3_10_11_20_11_7_v1'

======================================================================
ERROR: test_load (tests.test_gmm.GMMTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ben/git/monai_f_lazy_min/tests/test_gmm.py", line 310, in test_load
    load_module("gmm", {"CHANNEL_COUNT": 2, "MIXTURE_COUNT": 2, "MIXTURE_SIZE": 3}, verbose_build=True)
  File "/home/ben/git/monai_f_lazy_min/monai/_extensions/loader.py", line 89, in load_module
    module = load(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/ben/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'gmm_2_2_3_Linux_3_10_11_20_11_7'

**Comment by atbenmurray** [comment]
@Nic-Ma Are the above CI errors a problem or incidental?

**Comment by Nic-Ma** [comment]
> @Nic-Ma Are the above CI errors a problem or incidental?

Hi @wyli ,

Do you know anything about this error?

Thanks.

**Pull request merged**
