### PR TITLE
1814 Enhance transform chain error logging

### LINKED ISSUE #1814: apply_transform better error msg
**Is your feature request related to a problem? Please describe.**
follow up of https://github.com/Project-MONAI/MONAI/discussions/1784#discussioncomment-504257 the error message from the `apply_transform` function could be improved
- https://github.com/Project-MONAI/MONAI/blob/70388fa298384f698dfb3ba790e3bedb1ffcb07b/monai/transforms/transform.py#L48

**Describe the solution you'd like**
could use `DataStatsd` to print additional type/shape info before raising the RuntimeError?

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #1814 .

### Description
This PR added `DataStats` to log more data information if an error happened in the transform chain.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by wyli — APPROVED** [review]
thanks! please merge if you could confirm that it works fine with the multiprocess loaders

**Comment by Nic-Ma** [comment]
> thanks! please merge if you could confirm that it works fine with the multiprocess loaders

Hi @wyli ,

Thanks for your review.
I tested with our 3D segmentation integration test, it works fine with regular training and exception in transform case.

Thanks.

**Pull request merged**
