### PR TITLE
Scale intensity

### PR DESCRIPTION
**Pull request by rijobro**
### Description
ScaleIntensity as numpy/torch transform. Requires #2829.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests`.

### CODE REVIEW

**Review by wyli — APPROVED** [review]
thanks

**Review by Nic-Ma — APPROVED** [review]
Looks good to me, thanks for the quick update!
We may need to address the `# type: ignore` type annotation later.

**Pull request merged**
