### PR TITLE
3610 review array copy perf

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

follow-up of #3610

### Description
review and remove unnecessary array flatten copies

### Status
**Work in progress**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
Hi @Nic-Ma, I've double-checked this PR doesnt' improve the performance much. I'm closing it.

**Comment by Nic-Ma** [comment]
> Hi @Nic-Ma, I've double-checked this PR doesnt' improve the performance much. I'm closing it.

Sure, let's revisit it in future if necessary.
Thanks for your investigation!

**Pull request closed without merging**
