### PR TITLE
2975 torch fgbgtoindices

### LINKED ISSUE #2975: Torch `FgBgToIndices`
BTW, to cache the foreground & background indices for pos / neg crop, could you please help also add Tensor backend for `FgBgToIndices` transform?

Thanks in advance.

_Originally posted by @Nic-Ma in https://github.com/Project-MONAI/MONAI/pull/2967#pullrequestreview-757677818_

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Fixes #2975

### Description
- ~unravel_index is still in numpy, otherwise it supports both backends~ added both backends

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Mark: training time with this PR around `60s`, and without this PR `56-58s`.

Thanks.

**Comment by wyli** [comment]
> Mark: training time with this PR around `60s`, and without this PR `56-58s`.
> 
> Thanks.

I looked into this issue,  the root cause is that
coordinates were (1) converted into list of numbers:
https://github.com/Project-MONAI/MONAI/blob/28fb7d6af1a74aac1576637403603de1c3d8a59a/monai/transforms/utils.py#L427
and (2) the numbers are converted into tensors:
https://github.com/Project-MONAI/MONAI/blob/28fb7d6af1a74aac1576637403603de1c3d8a59a/monai/transforms/croppad/array.py#L405

Previously `fg_indices`, `bg_indices` were numpy arrays, so there's no step (1) conversion.

So I think the issue is not really in this PR, it's from the `generate_pos_neg_label_crop_centers` and `SpatialCrop` of `RandCropByPosNegLabeld`.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

OK, thanks for your investigation!
Let me try to fix the issue in a separate PR ASAP.

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> OK, thanks for your investigation! Let me try to fix the issue in a separate PR ASAP.
> 
> Thanks.

thanks! please help fix the issue and we can merge this PR after that

**Comment by Nic-Ma** [comment]
Sure, sounds good to me. Investigating.

Thanks.

**Comment by rijobro** [comment]
This looks great, thanks!

**Comment by Nic-Ma** [comment]
I think we already found the root cause of the performance issue, no need to put the `fg / bg indices` on GPU as we actually need to move it to CPU and index image.
So I will merge this PR first, then create another PR to optimize the logic.

Thanks.

**Review by Nic-Ma — APPROVED** [review]

**Pull request merged**
