### PR TITLE
5 checkpoint event-handler

### PR DESCRIPTION
**Pull request by Nic-Ma**
Hi All,

Thanks for ignite team who provided powerful checkpoint management API.
In order to unify & simplify the event-handler APIs and develop well-structured event-handlers later,
I tried to **organize** event-handlers in categories, like _checkpoint_handler, timer_handler, stats_logger, etc._ And every category can handle **all the 8 ignite Events** during training.

this PR includes the base **traine_handler** and 2 sub handlers: **TimerHandler, CheckpointHandler**
The CheckpointHandler can support _"restore training", "save based on validation", "save based on step num", "save based on epoch num", "save based on excepition/train_end", etc._

the usage is as below:
```py
handlers = [
    TimerHandler(),
    CheckpointHandler(
        network=network,  # the model to save or restore
        optimizer=optimizer,  # the optimizer to save or restore
        lr_policy=lr_policy,  # the lr_policy to save or restore
        restore_ckpt=False,  # whether to restore model, optimizer, lr_policy
        restore_session=False,  # whether to restore previous epoch, step, etc.
        restore_path=None,  # the checkpoint file path to restore training
        save_ckpt=True,  # whether to save model, optimizer, lr_policy
        save_session=True,  # whether to save current epoch, current step, etc.
        save_path=output_dir,  # the dir to save models
        save_val_model=True,  # whether to save model during validation
        val_n_saved=1,  # save top N models sorted by validation metric
        key_metric_name='accuracy',  # use which metric to select model
        epoch_save_interval=5,  # save model every 5 epochs
        epoch_n_saved=None,  # 'None' is to save all models
        step_save_interval=400,  # save model every 400 intervals
        step_n_saved=None  # 'None' is to save all models
    )
for handler in handlers:
    handler.start(engine)
```
And the saved models will be:

```
checkpoint_step=400.pth
checkpoint_step=800.pth
checkpoint_epoch=1.pth
checkpoint_final_step=1000.pth
checkpoint_key_metric=0.9387.pth
```

As ignite official code doesn't provide rich StatsLogger related APIs, I will create a **StatsLogger** category.

Could you please help review this PR when you are available?
Thanks in advance.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
The CI/CD error may because the test machine doesn't install the latest version PyTorch Ignite.
Thanks.

**Comment by wyli** [comment]
Hi @Nic-Ma, the CI test has to be fixed before we start reviewing. in case you didn't see it, logs are here: https://github.com/Project-MONAI/MONAI/commit/1f6e92fd35b8bac4e5dcfa4914c6c37d767af256/checks?check_suite_id=409532503

**Comment by Nic-Ma** [comment]
> Hi @Nic-Ma, the CI test has to be fixed before we start reviewing. in case you didn't see it, logs are here: https://github.com/Project-MONAI/MONAI/commit/1f6e92fd35b8bac4e5dcfa4914c6c37d767af256/checks?check_suite_id=409532503

Hi @wyli ,

Normal Ignite is too old and has some issues on checkpoint and Event related logic, changed to nigtly build and CI test passed.
Thanks.

**Comment by wyli** [comment]
Thanks, as we discussed the `trainhandler` object is out of scope of the current sprint, let's postpone this PR. But the `Checkpoint` and `DisckSaver` from nightly release ignite are useful, we should use those objects after implementing a minimal training loop

**Comment by Nic-Ma** [comment]
> Thanks, as we discussed the `trainhandler` object is out of scope of the current sprint, let's postpone this PR. But the `Checkpoint` and `DisckSaver` from nightly release ignite are useful, we should use those objects after implementing a minimal training loop

Hi @wyli ,

OK, I agree to postpone this PR for later sprints as it contains more high level design, let's focus on minimal demo example first.
For this sprint, I think we only need to save a model to file after training.
Thanks.

**Comment by Nic-Ma** [comment]
Temporarily close for this sprint.

**Pull request closed without merging**
