### PR TITLE
Update nifti_writer.py

### PR DESCRIPTION
**Pull request by Alxaline**
Fixes # .

### Description
Change dtype for return

### Status
**Ready/Work in progress/Hold**
Ready

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
thank you, could you help update the other two places:
https://github.com/Project-MONAI/MONAI/blob/5bc1ac318c96bf448d2c0e5551101aefdf518bce/monai/data/nifti_writer.py#L103
https://github.com/Project-MONAI/MONAI/blob/5bc1ac318c96bf448d2c0e5551101aefdf518bce/monai/data/nifti_writer.py#L115

and please sign the commit:
https://github.com/Project-MONAI/MONAI/blob/master/CONTRIBUTING.md#signing-your-work
https://github.com/Project-MONAI/MONAI/pull/1299/checks?check_run_id=1463392565

**Comment by wyli** [comment]
HI @Nic-Ma, there's a comment in the docstring: 
`To be compatible with other modules, the output data type is always np.float32`
perhaps we need a new option `output_dtype` and defaults to `np.float32`?

https://github.com/Project-MONAI/MONAI/blob/5bc1ac318c96bf448d2c0e5551101aefdf518bce/monai/data/nifti_writer.py#L87-L88

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I think we discussed this topic before, as PyTorch computation always uses float32 type, we forced it to float32.
I am not sure whether the situation changed or any feature request for float64?
If yes, I agree to add the option for the data type.

Thanks.

**Review by wyli — APPROVED** [review]
thanks, this PR is a non-breaking change making the API more flexible

**Pull request merged**
