### PR TITLE
Make ViT and Unetr to be torchscript comaptible

### LINKED ISSUE #7936: Module 'SABlock' has no attribute 'causal_mask'
```
[2024-07-20T23:15:47.067Z] ======================================================================
[2024-07-20T23:15:47.067Z] ERROR: test_script_00 (tests.test_vit.TestViT)
[2024-07-20T23:15:47.067Z] ----------------------------------------------------------------------
[2024-07-20T23:15:47.067Z] Traceback (most recent call last):
[2024-07-20T23:15:47.067Z]   File "/usr/local/lib/python3.10/dist-packages/parameterized/parameterized.py", line 620, in standalone_func
[2024-07-20T23:15:47.067Z]     return func(*(a + p.args), **p.kwargs, **kw)
[2024-07-20T23:15:47.067Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/tests/test_vit.py", line 114, in test_script
[2024-07-20T23:15:47.067Z]     torch.jit.script(net)
[2024-07-20T23:15:47.067Z]   File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 1338, in script
[2024-07-20T23:15:47.067Z]     return torch.jit._recursive.create_script_module(
[2024-07-20T23:15:47.067Z]   File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 558, in create_script_module
[2024-07-20T23:15:47.067Z]     return create_script_module_impl(nn_module, concrete_type, stubs_fn)
[2024-07-20T23:15:47.067Z]   File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 631, in create_script_module_impl
[2024-07-20T23:15:47.067Z]     script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
[2024-07-20T23:15:47.067Z]   File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 647, in _construct
[2024-07-20T23:15:47.067Z]     init_fn(script_module)
[2024-07-20T23:15:47.067Z]   File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 607, in init_fn
[2024-07-20T23:15:47.067Z]     scripted = create_script_module_impl(
[2024-07-20T23:15:47.067Z]   File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 631, in create_script_module_impl
[2024-07-20T23:15:47.067Z]     script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
[2024-07-20T23:15:47.067Z]   File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 647, in _construct
[2024-07-20T23:15:47.067Z]     init_fn(script_module)
[2024-07-20T23:15:47.067Z]   File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 607, in init_fn
[2024-07-20T23:15:47.067Z]     scripted = create_script_module_impl(
[2024-07-20T23:15:47.067Z]   File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 631, in create_script_module_impl
[2024-07-20T23:15:47.067Z]     script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
[2024-07-20T23:15:47.067Z]   File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 647, in _construct
[2024-07-20T23:15:47.067Z]     init_fn(script_module)
[2024-07-20T23:15:47.067Z]   File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 607, in init_fn
[2024-07-20T23:15:47.067Z]     scripted = create_script_module_impl(
[2024-07-20T23:15:47.067Z]   File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 635, in create_script_module_impl
[2024-07-20T23:15:47.067Z]     create_methods_and_properties_from_stubs(
[2024-07-20T23:15:47.067Z]   File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 467, in create_methods_and_properties_from_stubs
[2024-07-20T23:15:47.067Z]     concrete_type._create_methods_and_properties(
[2024-07-20T23:15:47.067Z] RuntimeError: 
[2024-07-20T23:15:47.067Z] Module 'SABlock' has no attribute 'causal_mask' :
[2024-07-20T23:15:47.067Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/monai/networks/blocks/selfattention.py", line 137
[2024-07-20T23:15:47.067Z]     
[2024-07-20T23:15:47.067Z]         if self.causal:
[2024-07-20T23:15:47.067Z]             att_mat = att_mat.masked_fill(self.causal_mask[:, :, : x.shape[1], : x.shape[1]] == 0, float("-inf"))
[2024-07-20T23:15:47.067Z]                                           ~~~~~~~~~~~~~~~~ <--- HERE
[2024-07-20T23:15:47.067Z]     
[2024-07-20T23:15:47.067Z]         att_mat = att_mat.softmax(dim=-1)
[2024-07-20T23:15:47.067Z] 
```

### PR DESCRIPTION
**Pull request by KumoLiu**
Fixes #7936

### Description
- Pre-define `self.causal_mask = torch.Tensor()` before register buffer
- Move norm_cross_attn and cross_attn out of if block

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by KumoLiu** [comment]
Hi @ericspod and @virginiafdez, the issue is introduced by merging the gen-ai-dev branch: https://github.com/Project-MONAI/MONAI/pull/7886. ViT and Unetr can't support torchscript converting after merging the PR.
Could you please help review this PR? Thanks!

**Review by virginiafdez — COMMENTED** [review]
I have checked this with Eric. The only concern we have is in selfattention.py, when you add the CrossAttention block as an attribute by default, it might lead to incompatibilities when loading the module weights from old models, as weights are expected to be there unless you choose strict=False

**Review by ericspod — APPROVED** [review]
Let's put this through now and we'll come back to the issue of weights later, if we're lucky no one's saved models are broken by this anyway.

**Comment by KumoLiu** [comment]
> I have checked this with Eric. The only concern we have is in selfattention.py, when you add the CrossAttention block as an attribute by default, it might lead to incompatibilities when loading the module weights from old models, as weights are expected to be there unless you choose strict=False

Yes, it will potential be an issue, may need to add a `load_old_state_dict` as @ericspod suggested to fix the loading issue.

**Pull request merged**
