### PR TITLE
Pytype fix

### PR DESCRIPTION
**Pull request by rijobro**
Fixes https://github.com/Project-MONAI/MONAI/pull/2121#issuecomment-833551183.

### Description
Avoid most recent pytype (2021.05.04) due to https://github.com/google/pytype/issues/909.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Comment by wyli** [comment]
according to the pytype ticket, looks like it's actually the attrs issue...  https://github.com/python-attrs/attrs/releases

**Comment by rijobro** [comment]
Ok. So we add in `attrs<21.1.0` before pytype and then remove it once their issue is closed?

**Comment by wyli** [comment]
> Also looks like the `attrs` bug has already [been fixed](https://github.com/python-attrs/attrs/issues/752), so the problem will solve itself when they do their next release.

shall we close this and wait?

**Comment by wyli** [comment]
sounds good

**Pull request merged**
