### PR TITLE
Add min tests cmd to runtests script

### PR DESCRIPTION
**Pull request by Nic-Ma**
### Description
This PR added the `min` command to `runtests.sh` script, to run it in the same way as other tests.
Non-breaking enhancement for the local test.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by wyli — APPROVED** [review]
not sure how to ensure it's running with the min. environment

**Comment by Nic-Ma** [comment]
> not sure how to ensure it's running with the min. environment

Good question, let me try to change the CI script to use `runtests.sh` to test it.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

When I try to update the CI config, I got an error:
```
nma@apt-sh-ai:~/WorkSpace/Deep_Learning/Clara_SDK/medical/MONAI$ git push origin HEAD
Username for 'https://github.com': Nic-Ma
Password for 'https://Nic-Ma@github.com': 
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 24 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 472 bytes | 472.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/Nic-Ma/MONAI.git
 ! [remote rejected]   HEAD -> add-min-tests-cmd (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/pythonapp.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/Nic-Ma/MONAI.git'
```
Should I apply for some permission?

Thanks.

**Comment by wyli** [comment]
I think the error 'refusing to allow a Personal Access Token to create or update workflow `.github/workflows/pythonapp.yml` without `workflow` scope' is because you didn't create your github token with this permission

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Cool, thanks for your help!

**Pull request merged**
