### PR TITLE
Autorunner clear gpu mem allocatoins of dataanalyzer

### PR DESCRIPTION
**Pull request by myron**
clears gpu mem allocatoins of dataanalyzer

For some reason, after data analyzer finishes, GPU memory was not fully released, and about 1GB persisted, 
this fix helps.

PS: about 300MB still persists on CUDA:0 device even after this fix, but unclear why yet

### CODE REVIEW

**Comment by wyli** [comment]
the 300MB is used by the cuda driver and won't be released unless quitting the process https://github.com/pytorch/pytorch/issues/20532

**Review by wyli — APPROVED** [review]

**Comment by myron** [comment]
> the 300MB is used by the cuda driver and won't be released unless quitting the process [pytorch/pytorch#20532](https://github.com/pytorch/pytorch/issues/20532)

interesting, thank you for letting me know! and thank you for merging quickly

**Pull request merged**
