### PR TITLE
2495 Enhance PatchEmbeddingBlock

### LINKED ISSUE #2495: Minor code format issue in PatchEmbeddingBlock
**Describe the bug**
If running `/black`, the change in the newly added PatchEmbeddingBlock will cause CI error.
https://github.com/Project-MONAI/MONAI/blob/dev/monai/networks/blocks/patchembedding.py
And there are also some other potential issues about the input args.

### PR DESCRIPTION
**Pull request by Nic-Ma**
partly fixes issue 2495 .

### Description
This PR enhanced the `PatchEmbeddingBlock` to fix CI tests and fixed wrong data type, removed unused args.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

There is only 1 change is to the code, I removed the `classification` arg of  PatchEmbeddingBlock as it's not used in the code at all.

Thanks.

**Comment by wyli** [comment]
Could you please help confirm the changes in this PR? @ahatamiz

**Review by yiheng-wang-nv — APPROVED** [review]

**Review by ahatamiz — APPROVED** [review]
Thanks. Changes look nice.

**Comment by ahatamiz** [comment]
> Could you please help confirm the changes in this PR? @ahatamiz

Just reviewed. Everything looks good.

**Comment by wyli** [comment]
Thanks @ahatamiz.  Hi @Nic-Ma why is this partly fixing #2495? could you please document the missing parts?

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I didn't check every line of UNETR related logic, so I marked as "partly". I will try to double confirm ASAP later.

Thanks.

**Pull request merged**
