### PR TITLE
Fixed an error in DiNTS model implementation and enabled act and norm layer options

### PR DESCRIPTION
**Pull request by dongyang0122**
Signed-off-by: dongy <dongy@nvidia.com>

Fixes # .

### Description
A few sentences describing the changes proposed in this pull request.Fixed an error in DiNTS model implementation and enabled act and norm layer options.

### Status
Ready

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by yiheng-wang-nv — COMMENTED** [review]
Hi @dongyang0122 , it looks good to me, could you please also add the unit tests for act and norm? Thanks!

**Comment by dongyang0122** [comment]
@yiheng-wang-nv thanks for the comments! test cases are updated.

**Review by yiheng-wang-nv — APPROVED** [review]

**Pull request merged**
