### PR TITLE
Fixing Numpy requirements to exclude 2.0

### PR DESCRIPTION
**Pull request by ericspod**
### Description

This fixes the version of Numpy to be less than 2.0 so that we can get a working setup guaranteed. Numpy 2.0 isn't supported yet by MONAI and will need a number of changes to be compatible. 

This is only sometimes a problem because a number of dependencies we have require Numpy<2.0. When these are absent however, such as with minimal installs, Numpy 2.0 can be installed and causes problems. This is a temporary fix until we have worked out an update that's compatible with versions before and after 2.0.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by ericspod** [comment]
@wyli @pxLi @YanxuanLiu @KumoLiu @Nic-Ma I need one of you to initiate the Blossom tests to let this through. Other PRs can't pass because certain tests are failing if they install Numpy 2.0. We should update things to be compatible but this is the temporary fix we need for now.

**Review by Nic-Ma — APPROVED** [review]

**Comment by MattTheCuber** [comment]
Is there plans to make MONAI support Numpy v2 in the near future?

**Comment by ericspod** [comment]
Hi @MattTheCuber we are discussing developing a dependency update policy at #8303 so we can balance keeping older versions for those that need them against updating requirements appropriately. For Numpy 2 if you don't need to use any dependencies which do not work with it, you can install MONAI then upgrade the version of Numpy that gets installed. That should work as we've made MONAI compatible but added this exclusion to ensure the install process would produce a valid configuration.

**Pull request merged**
