### PR TITLE
fixes iterable tests

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Fixes https://github.com/Project-MONAI/MONAI/runs/4055342179?check_suite_focus=true

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]
Looks good to me.

Thanks.

**Comment by Nic-Ma** [comment]
May I know why "/integration-test" doesn't work?

Thanks.

**Comment by wyli** [comment]
> May I know why "/integration-test" doesn't work?
> 
> Thanks.

Thanks, first time I see this error, I'll rerun it and double check.

**Pull request merged**
