### PR TITLE
676 Update all the quick import in modules

### LINKED ISSUE #676: Missing quick import of networks module
**Is your feature request related to a problem? Please describe.**
We added many quick `import` in `__init__.py`, missing it for networks.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #676 .

### Description
This PR updated all the `__init__.py` for quick import.

### Status
**Ready**

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [ ] Docstrings/Documentation updated

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your review, I double checked import path again and updated the PR.
Could you please help review it again?
Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> Thanks for your review, I double checked import path again and updated the PR.
> Could you please help review it again?
> Thanks.

thanks I approved this

**Pull request merged**
