### PR TITLE
Streamlined Rearrange in SpatialAttentionBlock

### PR DESCRIPTION
**Pull request by borisfom**
The Rearrange code failed dynamo export in 24.09 container: 
https://github.com/pytorch/pytorch/issues/137629
While we can't still use dynamo export with TRT in 23.09, I also noticed that my workaround improved runtime by about 1 second end-to-end for 100 seconds run. 

### Description

Replaced einops Rearrange with reshape/transpose 

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]

**Comment by Nic-Ma** [comment]
PR looks good to me, please ensure the logic is covered by unit tests.
@yiheng-wang-nv @KumoLiu Please help review this PR.

Thanks.

**Review by KumoLiu — APPROVED** [review]
Hi @borisfom, thanks for the update. Overall looks good to me.

We've already code freeze for version 1.4, and QA is expected to complete their testing by the end of this week. As a result, this PR may not be included in the 1.4 release. Thank you for your understanding!

**Comment by borisfom** [comment]
@KumoLiu : Sure, obviously it doesn't make it to 1.4, so the target is dev branch. Can we get it merged?

**Pull request merged**
