### PR TITLE
Update test_nnunetv2runner

### LINKED ISSUE #7013: test_nnunetv2runner
test nnunetv2runner is broken after the recent update https://pypi.org/project/nnunetv2/#history
```
[2023-09-19T22:32:39.490Z] ======================================================================
[2023-09-19T22:32:39.490Z] ERROR: test_nnunetv2runner (__main__.TestnnUNetV2Runner)
[2023-09-19T22:32:39.490Z] ----------------------------------------------------------------------
[2023-09-19T22:32:39.490Z] Traceback (most recent call last):
[2023-09-19T22:32:39.490Z]   File "/home/jenkins/agent/workspace/Monai-notebooks/MONAI/tests/test_integration_nnunetv2_runner.py", line 89, in test_nnunetv2runner
[2023-09-19T22:32:39.490Z]     runner.predict_ensemble_postprocessing()
[2023-09-19T22:32:39.490Z]   File "/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/apps/nnunet/nnunetv2_runner.py", line 900, in predict_ensemble_postprocessing
[2023-09-19T22:32:39.490Z]     self.predict(
[2023-09-19T22:32:39.490Z]   File "/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/apps/nnunet/nnunetv2_runner.py", line 827, in predict
[2023-09-19T22:32:39.490Z]     from nnunetv2.inference.predict_from_raw_data import predict_from_raw_data
[2023-09-19T22:32:39.490Z] ImportError: cannot import name 'predict_from_raw_data' from 'nnunetv2.inference.predict_from_raw_data' (/usr/local/lib/python3.10/dist-packages/nnunetv2/inference/predict_from_raw_data.py)
[2023-09-19T22:32:39.490Z] 
[2023-09-19T22:32:39.490Z] ----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by KumoLiu**
Fixes #7013 #7478

### Description
replace `predict_from_raw_data` with `nnUNetPredictor` in test_nnunetv2runner

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by ericspod** [comment]
The change nnUNet that this fixes appears to be in version 2.2, we should specify somewhere that this version is needed now. I don't see where we've specified nnUNet as a dependency however.

**Comment by KumoLiu** [comment]
Hi @ericspod, we didn't add nnunetv2 as a dependency requirement, the error log is from daily ci in the blossom which fixed the nnunetv2 version to 2.1 as a workaround, but due to the recent update from nnunet team, It raises another [error](https://github.com/Project-MONAI/MONAI/issues/7478), so I update the nnUNetV2Runner to be compatible with the latest nnunet. Do you think if we need to mention the version in docstring or somewhere else?

**Comment by ericspod** [comment]
> Hi @ericspod, we didn't add nnunetv2 as a dependency requirement, the error log is from daily ci in the blossom which fixed the nnunetv2 version to 2.1 as a workaround, but due to the recent update from nnunet team, It raises another [error](https://github.com/Project-MONAI/MONAI/issues/7478), so I update the nnUNetV2Runner to be compatible with the latest nnunet. Do you think if we need to mention the version in docstring or somewhere else?

We don't mention the requirements for any of the things in the `apps` directory that may be different from what's mentioned in the requirements files. We should have readme files for these or some mention of requirements in the docs. For now we can add a comment about needing the 2.2 version.

**Comment by KumoLiu** [comment]
Mentioned it in the docstring for now.

**Review by ericspod — APPROVED** [review]
LGTM.

**Pull request merged**
