### PR TITLE
[WIP] 2620 Add ITKWriter for other formats

### LINKED ISSUE #2620: Image writer with itk backend to support more output image formats
**Is your feature request related to a problem? Please describe.**
The `SaveImage` transform should be extended to support writing output in different formats using ITK.
https://github.com/Project-MONAI/MONAI/blob/830f8bb34532f63e188b43738f804fff6f059d5b/monai/transforms/io/array.py#L260-L261

the current nifti output doesn't work well with Slicer https://github.com/Project-MONAI/MONAILabel/issues/211

see also https://github.com/InsightSoftwareConsortium/ITK/issues/2663

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #2620 .

### Description
This PR added `ITKWriter` to support more image formats.

### Status
**Work in progress**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @rijobro @wyli @ericspod ,

I am blocked by an issue that I didn't find the API to set affine matrix in ITK image, already filed a ticket to ITK repo:
https://github.com/InsightSoftwareConsortium/ITK/issues/2663
Do you guys have any experience or ideas?
Actually, if someone can share a detailed **python tutorial** or example to save numpy array into many different formats(PNG, DICOM, DICOM series, NIfTI, etc.) with **ITK**, that would be extremely helpful for us. CC @thewtex 

Thanks in advance.

**Comment by wyli** [comment]
I can work on this feature because I revised the reader recently and now familiar with these

**Comment by Nic-Ma** [comment]
> I can work on this feature because I revised the reader recently and now familiar with these

That would be great.
I almost finished this PR for the basic saving with ITK, just blocked by the multi-channels case now, maybe I can complete this PR as initial part of writers? Then you can enhance with more your ideas?

Thanks.

**Comment by wyli** [comment]
We haven't started the review yet, I think this basic implementation needs some more work. I'll start a new PR on this, using some ideas from this PR, what do you think?

**Comment by Nic-Ma** [comment]
> We haven't started the review yet, I think this basic implementation needs some more work. I'll start a new PR on this, using some ideas from this PR, what do you think?

OK, plan sounds good.

Thanks.

**Comment by thewtex** [comment]
> Hi @rijobro @wyli @ericspod ,
> 
> I am blocked by an issue that I didn't find the API to set affine matrix in ITK image, already filed a ticket to ITK repo:
> [InsightSoftwareConsortium/ITK#2663](https://github.com/InsightSoftwareConsortium/ITK/issues/2663)
> Do you guys have any experience or ideas?
> Actually, if someone can share a detailed **python tutorial** or example to save numpy array into many different formats(PNG, DICOM, DICOM series, NIfTI, etc.) with **ITK**, that would be extremely helpful for us. CC @thewtex
> 
> Thanks in advance.

Discussed more in [InsightSoftwareConsortium/ITK#2663](https://github.com/InsightSoftwareConsortium/ITK/issues/2663), but https://gist.github.com/thewtex/9503448d2ad1dfacc2cbd620d95d3dac is hopefully helpful.

**Comment by lukasfolle** [comment]
Any updates on this? I would really appreciate a Dicom out support for MONAI.

**Comment by dyollb** [comment]
Any update on this. I was thinking of writing a custom ImageWriter for our in-house file format based on hdf5.

**Comment by Nic-Ma** [comment]
Hi @dyollb ,

As @wyli said in https://github.com/Project-MONAI/MONAI/pull/2647#issuecomment-886648113, I think we need more discussion about this topic.

Thanks.

**Comment by wyli** [comment]
thanks, I'm closing this in favour of #3674.

**Pull request closed without merging**
