### PR TITLE
Enhance csrc/resample

### PR DESCRIPTION
**Pull request by wyli**
### Description
adds tests for csrc/resample, enhancements according to https://github.com/balbasty/nitorch
part of #789 

### Status
**ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
this PR is ready for review @rijobro @ericspod @Nic-Ma   this is another step towards https://github.com/Project-MONAI/MONAI/issues/789, it mainly includes the latest non-breaking refactoring from https://github.com/balbasty/nitorch/tree/7aba34b7499fe7efe1cfdf12311dfe8d1cf69355/nitorch/_C and added:

- enhanced tests for [the padding/interpolation options](https://github.com/Project-MONAI/MONAI/pull/1471/files?file-filters%5B%5D=.py&file-filters%5B%5D=.sh#diff-c3041fc23e84b744419561dbfb30a65fcc59afd6a2ca604de504829126d90a01) 
- detailed tests in the forward and backprop [for the 1D grid_pull cases](https://github.com/Project-MONAI/MONAI/pull/1471/files?file-filters%5B%5D=.py&file-filters%5B%5D=.sh#diff-a5637ff517e1abba61ca58070db8b75b4292205e52d7672352be4ad550a77761)

the python-based new unit tests should cover most of the cpp/cuda code changes, I'll add more tests in some follow-up PRs as this one is getting large.

**Comment by wyli** [comment]
Hi @brudfors @balbasty could you help review this if you have time? thanks in advance!

**Review by rijobro — APPROVED** [review]
A little over my head, but the tests look good!

**Pull request merged**
