### PR TITLE
removes duplicated docstring rendering

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>
Screenshot 2022-01-12 at 23 00 46

### Description
for example https://docs.monai.io/en/stable/data.html#iterabledataset
`__init__` arguments are rendered twice as the class docstring and `__init__` method docstring, this PR removes the duplicated ones

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
as our doc page defaults to the milestone releases, would be great to include this PR in 0.8.1 https://github.com/Project-MONAI/MONAI/issues/3479

**Review by Nic-Ma — APPROVED** [review]
Good finding! Thanks for the quick fix, looks good to me.
Is there any preview of the expected web page after building with this PR?

Thanks.

**Comment by wyli** [comment]
yes the preview of this PR is deployed here https://monai-dev.readthedocs.io/en/fixes-sphinx/data.html

**Pull request merged**
