### PR TITLE
Set autoscale false for auto3dseg test

### PR DESCRIPTION
**Pull request by heyufan1995**
Fixes # .
Disabled autoscale for auto3dseg template testing. 
### Description

A few sentences describing the changes proposed in this pull request.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by wyli — APPROVED** [review]
@mingxin-zheng please let me know if any concerns

**Comment by mingxin-zheng** [comment]
The changes are only in HPO, which I think it should be fine.
My question to @heyufan1995 would be whether it is necessary to keep the auto scaling off in all unit tests, as we strived to use the minimal resources in the unit test and avoid overloading the testing systems.

**Pull request merged**
