### PR TITLE
Revert version requirement for mlflow

### PR DESCRIPTION
**Pull request by KumoLiu**
Revert https://github.com/Project-MONAI/MONAI/pull/7659

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by mingxin-zheng** [comment]
Thanks @KumoLiu for PR. Just to double-check, is the previous mlflow issue resolved in all versions >=1.28.0, or just the latest versions?

**Comment by KumoLiu** [comment]
> Thanks @KumoLiu for PR. Just to double-check, is the previous mlflow issue resolved in all versions >=1.28.0, or just the latest versions?

Hi @mingxin-zheng, the previous issue is resolved by moving the env arg, seems not directly related to mlflow. But we have security issue with mlflow <=2.12.1.

**Review by mingxin-zheng — APPROVED** [review]
Thanks @KumoLiu . I believe you should have noted the security issue somewhere else. Since it's not related to this PR, we can take care of that later.

**Pull request merged**
