### PR TITLE
Skip "test_gaussian_filter" as a workaround for blossom killed

### PR DESCRIPTION
**Pull request by KumoLiu**
workaround for #7445

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by ericspod** [comment]
Do we know if one test or another is causing the issue? In test_gaussian_filter.py there's tests doing backprop and others testing other things, can we keep any of these instead of ignoring the file?

**Comment by KumoLiu** [comment]
> Do we know if one test or another is causing the issue? In test_gaussian_filter.py there's tests doing backprop and others testing other things, can we keep any of these instead of ignoring the file?

Hi @ericspod, I still haven't found the root problem, I have discovered that this unit test is the cause and only occurs on v100. Additionally, it comes after PyTorch2.2, so I added a check only skip the test after 2.2, what do you think?

**Comment by ericspod** [comment]
> Hi @ericspod, I still haven't found the root problem, I have discovered that this unit test is the cause and only occurs on v100. Additionally, it comes after PyTorch2.2, so I added a check only skip the test after 2.2, what do you think?

Thanks @KumoLiu this looks good now if it works. Please add a comment with the skip decorators so that we are aware of why we're skipping if we want to come back to it in the future. We know there's a number of other inexplicable issues with tests combined with specific environments that we should circle back later.

**Review by ericspod — APPROVED** [review]

**Pull request merged**
