### PR TITLE
Feature/2231 transforms

### PR DESCRIPTION
**Pull request by rijobro**
Fixes https://github.com/Project-MONAI/MONAI/issues/2231.

### Description
I've sorted transforms into `TorchTransforms` and/or `NumpyTransforms`. 

- `TorchTransform`: convert input to torch, do transform, convert back to original
- `NumpyTransform`: convert input to numpy, do transform, convert back to original
- Both `TorchTransform` and `NumpyTransform`: no need for conversion (e.g., `img[None]`)

I've also added some `enums` to try and unify the input types:

```python
class DataObjects:
    """Common classes used for arrays/tensors and then their usage in dict/mappings."""

    Images = Union[torch.Tensor, np.ndarray]
    Dict = Dict[Hashable, Any]
    Mapping = Mapping[Hashable, Any]
```

We can keep a track of progress with:

```python
from monai import transforms
from inspect import getmembers, isclass
for n,obj in getmembers(transforms):
    if isclass(obj) and issubclass(obj,transforms.Transform) and not issubclass(obj,transforms.MapTransform):
        print(n)
```
And we can add in is not `TorchTransform` and is not `NumpyTransform`, etc. to see which are yet to be considered.

### Status
**Ready/Work in progress/Hold**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by rijobro** [comment]
@wyli @Nic-Ma @ericspod I think [this](https://github.com/Project-MONAI/MONAI/pull/2278/commits/1b578a2ddf783a280cb95ffbeec0025b572fb87d) commit might be interesting.

I made `RandRicianNoise` available for both numpy and torch inputs. I realised we couldn't fix the seed for the torch random generators, so I followed [this](https://stackoverflow.com/a/61225003/12411867) StackOverflow post. 

Now we can use `self.R` and `self.R_torch` for random generation with numpy and torch, respectively.

**Comment by wyli** [comment]
> @wyli @Nic-Ma @ericspod I think [this](https://github.com/Project-MONAI/MONAI/pull/2278/commits/1b578a2ddf783a280cb95ffbeec0025b572fb87d) commit might be interesting.
> 
> I made `RandRicianNoise` available for both numpy and torch inputs. I realised we couldn't fix the seed for the torch random generators, so I followed [this](https://stackoverflow.com/a/61225003/12411867) StackOverflow post.
> 
> Now we can use `self.R` and `self.R_torch` for random generation with numpy and torch, respectively.

I forgot to get back to this... I think there's also torch.cuda.manual_seed, this will create some inconsistencies for numpy/torch cpu/cuda setups, but I couldn't think of a better approach here

**Comment by rijobro** [comment]
Current state of proposed transforms as I start merging them into MONAI:

```
TorchOrNumpy:  Activations
TorchOrNumpy:  AddChannel
TorchOrNumpy:  AddCoordinateChannels
Torch:         AddExtremePointsChannel
TorchOrNumpy:  AdjustContrast
Torch:         Affine
Torch:         AffineGrid
TorchOrNumpy:  AsChannelFirst
TorchOrNumpy:  AsChannelLast
TorchOrNumpy:  AsDiscrete
Uncategorised: BatchInverseTransform
TorchOrNumpy:  BorderPad
TorchOrNumpy:  BoundingRect
TorchOrNumpy:  CastToType
TorchOrNumpy:  CenterScaleCrop
TorchOrNumpy:  CenterSpatialCrop
TorchOrNumpy:  ClassesToIndices
TorchOrNumpy:  ConvertToMultiChannelBasedOnBratsClasses
TorchOrNumpy:  CropForeground
TorchOrNumpy:  DataStats
Torch:         DetectEnvelope
TorchOrNumpy:  DivisiblePad
Torch:         EnsureChannelFirst
Uncategorised: EnsureType
TorchOrNumpy:  FgBgToIndices
Torch:         Flip
Torch:         GaussianSharpen
Torch:         GaussianSmooth
TorchOrNumpy:  GibbsNoise
TorchOrNumpy:  Identity
TorchOrNumpy:  KSpaceSpikeNoise
Torch:         KeepLargestConnectedComponent
Torch:         LabelToContour
TorchOrNumpy:  LabelToMask
TorchOrNumpy:  MaskIntensity
TorchOrNumpy:  MeanEnsemble
TorchOrNumpy:  NormalizeIntensity
Numpy:         Orientation
TorchOrNumpy:  Pad
TorchOrNumpy:  PadListDataCollate
Torch:         ProbNMS
Torch:         Rand2DElastic
Torch:         Rand3DElastic
TorchOrNumpy:  RandAdjustContrast
Torch:         RandAffine
Torch:         RandAffineGrid
Torch:         RandAxisFlip
TorchOrNumpy:  RandBiasField
TorchOrNumpy:  RandCoarseDropout
TorchOrNumpy:  RandCropByLabelClasses
TorchOrNumpy:  RandCropByPosNegLabel
TorchOrNumpy:  RandDeformGrid
Torch:         RandFlip
TorchOrNumpy:  RandGaussianNoise
Torch:         RandGaussianSharpen
Torch:         RandGaussianSmooth
TorchOrNumpy:  RandGibbsNoise
Numpy:         RandHistogramShift
TorchOrNumpy:  RandKSpaceSpikeNoise
Uncategorised: RandLambda
TorchOrNumpy:  RandRicianNoise
Torch:         RandRotate
TorchOrNumpy:  RandRotate90
TorchOrNumpy:  RandScaleCrop
TorchOrNumpy:  RandScaleIntensity
TorchOrNumpy:  RandShiftIntensity
TorchOrNumpy:  RandSpatialCrop
TorchOrNumpy:  RandSpatialCropSamples
TorchOrNumpy:  RandStdShiftIntensity
TorchOrNumpy:  RandWeightedCrop
Torch:         RandZoom
TorchOrNumpy:  RemoveRepeatedChannel
TorchOrNumpy:  RepeatChannel
Torch:         Resample
Torch:         Resize
TorchOrNumpy:  ResizeWithPadOrCrop
Torch:         Rotate
TorchOrNumpy:  Rotate90
TorchOrNumpy:  SaveImage
Torch:         SavitzkyGolaySmooth
TorchOrNumpy:  ScaleIntensity
TorchOrNumpy:  ScaleIntensityRange
TorchOrNumpy:  ScaleIntensityRangePercentiles
TorchOrNumpy:  ShiftIntensity
TorchOrNumpy:  SimulateDelay
Torch:         Spacing
TorchOrNumpy:  SpatialCrop
TorchOrNumpy:  SpatialPad
TorchOrNumpy:  SplitChannel
TorchOrNumpy:  SqueezeDim
TorchOrNumpy:  StdShiftIntensity
TorchOrNumpy:  ThresholdIntensity
TorchOrNumpy:  ToNumpy
Torch:         ToTensor
TorchOrNumpy:  Transpose
TorchOrNumpy:  VoteEnsemble
Torch:         Zoom
```

**Comment by wyli** [comment]
feature merged into `dev`

**Pull request closed without merging**
