### PR TITLE
`EnsureChannelFirst`: avoid re-creation of `AddChannel`

### PR DESCRIPTION
**Pull request by rijobro**
### Description
Each time `EnsureChannelFirst.__call__` is called, `AddChannel` or `AsChannelFirst` is created and then immediately destroyed. Better to create both during the `__init__` and then reuse.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.

### CODE REVIEW

**Review by wyli — APPROVED** [review]
Thanks, it looks good to me.

**Comment by rijobro** [comment]
Sorry, realise that since the channel dimension is determined during `__call__`, the AsChannelFirst object can't be created during the `__init__`. The `AddChannel` can, though.

**Pull request merged**
