### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by kartikshastrakar**
correct relate update

Fixes # .

### Description

A few sentences describing the changes proposed in this pull request.

### Types of changes

- [ ] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by ericspod** [comment]
Hi @kartikshastrakar thanks for the contribution but could you explain the rationale behind these changes? I don't think any of them should be accepted as they are, so if there's something you needed to accomplish here we can review and see what to do.

**Comment by kartikshastrakar** [comment]
Hi ,

Actuall i was trying to change the dockerfile in it and had updated it

**Comment by ericspod** [comment]
> also only one check is skipped else all are fine i have attached a snap because while using the monai ai i face some difficulties so i have changed

The other checks will be fine because the code base wasn't changed, only the Dockerfile. Was there something specific with the issues you were having? As I said I don't think these changes should be accepted as they are, we need to see what wasn't working for you and then if we can modify the Dockerfile without breaking it for others. For example, we shouldn't remove the license header, nor remove the aarch64 install in the first RUN section. If you wanted a modified Dockerfile for your own purposes only, I would suggest to keep it in your own fork and not to propose the PR here.

**Comment by kartikshastrakar** [comment]
Ok, thanks for the clarification.

**Comment by kartikshastrakar** [comment]
thank you for clarification

**Pull request closed without merging**
