### PR TITLE
Minor enhancement for several places

### PR DESCRIPTION
**Pull request by Nic-Ma**
### Description
This PR added several minor enhancements:
1. Added missing doc for `monai.bundle init_bundle`.
2. Corrected description for spatial shape example in the bundle doc.
3. Updated wrong typehints in all the `pad` transforms.
4. @rijobro already updated the `Pad` transform arg `np_kwargs` to `kwargs` for both numpy and torch APIs, this PR corrected 2 missing transforms for this change.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by ericspod** [comment]
Should we also change the URL for the schema file to https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json?

**Comment by Nic-Ma** [comment]
> Should we also change the URL for the schema file to https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json?

Hi @ericspod ,

May I know where you think we should update?
I think the test data is already updated:
https://github.com/Project-MONAI/MONAI/blob/dev/tests/testing_data/metadata.json#L2

Thanks.

**Comment by ericspod** [comment]
Sorry I meant the URL that's in `md=b_specification.rst` should be the one I gave rather than the temporary one that's given currently.

**Pull request merged**
