### PR TITLE
Update cucim dependency for cucim transforms

### PR DESCRIPTION
**Pull request by drbeh**
### Description
This PR updates the cucim dependency to support cuCIM Transforms.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Review by wyli — APPROVED** [review]
thanks!

**Comment by drbeh** [comment]
@wyli I've been looking into this and it does not happen on my local with the same version of cucim. I re-ran the test to see if it persists. I'll further look into it once the tests are done.

**Comment by drbeh** [comment]
I can confirm that there is no API changes. There is not issue with our tests on actual TIF files. The issue is when we are using simple uncompressed TIF files that are crated using PIL. I'm contacting cucim development team to find a way out for our cucim tests.

**Comment by drbeh** [comment]
@wyli as you mentioned there are two issues here:
1. AttributeError: module 'cucim' has no attribute 'CuImage' https://github.com/Project-MONAI/MONAI/pull/2987/checks?check_run_id=3667531299
2. RuntimeError: This format (compression: 1, sample_per_pixel: 1, planar_config: 1, photometric: 1) is not supported yet!. https://github.com/Project-MONAI/MONAI/pull/2987/checks?check_run_id=3667530814#step:7:15641

The first one should be resolved by the new commits here. The second one is related to #2999.

**Comment by wyli** [comment]
closing this in favor of https://github.com/Project-MONAI/MONAI/pull/3006

**Pull request closed without merging**
