### PR TITLE
629 Update progress_bar and replace tqdm in notebook

### LINKED ISSUE #629: progress bar with tqdm
**Is your feature request related to a problem? Please describe.**
instead of implementing the progress bar related functionality, [tqdm](https://github.com/tqdm/tqdm) looks like a good library to use directly. this ticket requests replacing the existing code to use tqdm implementations

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #629 .

### Description
Update progress_bar and replace tqdm in notebook.

### Status
**Ready**

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [x] Docstrings/Documentation updated

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Could you please help me reproduce the CI error on your MacBook? I only have Ubuntu env locally, didn't find the root cause.
Thanks in advance.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> Could you please help me reproduce the CI error on your MacBook? I only have Ubuntu env locally, didn't find the root cause.
> Thanks in advance.

I think it's related to updating tqdm object in a multithread/multiprocess context.
a simple fix is to use our previous progress bar in this case...

btw after testing this properly, we should make tqdm optional:
```python
tqdm, has_tqdm = optional_import("tqdm",  "4.46.1")
if has_tqdm:
    pbar = tqdm()
else:
    # don't show progress bar or use the previous progress bar
````

**Comment by Nic-Ma** [comment]
Hi @wyli ,

1. Even I removed tqdm in the multi-threading program, it still caused error in CI. 
2. After deeper investigation, I think the root cause is related to python 3.8 instead of multi-threading:
https://github.com/GoogleCloudPlatform/gsutil/issues/961
3. I also checked the tqdm source, it doesn't support python 3.8: https://github.com/tqdm/tqdm
4. And I feel progress_bar is necessary for CacheDataset and it's not easy to make it optional.

Based on all above reasons, can we just restore back to use our progress_bar and change the GAN example to use our progress_bar? When tqdm is more suitable for us, I can try to change to use it.

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> 1. Even I removed tqdm in the multi-threading program, it still caused error in CI.
> 2. After deeper investigation, I think the root cause is related to python 3.8 instead of multi-threading:
>    [GoogleCloudPlatform/gsutil#961](https://github.com/GoogleCloudPlatform/gsutil/issues/961)
> 3. I also checked the tqdm source, it doesn't support python 3.8: https://github.com/tqdm/tqdm
> 4. And I feel progress_bar is necessary for CacheDataset and it's not easy to make it optional.
> 
> Based on all above reasons, can we just restore back to use our progress_bar and change the GAN example to use our progress_bar? When tqdm is more suitable for us, I can try to change to use it.
> 
> Thanks.

thanks for looking into this, I agree that we postpone this feature.

to fix the CI error I think `self.pbar = tqdm(total=self.cache_num)`  should be called when the num workers is 0:
```python
if num_workers == 0:
    self.pbar = tqdm(total=self.cache_num)
```
because `self` is shared among the workers

**Comment by Nic-Ma** [comment]
Mark: the tqdm solution for download module:
```py
    class TqdmUpTo(tqdm):
        """
        Provides `update_to(n)` which uses `tqdm.update(delta_n)`.
        Inspired by the example in https://github.com/tqdm/tqdm
        """

        def update_to(self, b=1, bsize=1, tsize=None):
            """
            b (int): number of blocks transferred so far, default: 1.
            bsize (int): size of each block (in tqdm units), default: 1.
            tsize (int) total size (in tqdm units). if None, remains unchanged.
            """
            if tsize is not None:
                self.total = tsize
            self.update(b * bsize - self.n)  # will also set self.n = b * bsize

    try:
        with TqdmUpTo(unit="B", unit_scale=True, unit_divisor=1024, miniters=1, desc=filepath.split("/")[-1]) as t:
            urlretrieve(url, filepath, reporthook=t.update_to)
        print(f"\ndownloaded file: {filepath}.")
    except (URLError, IOError) as e:
        raise e
```

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your review, I updated the PR according to the above plan.
Could you please help review it again?

Thanks.

**Pull request merged**
