### PR TITLE
skip RandAffine if possible

### PR DESCRIPTION
**Pull request by rijobro**
Fixes https://github.com/Project-MONAI/MONAI/issues/2124.

### Description
Skip RandAffine if possible.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by rijobro** [comment]
When debugging, I put a print statement to verify that the first unit test skips the resampling, as expected.

**Comment by wyli** [comment]
thanks, need something like
```py
        if not self.rand_affine.do_transform and self.rand_affine.spatial_size is None:
            for idx, key in enumerate(self.keys):
                if self.rand_affine.resampler.as_tensor_output:
                    d[key] = torch.tensor(key)
                elif torch.is_tensor(d[key]):                    
                    d[key] = d[key].cpu().numpy()
            return d
```
for `RandAffined`

need to double-check the output data type, make sure that the PR doesn't change the dtype for integer `image`

**Comment by rijobro** [comment]
also need to think about the inverse for `RandAffined`...

**Comment by rijobro** [comment]
@wyli why would the dtype change if the image isn't modified? Because of the torch/numpy conversion?

**Comment by wyli** [comment]
the root cause is that the current resampling requires floats...https://github.com/Project-MONAI/MONAI/blob/41e62e544685e87a14b88d7fdca229dc4191836d/monai/transforms/spatial/array.py#L1240-L1242

if we bypass the resample step, I feel the datatype might be different, but I haven't checked all the details...

**Review by wyli — APPROVED** [review]
thanks!

**Comment by wyli** [comment]
the dev branch had its 1024th merged pull request 🎉

**Comment by rijobro** [comment]
that was quick, it's only a few weeks old! 😅

**Pull request merged**
