### PR TITLE
730 Update ignite related typehints

### LINKED ISSUE #730: Cannot resolve forward reference in type annotations
**Describe the bug**
> WARNING: Cannot resolve forward reference in type annotations of "{}": name 'ignite' is not defined

Even with the fix of [``set_type_checking_flag = True``](https://github.com/Project-MONAI/MONAI/blob/master/docs/source/conf.py#L98) there are still unresolved forward references.

**To Reproduce**

1. Go to ``docs/``
2. With [``set_type_checking_flag = False``](https://github.com/Project-MONAI/MONAI/blob/master/docs/source/conf.py#L98)
3. Run ``make html``

```bash
WARNING: Cannot resolve forward reference in type annotations of "monai.engines.multi_gpu_supervised_trainer.create_multigpu_supervised_evaluator": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.engines.workflow.Workflow": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.engines.Trainer": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.engines.SupervisedTrainer": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.engines.Evaluator": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.engines.SupervisedEvaluator": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.handlers.CheckpointSaver.completed": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.handlers.CheckpointSaver.exception_raised": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.handlers.CheckpointSaver.interval_completed": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.handlers.CheckpointSaver.metrics_completed": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.handlers.StatsHandler.attach": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.handlers.StatsHandler.epoch_completed": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.handlers.StatsHandler.exception_raised": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.handlers.StatsHandler.iteration_completed": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.handlers.TensorBoardStatsHandler.attach": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.handlers.TensorBoardStatsHandler.epoch_completed": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.handlers.TensorBoardStatsHandler.iteration_completed": name 'ignite' is not defined
```

2. With [``set_type_checking_flag = True``](https://github.com/Project-MONAI/MONAI/blob/master/docs/source/conf.py#L98)
3. Run ``make html``

```bash
WARNING: Cannot resolve forward reference in type annotations of "monai.engines.multi_gpu_supervised_trainer.create_multigpu_supervised_evaluator": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.engines.workflow.Workflow": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.engines.Trainer": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.engines.SupervisedTrainer": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.engines.Evaluator": name 'ignite' is not defined
WARNING: Cannot resolve forward reference in type annotations of "monai.engines.SupervisedEvaluator": name 'ignite' is not defined
```

**Screenshots**

Untitled

**Environment**
- OS: Ubuntu 18.04
- Python version: 3.7.5
- MONAI version: 8516865

```bash
MONAI version: 0.2.0+28.g8516865
Python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
Numpy version: 1.19.0
Pytorch version: 1.5.1

Optional dependencies:
Pytorch Ignite version: 0.3.0
Nibabel version: 3.1.1
scikit-image version: 0.17.2
Pillow version: 7.2.0
Tensorboard version: 2.2.2
```

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #730 .

### Description
I think `ignite` is necessary for these modules, so I changed to use the ignite classes for typehints.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [ ] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Test log1:
```
root@apt-sh-ai:/workspace/data/medical/MONAI/docs# make clean
rm -rf build/
root@apt-sh-ai:/workspace/data/medical/MONAI/docs# make html set_type_checking_flag=True
Running Sphinx v2.3.1
['/workspace/data/medical/MONAI', '/workspace/data/medical/MONAI/docs', '/opt/conda/bin', '/workspace/data/medical/MONAI/docs/PYTHONPATH', '/workspace/data/medical/MONAI', '/opt/conda/lib/python36.zip', '/opt/conda/lib/python3.6', '/opt/conda/lib/python3.6/lib-dynload', '/opt/conda/lib/python3.6/site-packages']
making output directory... done
output_path /workspace/data/medical/MONAI/docs/source/apidocs
module_path /workspace/data/medical/MONAI/monai
File /workspace/data/medical/MONAI/docs/source/apidocs/monai.rst already exists, skipping.
File /workspace/data/medical/MONAI/docs/source/apidocs/modules.rst already exists, skipping.
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 16 source files that are out of date
updating environment: [new config] 16 added, 0 changed, 0 removed
/opt/conda/lib/python3.6/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document       
  warn("Container node skipped: type={0}".format(mdnode.t))
/opt/conda/lib/python3.6/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document       
  warn("Container node skipped: type={0}".format(mdnode.t))
reading sources... [100%] visualize                                                                                        
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] visualize                                                                                         
generating indices...  genindex py-modindexdone
highlighting module code... [100%] monai.visualize.img2tensorboard                                                         
writing additional pages...  search/opt/conda/lib/python3.6/site-packages/sphinx_rtd_theme/search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {{ super() }}
done
copying images... [100%] ../images/unet-pipe.png                                                                           
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in build/html.
```

Test log2:
```
root@apt-sh-ai:/workspace/data/medical/MONAI/docs# make clean
rm -rf build/
root@apt-sh-ai:/workspace/data/medical/MONAI/docs# make html set_type_checking_flag=False
Running Sphinx v2.3.1
['/workspace/data/medical/MONAI', '/workspace/data/medical/MONAI/docs', '/opt/conda/bin', '/workspace/data/medical/MONAI/docs/PYTHONPATH', '/workspace/data/medical/MONAI', '/opt/conda/lib/python36.zip', '/opt/conda/lib/python3.6', '/opt/conda/lib/python3.6/lib-dynload', '/opt/conda/lib/python3.6/site-packages']
making output directory... done
output_path /workspace/data/medical/MONAI/docs/source/apidocs
module_path /workspace/data/medical/MONAI/monai
File /workspace/data/medical/MONAI/docs/source/apidocs/monai.rst already exists, skipping.
File /workspace/data/medical/MONAI/docs/source/apidocs/modules.rst already exists, skipping.
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 16 source files that are out of date
updating environment: [new config] 16 added, 0 changed, 0 removed
/opt/conda/lib/python3.6/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document       
  warn("Container node skipped: type={0}".format(mdnode.t))
/opt/conda/lib/python3.6/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document       
  warn("Container node skipped: type={0}".format(mdnode.t))
reading sources... [100%] visualize                                                                                        
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] visualize                                                                                         
generating indices...  genindex py-modindexdone
highlighting module code... [100%] monai.visualize.img2tensorboard                                                         
writing additional pages...  search/opt/conda/lib/python3.6/site-packages/sphinx_rtd_theme/search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {{ super() }}
done
copying images... [100%] ../images/unet-pipe.png                                                                           
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in build/html.
```

**Comment by wyli** [comment]
thanks, will this also resolve the cron test issue? https://github.com/Project-MONAI/MONAI/runs/856415942?check_suite_focus=true#step:3:88

**Comment by Nic-Ma** [comment]
> thanks, will this also resolve the cron test issue? https://github.com/Project-MONAI/MONAI/runs/856415942?check_suite_focus=true#step:3:88

Yes, I think it should also fix that issue, because we used `ignite.metrics` now.
Thanks.

**Pull request merged**
