### PR TITLE
Workflow Fix

### PR DESCRIPTION
**Pull request by ericspod**
### Description
Very minor fix to how workflows decide what the best metric result is such that the first epoch always chooses whatever its metric was. `BaseWorkflow` was also removed since it wasn't used anywhere, this can be put back if somewhere else needs it.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by wyli — APPROVED** [review]

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

The `BaseWorkflow` is useful in the NVIDIA Clara Train project to ask developers to follow the signature if they want to develop their own workflow.

Thanks.

**Comment by ericspod** [comment]
Could that be put into the clara train package then? If it's not used in MONAI I would say it shouldn't be here, but I can put it back in another PR.

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

I think we are fine now, Clara Train supposes to work with fixed MONAI version.

Thanks.

**Pull request merged**
