### PR TITLE
3063 Fix the complex Tensor issue in type conversion

### LINKED ISSUE #3063: error from `convert_to_tensor`
**Describe the bug**
from the cron logs:
```
======================================================================
ERROR: test_dict_matches_4 (tests.test_k_space_spike_noised.TestKSpaceSpikeNoised)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/tests/test_k_space_spike_noised.py", line 97, in test_dict_matches
    out = t(deepcopy(data))
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/intensity/dictionary.py", line 1324, in __call__
    d[key] = self.transform(d[key])
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/intensity/array.py", line 1499, in __call__
    k = self.shift_fourier(img, n_dims)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/utils/deprecated.py", line 204, in _wrapper
    return func(*args, **kwargs)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/utils.py", line 1280, in shift_fourier
    k, *_ = convert_to_dst_type(k, x)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/utils/type_conversion.py", line 284, in convert_to_dst_type
    return convert_data_type(data=src, output_type=output_type, device=device, dtype=dtype)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/utils/type_conversion.py", line 251, in convert_data_type
    data = convert_to_tensor(data, dtype=dtype_, device=device)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/utils/type_conversion.py", line 121, in convert_to_tensor
    return torch.as_tensor(data, dtype=dtype, device=device)  # type: ignore
TypeError: can't convert np.ndarray of type numpy.complex128. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.
```

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #3063 .

### Description
This PR fixed the issue that PyTorch 1.5.1 can't support complex Tensor.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Tested this PR in PyTorch 1.5.1:
```
root@apt-sh-ai:/workspace/data/medical/MONAI# python
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.5.1
>>> exit()
root@apt-sh-ai:/workspace/data/medical/MONAI# python tests/test_k_space_spike_noised.py
..................
----------------------------------------------------------------------
Ran 18 tests in 3.938s

OK
```

**Review by wyli — APPROVED** [review]
Thanks, it looks good to me.

**Pull request merged**
