### PR TITLE
Make str subset parameters consistent

### PR DESCRIPTION
**Pull request by benjamin-gorman**
Precursor to #484.

### Description

- make parameter names match underlying function
- make parameter docstrings uniform
- add set notation to communicate str subset
- add 'Defaults to' for default values
- add 'See also' for underlying function

**Note**

- the docstring format could be changed (style choice)

### Status

**Ready**

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or new feature that would cause existing functionality to change)
- [x] Docstrings/Documentation updated

### CODE REVIEW

**Comment by wyli** [comment]
this looks good, need to update the integration tests (`./runtests.sh --coverage`) and  monai/examples. any comments @Nic-Ma?

**Comment by Nic-Ma** [comment]
> this looks good, need to update the integration tests (`./runtests.sh --coverage`) and monai/examples. any comments @Nic-Ma?

Yes, I agree. Need to update,and confirm all the examples and notebooks, And please also make sure it doesn't affect research folder things.
Thanks.

**Comment by benjamin-gorman** [comment]
> > this looks good, need to update the integration tests (`./runtests.sh --coverage`) and monai/examples. any comments @Nic-Ma?
> 
> Yes, I agree. Need to update,and confirm all the examples and notebooks, And please also make sure it doesn't affect research folder things.
> Thanks.

Did not find any problems in examples (minus notebooks) or research.

**Comment by benjamin-gorman** [comment]
No conflicts

**Pull request merged**
