### PR TITLE
3914 optional lps to ras

### LINKED ISSUE #3914: ITKReader silently changes the affine matrix to RAS without informing the users
**Describe the bug**
The function _get_affine(self, img) of ITKReader() in monai/data/image_reader.py
silently flips the affine matrix to match with the format of nibabel.
See line 307: flip_diag = [[-1, 1], [-1, -1, 1], [-1, -1, 1, 1]][sr - 1]  # itk to nibabel affine

However, the user is not aware of this operation unless they check the source code of ITKReader().
If they thought the affine was the raw affine, it would cause mistakes.

**Additional context**
Three possible solutions:
1.  let the operation of flipping affine matrix be a separate transform
2. set a bool input for ITKReader() to indicate whether to flip the affine.
3. add a key in image_mata_dict to indicate that the image affine has been flipped.

There might be other solutions, but users need to know this operation has been done.

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Fixes #3914

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by Can-Zhao — APPROVED** [review]

**Review by Nic-Ma — APPROVED** [review]
Looks good to me.
Do we also need to change image writers for this problem?

Thanks.

**Pull request merged**
