### PR TITLE
1133 Add partition dataset API

### LINKED ISSUE #1133: Add partition dataset API
**Is your feature request related to a problem? Please describe.**
In order to partition dataset for training, evaluation, cross validation, even distributed training, we should develop a general `partition_dataset` API.
Refer to what we have in the tutorial:
https://github.com/Project-MONAI/tutorials/blob/master/acceleration/distributed_training/unet_training_smartcache.py#L80

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #1133 .

### Description
This PR added partition dataset API for training, evaluation, cross-validation, and distributed training.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by ericspod** [comment]
I had played around earlier with a more generalized idea of partitioning data. We often want to partition by irregular ratios and not just into even sets, not just to divide data amongst processes but also to divide a dataset into train, eval, and test sets which aren't the same size, and do ablation partitioning. I had this routine to yield a list of indices to divide a sequence by ratios:

```py
def partition_seq(length,*ratios):
    """
    Yields the slices for partitioning a sequence of length `length` into the given integer ratios.
    """
    rsum=sum(ratios)
    indices=[int((r/rsum)*length+0.5) for r in ratios]
    start_idx=0
    
    for idx in indices:
        next_idx=min(start_idx+idx,length)
        yield slice(start_idx,next_idx)
        start_idx=next_idx
```

So to divide a sequence of length `N` into train (70%), evaluation (20%), and test (10%) sets we would do `train_inds, eval_inds, test_inds = partition_seq(N, 7, 2, 1)`. To divide into M equal-sized partitions (or near to): `partition_seq(N, *[1]*M)`. 

Now if our data has class labels and we want to divide the data such that each partition has the same ratio of classes we would use this:

```py
def partition_classes(classes,*ratios):
    """
    Given a sequence of integer class labels in `classes` from 0 to N for N classes, divide each class into the given
    ratios. The result is a list of integer lists, with one entry for each ratio in `ratios` containing indices into
    `classes` for that ratio's part of each class. This is used to partition a set of values by class such that all
    the returned lists index members of each class in the same ratio. Relative ordering of indices is kept in the
    partitioned indices.
    
    For example, if `classes` contained three distinct labels, `partition_classes(classes,3,1)` will return two index 
    lists, the first having the indices of the first 75% of each of the three labels, and the second the remaining 25%:
    
        >>> classes = [0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3]
        >>> partition_classes(classes, 3, 1)
            [[0, 1, 2, 3, 5, 6, 8, 9, 10, 11, 12, 13, 16, 17, 18], [4, 7, 14, 15, 19]]
    """
    class_indices=defaultdict(list) 
    
    # add the index of each value in `classes` to the entry in `class_indices` for the class at that index
    for i,c in enumerate(classes):
        class_indices[c].append(i)
        
    partitions=[list() for _ in ratios]
    
    # loop through the lists in `class_indices` in class order
    for _, indices in sorted(class_indices.items()):
        # partition the list of indices for this class
        slices=partition_seq(len(indices),*ratios)
        
        # for each partition of this class index list, append the indices to the output list for each ratio
        for s,part in zip(slices,partitions):
            part+=indices[s]
            
    return partitions
```

With these two we can divide a sequence of data into partitions but also select which partitions we want to retain:

```py
def select_array_partitions(arr, ratios, selected_ratios, classes=None):
    """
    Given an array of values `arr`, divide the array into partitions defined by the `ratios` sequence of ratio integers
    and select the partitions indexed by `selected_ratios`. Returns the concatenated selected partitions of `arr`. If
    `classes` is not None, this is an array of class labels for each index in the 0th dimension of `arr`, and will be
    used to partition each class separately using `partition_classes`. 
    """
    
    if classes is None:
        partitions=list(partition_seq(len(arr),*ratios))
    else:
        if len(classes)!=len(arr):
            raise ValueError("0th dimension of `classes` must match that of `arr`")
            
        partitions=partition_classes(classes,*ratios)
        
    arr=np.atleast_1d(arr)
    selections=[arr[partitions[idx]] for idx in selected_ratios]
        
    return np.concatenate(selections)
```

This is useful for dividing data into partitions for doing ablation where a different partition is dropped for each run. With this non-contiguous partitions can be selected, so if a study divides the data into 5 partitions and drops one partition the call would be `select_array_partitions(arr, [1]*5,[1,2,3,4])` to drop the first partition, `select_array_partitions(arr, [1]*5,[0,2,3,4])` to drop the second, etc. 

I would suggest to use these routines in the `partition_dataset` routine provided to get the same results or modify its definition to allow for irregular sized partitions, partitioning by class, etc.

**Review by wyli — DISMISSED** [review]
need a flexible proportion option as commented https://github.com/Project-MONAI/MONAI/pull/1134#issuecomment-717968018

**Comment by Nic-Ma** [comment]
Thanks @ericspod and @wyli for your review.
I updated the PR according to your comments.
In order to keep the function not too complicated, I implemented `classes` based partition in a separate function.
Could you please help review it again?

Thanks.

**Comment by ericspod** [comment]
It looks good but we're missing an equivalent of `select_array_partitions` I think. This would be useful for doing partitioning for ablation/cross fold validation.

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Currently, the `partition_dataset` API in this PR is slightly different from your sample code, it already returns a set of data partitions, no need to do iteration again.
For example, if you want to select `train`, `val`, and `test` partitions:
```py
partitions = partition_dataset(data, ratios=[8, 1, 1], shuffle=True)
train, val, test = partition[0], partition[1], partition[2]
```
Or if you want to do cross-validation:
```py
partitions = partition_dataset(data, num_partitions=5, shuffle=True, even_divisible=False)
data0 = Dataset(partition[0], transforms, ...)
data1 = Dataset(partition[1], transforms, ...)
data2 = Dataset(partition[2], transforms, ...)
data3 = Dataset(partition[3], transforms, ...)
data4 = Dataset(partition[4], transforms, ...)
```
What do you think?

Thanks.

**Comment by ericspod** [comment]
The difference with `select_array_partitions` is that it allows you to select certain partitions and concatenate them together, so if you're doing a 5-fold cross validation you would break the dataset into 5 pieces and select a different set of 4 for each run. A script to do this by omitting 1 of the partitions might have the following:

```py
run_id=0  # ID of this run, script run multiple times with different value here
num_folds=5  # total number of parts
num_selected=4  # number of parts to select for this run
combinations = list(itertools.combinations(range(num_folds), num_selected))

fold = select_array_partitions(dataset, [1]*num_folds, combinations)
# `fold` is now the data to use for this run, this is further divided into train/valid/test partitions with partition_dataset
```

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

I see your point, let me try to add another function to concat data for cross-validation usage.
Thanks.

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

I added the `generate_cross_validation_fold` API and corresponding unit test.
Could you please help review it again?

Thanks.

**Review by ericspod — APPROVED** [review]

**Review by wyli — APPROVED** [review]
thanks @Nic-Ma, very useful features, could you please include them in the docs/

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your review.
Added these new APIs to docs and tested locally:
```
reading sources... [100%] visualize
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] visualize
generating indices...  genindex py-modindexdone
highlighting module code... [100%] monai.visualize.img2tensorboard
writing additional pages...  searchTo modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
done
copying images... [100%] ../images/distributed_training.png
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.
```

Thanks.

**Pull request merged**
