### PR TITLE
2499 adds 2d/3d support of patchembedding, ViT, and unetr model

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

part of #2499 

### Description
the current patchembedding/vit model only supports 3d input,
this PR extends them for 2d

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]
Thanks for the enhancement.
PR looks good to me.
@ahatamiz could you please help double confirm as you are expert on the UNETR, I may missed to check some computation theory.

Thanks in advance.

**Review by ahatamiz — APPROVED** [review]
Thanks @wyli for the great work. 

This PR looks good to me.

**Comment by ahatamiz** [comment]
> Thanks for the enhancement.
> PR looks good to me.
> @ahatamiz could you please help double confirm as you are expert on the UNETR, I may missed to check some computation theory.
> 
> Thanks in advance.

Thanks @Nic-Ma for your review.

**Pull request merged**
