### PR TITLE
Update Mish to default PyTorch 1.9 version

### PR DESCRIPTION
**Pull request by digantamisra98**
### Description
Update Mish to use the default in PyTorch 1.9

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @digantamisra98 ,

Thanks for your contribution here.
I think you can use some existing MONAI utilises to simplify:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/utils/module.py#L362

Thanks.

**Comment by digantamisra98** [comment]
@Nic-Ma Sorry checked back on this late, looks like @wyli has addressed the changes. Thanks a ton for the same.

**Review by Nic-Ma — APPROVED** [review]

**Pull request merged**
