### PR TITLE
3708 - refactor testing data fetching and migrate to release assets

### LINKED ISSUE #3708: migrate monai testing/demo data to GitHub release assets
**Is your feature request related to a problem? Please describe.**
The relevant data are currently located at https://drive.google.com/drive/u/0/folders/1ZOqwF44newvq-jOSgnbXRDWRD9DRq8hH and some other shared folders.

these could be migrated to, for example the release asset region of https://github.com/Project-MONAI/MONAI-extra-test-data (similar to https://github.com/Project-MONAI/MONAILabel/releases/tag/data)

this is to maintain the data in a centralised place.

follow-ups include
- [ ] the URLs should be updated accordingly for tutorials and monai tests
- [ ] the contribution guidelines should be updated for any new tutorial/test case contributors

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Fixes #3708

### Description
testing data are now also [available here](https://github.com/Project-MONAI/MONAI-extra-test-data/releases/tag/0.8.1)

this PR unified the config file to organise the testing data 

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]
Thanks for the quick update.
Looks good to me.

**Review by pxLi — APPROVED** [review]
LGTM. 

nit: data_config keys length and name check as the fixed format, but not a big deal :)

**Comment by wyli** [comment]
> LGTM.
> 
> nit: data_config keys length and name check as the fixed format, but not a big deal :)

Thanks @pxLi as you can see all the ci jobs will download and cache these testing data to the "testing_data" folder. Would be great to have a shared space for them at co runtime to avoid repeated downloading...

**Pull request merged**
