### PR TITLE
363-update gaussian 1d

### LINKED ISSUE #363: Discrete Gaussian kernel (gaussian_1d) should be adapted for discrete filtering
**Describe the bug**
The [current Gaussian kernel](https://github.com/Project-MONAI/MONAI/blob/5fcbf5ab16638670d890031825869874ed3d59ef/monai/networks/layers/convutils.py#L40-L59) simply samples the continuous Gaussian function:
```python
def gaussian_1d(sigma, truncated=4.0):
    """
    one dimensional gaussian kernel.

    Args:
        sigma: std of the kernel
        truncated: tail length

    Returns:
        1D numpy array
    """
    if sigma <= 0:
        raise ValueError("sigma must be positive")


    tail = int(sigma * truncated + 0.5)
    sigma2 = sigma * sigma
    x = np.arange(-tail, tail + 1)
    out = np.exp(-0.5 / sigma2 * x ** 2)
    out /= out.sum()
    return out
```

**Expected behavior**
Discrete Gaussian filtering should be compatible with scale-space theory and rely on modified Bessel function for its kernel weights. See e.g.:
https://en.wikipedia.org/wiki/Scale_space_implementation#The_discrete_Gaussian_kernel

**Additional context**
ITK implements such a behaviour in itk::GaussianOperator:
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkGaussianOperator.hxx

[Wikipedia](https://commons.wikimedia.org/wiki/File:Discrete_Gaussian_kernel.svg) also provides a basic python implementation (albeit relying on scipy and without rescaling):
```python
from scipy.special import iv
import numpy as np

def discrete_gaussian_kernel(n, t):
    T = np.exp(-t) * iv(n, t)
    return T
```

### PR DESCRIPTION
**Pull request by wyli**
related to #363, this PR implements a slightly better discrete gaussian kernel

### Status
**Ready**
### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
Hi @Nic-Ma this PR improves the discrete Gaussian kernel, and it affects a few preprocessing components. could you help verify the integration tests?

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I downloaded your code and ran the integration tests locally, it passed.

Thanks.

**Comment by Nic-Ma** [comment]
May I know why you change to use torch APIs to implement the gaussian 1d? To make it easier to be called with slidingwindow or other Tensor data computation?

Thanks.

**Comment by wyli** [comment]
> May I know why you change to use torch APIs to implement the gaussian 1d? To make it easier to be called with slidingwindow or other Tensor data computation?
> 
> Thanks.

yes, and this version is slightly more accurate especially when the kernel size is small

**Comment by wyli** [comment]
FYI @edgarriba this pr might be of interest for you as well... came across it here https://github.com/balbasty/nitorch/blob/216de8dc80634f566440768d46184482c60b4031/nitorch/kernels.py#L85

**Comment by edgarriba** [comment]
@wyli I will add it to the roadmap to support that as well. We are releasing 0.4.1 in two weeks, I believe it could be added there.  Besides, we are growing on 3d augmentations as well, probably we should sync at some point /cc @shijianjian

**Pull request merged**
