### PR TITLE
3368 Add `frame_dim` to specify the dim as frames of visualization

### LINKED ISSUE #3368: Add `frame_dim` to the matshow3d utility
**Is your feature request related to a problem? Please describe.**
Currently, for higher dimensional data (like `BCHWD`), `matshow3d` will expand to a list of frame images on the flattened `BCH` dim. Would be useful to add a `frame_dim` arg to support any dim.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #3368 .

### Description
This PR added `frame_dim` to specify the dim as frames of visualization.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
I also tested the feature in PR: https://github.com/Project-MONAI/tutorials/pull/448.

Thanks.

**Review by ericspod — APPROVED** [review]

**Pull request merged**
