### PR TITLE
Add distributed training example based on workflows

### PR DESCRIPTION
**Pull request by Nic-Ma**
### Description
This PR implemented distributed training example based on MONAI workflows and ignite.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
since we are on this topic, shall we modify the multigpu trainer to optionally support`DistributedDataParallel`?
https://github.com/Project-MONAI/MONAI/blob/8e5a53eec5fac30c8fba840eaeccc6f8fe8f9053/monai/engines/multi_gpu_supervised_trainer.py#L79-L80

**Comment by Nic-Ma** [comment]
> since we are on this topic, shall we modify the multigpu trainer to optionally support`DistributedDataParallel`?
> https://github.com/Project-MONAI/MONAI/blob/8e5a53eec5fac30c8fba840eaeccc6f8fe8f9053/monai/engines/multi_gpu_supervised_trainer.py#L79-L80

Hi @wyli ,

Thanks for your review, I added this logic in the latest commit.
Could you please help review it again?

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I updated the flake8 issues, ready for review now.
Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> I updated the flake8 issues, ready for review now.
> Thanks.

couldn't pass the full tests (torch 1.6, titan xp) is this expected?
```
======================================================================
FAIL: test_training (tests.test_integration_segmentation_3d.IntegrationSegmentation3D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Documents/MONAI/tests/test_integration_segmentation_3d.py", line 326, in test_training
    np.testing.assert_allclose(ave, s, rtol=5e-3)
  File "/anaconda3/envs/py36env/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1528, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/anaconda3/envs/py36env/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.005, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 0.00078179
Max relative difference: 0.00793673
 x: array(0.099285)
 y: array(0.098503)

======================================================================
FAIL: test_training (tests.test_integration_workflows.IntegrationWorkflows)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Documents/MONAI/tests/test_integration_workflows.py", line 263, in test_training
    np.testing.assert_allclose(best_metric, 0.9241043657064438, rtol=1e-3)
  File "/anaconda3/envs/py36env/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1528, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/anaconda3/envs/py36env/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 0.02201812
Max relative difference: 0.02382644
 x: array(0.946122)
 y: array(0.924104)

----------------------------------------------------------------------
Ran 938 tests in 608.186s

FAILED (failures=2)
```

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I tested full tests locally with PyTorch v1.6 + V100 and passed as expected.
Could you please help test the master branch also? I think if the result of TITAN XP is slightly different, we can ignore.
Do you agree?

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> I tested full tests locally with PyTorch v1.6 + V100 and passed as expected.
> Could you please help test the master branch also? I think if the result of TITAN XP is slightly different, we can ignore.
> Do you agree?
> 
> Thanks.

yes, the same issue for the master. now it becomes difficult for me to locally run `./runtests.sh --codeformat --coverage` to properly verify any PR

**Pull request merged**
