### PR TITLE
ResNet

### PR DESCRIPTION
**Pull request by Douwe-Spaanderman**
### Description 
ResNet implementation with 1D, 2D or 3D convolutions for classification. based on https://github.com/kenshohara/3D-ResNets-PyTorch/blob/master/models/resnet.py . Implementation contains resnet10, 18, 34, 50, 101, 152, 200. Current endpoint is fully connected for classification however backbone can also be used for other purposes (i.e. opt not to use fc layer).

Backbone pre-trained by 23 medical datasets based on this paper: "Med3D: Transfer Learning for 3D Medical Image Analysis" (https://arxiv.org/pdf/1904.00625.pdf). Only available for 3D convolutions.

Possible option to add 2+1D (pseudo-3D) convolution setting.

There are no breaking changes as this is a new feature.

### Status
Ready/**Work in progress**/Hold

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
thanks this looks nice, please sign the commits: https://github.com/Project-MONAI/MONAI/pull/2253/checks?check_run_id=2674985778   this is required [by the repo](https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md#signing-your-work)

**Comment by wyli** [comment]
> thanks this looks nice, please sign the commits: https://github.com/Project-MONAI/MONAI/pull/2253/checks?check_run_id=2674985778 this is required [by the repo](https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md#signing-your-work)

could you please also 
- add some tests following the example: https://github.com/Project-MONAI/MONAI/blob/dev/tests/test_densenet.py and the guide https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md#unit-testing
- address the coding style issues https://github.com/Project-MONAI/MONAI/pull/2253/checks?check_run_id=2683133117#step:7:114

thanks!

**Comment by Douwe-Spaanderman** [comment]
Sorry it took a little while longer to address the coding style issues.

I was also wondering if I could address some issues I am currently facing with pretraining the network. Personally I would like to implement loading the state dict from the paper "Med3D: Transfer Learning for 3D Medical Image Analysis" (https://github.com/Tencent/MedicalNet), I think this closer resamples the issues monai tries to solve, and I receive better performances for my datasets with this pretrained network vs others (i.e. https://github.com/kenshohara/3D-ResNets-PyTorch).
Problem however is that medicalnet doesn't provide a url download for the state dict only, it only provides a downloadable, 2.7 Gb, zip file which include all pretrained networks and testing data. As I don't want to download the whole zip if someone wants to use a pretrained model, does monai have a zoo storage somewhere for pretrained weights for me to store individual state dicts? Or would you prefer if I would implement the pretrained weights on non medical images? Or no pretraining option at all?

Thank you in advance for your response!

**Comment by wyli** [comment]
thanks, this PR is ready to go now. for the pretrained flag, could you please make it `raise NotImplementedError("")` for now? let me create a separate ticket for it and discuss with the monai team soon

**Review by wyli — APPROVED** [review]
thanks!

**Pull request merged**
