### PR TITLE
4037 Update base PyTorch docker to 22.03

### LINKED ISSUE #4037: Update docker and CI tests to PyTorch 22.03
**Is your feature request related to a problem? Please describe.**
Thanks for @deepib 's asking, I will try to update the base docker and CI tests to PyTorch 22.03:
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch
And then run our integration tests to verify it.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #4037 .

### Description
This PR updated the base PyTorch docker to 22.03 for docker and CI tests:
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
> /integration-test

Hi Nic, just a reminder that this won't trigger integration tests with the new docker on your fork (because of the security settings). Normally I push to the core codebase and do some temp tests then revert them. Please see the commit branch and history of this PR for an example. https://github.com/Project-MONAI/MONAI/pull/3297/commits cc @yiheng-wang-nv

**Comment by wyli** [comment]
We do similar ci/cd regularly for  adding/revising tests when newer pytorch is available, an example PR would be this one here https://github.com/Project-MONAI/MONAI/pull/3926 in case @yiheng-wang-nv or other contributors would help with the upgrade in the future.

**Review by wyli — APPROVED** [review]
premerge tests work fine, but in the future, would be good to have temporary tests to verify the integration tests

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your detailed instruction.
As @yiheng-wang-nv and I have local environments, I think we can run it locally to verify with V100.
Now I am running all the integration tests locally, will update later when it's finished.
And BTW, if `/integration-test` can't work for fork repo, should we disable it to avoid misleading message?

Thanks.

**Comment by Nic-Ma** [comment]
All the integration tests passed locally on V100 GPU.

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> Thanks for your detailed instruction. As @yiheng-wang-nv and I have local environments, I think we can run it locally to verify with V100. Now I am running all the integration tests locally, will update later when it's finished. And BTW, if `/integration-test` can't work for fork repo, should we disable it to avoid misleading message?
> 
> Thanks.

Hi Nic, I didn't make it clear, `/integration-test` works fine, it's just we can't modify the integration config from a fork. Local test is also good, but I'd prefer results on the ci server.

**Pull request merged**
