### PR TITLE
temporarily downgrade pytorch

### PR DESCRIPTION
**Pull request by rijobro**
Proposed temporary fix to https://github.com/Project-MONAI/MONAI/issues/1149.

### Description
We're having problems with all unit tests passing with `torch==1.7.0`. Hence, temporarily downgrade until those problems are fixed.

### Status
**Ready*

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Comment by wyli** [comment]
there are a few places
requirements.txt
1:torch>=1.5

pyproject.toml
5:  "torch>=1.5",

docs/requirements.txt
2:torch>=1.5

setup.cfg
15:    torch>=1.5
18:    torch>=1.5

https://github.com/Project-MONAI/MONAI/blob/b7cd8308805c630c10999e31af56a8430d70f097/.github/workflows/cron.yml#L24

**Review by wyli — CHANGES_REQUESTED** [review]
the current change will cause inconsistencies https://github.com/Project-MONAI/MONAI/pull/1151#issuecomment-717958723

**Comment by rijobro** [comment]
Ok, would you prefer me to close the PR or update all instances mentioned above?

**Comment by wyli** [comment]
> Ok, would you prefer me to close the PR or update all instances mentioned above?

thanks @rijobro  please update, this PR is necessary as it'll take some time to fix #1149

**Comment by rijobro** [comment]
Updated. 

Not sure how to test everything though, as it seems that sometimes quotation marks are needed when you have multiple pip conditions.

**Review by wyli — APPROVED** [review]
thank you @rijobro

**Pull request merged**
