### PR TITLE
5596 simplify conda env

### PR DESCRIPTION
**Pull request by wyli**
Fixes https://github.com/Project-MONAI/MONAI/issues/5596
Fixes https://github.com/Project-MONAI/MONAI/issues/5088

### Description
simplify the conda env

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by ericspod** [comment]
I've noticed that `mlflow` is super slow at times to install using the existing environment, and `einops` and `transformers` are really slow as well. I hadn't figured out why but removing these made installing everything else reasonable. I had issues on Windows that the environment would also default to CPU Pytorch for some reason. On the Pytorch site the conda command now includes `pytorch-cuda` as a package with a specification for a version of CUDA so that possibly should be added here as well.

A bare-minimum environment that appears to work is:

```yaml
name: monai
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - numpy>=1.17
  - pytorch>=1.6
  - pytorch-cuda
```

**Comment by ericspod** [comment]
I also created a runtime version of the environment with every package for development removed, this was a little slimmer for just deploying MONAI somewhere, but its contents will change now with the new way Pytorch is doing its packages.

**Comment by ericspod** [comment]
In the logs I see that the Windows build chose the `cpuonly` package by default. This is specified in `conda.yml` but I've seen this happening as a default thing when installing in Windows and I've always had to setup environments manually there.

**Comment by wyli** [comment]
> In the logs I see that the Windows build chose the `cpuonly` package by default. This is specified in `conda.yml` but I've seen this happening as a default thing when installing in Windows and I've always had to setup environments manually there.

I think manually installing pytorch is the recommended way described here https://pytorch.org/get-started/locally/#start-locally let me try to include the cuda requirement for the ci..

**Comment by wyli** [comment]
I've added the cuda dependency following your minimum environment example @ericspod, it works fine with ubuntu and windows: https://github.com/Project-MONAI/MONAI/actions/runs/3566365419/jobs/5992720823
but is not compatible with macos, so I drop the macOS test. 

Apart from the downloading took some time, it looks good to me. Any further suggestions? @ericspod @ericspod. Dropping these pip package requirements in the yaml will make it faster, 
```
  - pip:
    - -r requirements-dev.txt
```
I can do that, just wanted to get your opinion as it'll very different from the current behaviour of `conda update -f environment-dev.yml`.

**Comment by ericspod** [comment]
I've run with the environment file on my Windows box and it's installed things as I expected with the GPU version of Pytorch.

**Review by ericspod — APPROVED** [review]

**Pull request merged**
