### PR TITLE
3471 3491 Add example images for intensity transforms

### LINKED ISSUE #3491: Missing example images for transform `SavitzkyGolaySmooth` and `RandRicianNoise`
**Is your feature request related to a problem? Please describe.**
I checked the document of intensity transforms, found that we didn't add example images for transform `SavitzkyGolaySmooth` and `RandRicianNoise`:
https://github.com/Project-MONAI/MONAI/blob/dev/docs/source/transforms.rst#RandRicianNoise
https://github.com/Project-MONAI/MONAI/blob/dev/docs/source/transforms.rst#SavitzkyGolaySmooth

Would be nice to add them.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #3491 #3471 .

### Description
This PR added the missing example images for 2 intensity transforms and fixed wrong example image of `AsDiscrete`.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Depends on https://github.com/Project-MONAI/DocImages/pull/9.

Thanks.

**Review by wyli — APPROVED** [review]

**Pull request merged**
