### PR TITLE
Fix `UpSample` issue and enhance `UpCat`

### LINKED ISSUE #2759: `BasicUnet` needs to be enhanced
- When `upsample` is `nontrainable`, users cannot change interpolation method (like `nearest`).

### LINKED ISSUE #2760: `UpSample` has wrong docstrings and an issue with `out_channels`
1. Default value of `pre_conv` is `"default"` but in the docstrings, it says `None`.
2. AN error should be raised when:
```
out_channels != in_channels and preconv is None and up_mode == UpsampleMode.NONTRAINABLE
```

### PR DESCRIPTION
**Pull request by yiheng-wang-nv**
Signed-off-by: Yiheng Wang <vennw@nvidia.com>

### Description

This PR fixes a fews issues mentioned in 
Fixes #2759 , fixes #2760 and add some useful parameters for `UpCat` class.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by yiheng-wang-nv** [comment]
Hi @ericspod @wyli  @Nic-Ma , could you please help to look at this draft PR? The forward function of `BasicUNetDecoder` requires a sequence of tensors (represents all feature maps from the encoder), and the sequence length is variable. However, this implementation does not meet the requirements of torchscript. Do you have any suggestions to fix this issue? Thanks!

**Comment by wyli** [comment]
Hi @yiheng-wang-nv the basic unet is only a simple implementation with a focus on the code readability for the basic architecture, I feel this PR will add a bit too much complexity

**Comment by yiheng-wang-nv** [comment]
> Hi @yiheng-wang-nv the basic unet is only a simple implementation with a focus on the code readability for the basic architecture, I feel this PR will add a bit too much complexity
> 
> I think you can create a separate standalone module called `MultiscaleDecoder` as a network block.

Thanks @wyli for the suggestion, I removed the decoder and I will submit a new PR for the implementation. Now this PR is only used to fix #2759  #2760 and add some upsample related parameters into `UpCat` (these are non-breaking changes).

**Review by wyli — APPROVED** [review]
thanks

**Pull request merged**
