### PR TITLE
886 Add IterationMetric refer to to the EpochMetric in ignite

### PR DESCRIPTION
**Pull request by Nic-Ma**
Partly fixes issue 886.

### Description
This PR added `IterationMetric` handler to **remove much duplicated code** in all the metric handlers.
And it can provide **better extension** as it saves the computation results of every iteration.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by yiheng-wang-nv — APPROVED** [review]
Thanks Nic, I checked the code and I think the implementation is correct.

**Comment by Nic-Ma** [comment]
Hi @vfdev-5 ,

This PR added `IterationMetric` to MONAI, is it possible to consider to move it to ignite later? I just referred to the `EpochMetric` in ignite.

Thanks.

**Comment by Nic-Ma** [comment]
Found a small issue in distributed training case, please don't merge it.

Thanks.

**Comment by vfdev-5** [comment]
Hi @Nic-Ma , let me see about that and we can talk about moving it to ignite...

**Comment by Nic-Ma** [comment]
Distributed training issue fixed, ready for review.
Thanks.

**Comment by Nic-Ma** [comment]
integratiion `test_integration_workflow` passed locally.
Thanks.

**Pull request merged**
