### PR TITLE
Remove redundant array copy for TiffFileWSIReader

### LINKED ISSUE #5580: WSIReader, cucim , tifffile, performance regressions
with pathology MIL classification tutorial, as an example
https://github.com/Project-MONAI/tutorials/blob/main/pathology/multiple_instance_learning/panda_mil_train_evaluate_pytorch_gpu.py

WSIReader is now imported from  `from monai.data.wsi_reader import WSIReader`. If changing the import to the old way (now deprecated)  `from monai.data.image_reader import WSIReader`, and setting backend=tifffile, then training is ~10% faster.  seems like a performance regression.

Training time on 8gpu, 1 epoch
- from monai.data.wsi_reader import WSIReader, (backend=cucim)   313 seconds
- from monai.data.wsi_reader import WSIReader, (backend=tiffile)   303 seconds
- from monai.data.image_reader import WSIReader, (backend=tiffile)   283 seconds

### PR DESCRIPTION
**Pull request by drbeh**
Fixes #5580 

### Description
This PR removes an "unnecessary" array copy in WSITiffFileReader, which was causing an slow down in loading whole slide images.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Comment by drbeh** [comment]
```python
from monai.data.wsi_reader import WSIReader
from monai.data.image_reader import WSIReader as WSIReader2

filename = "temp_CMU-1.tiff"
reader1 = WSIReader(backend="TiffFile")
reader2 = WSIReader2(backend="TiffFile")
obj1 = reader1.read(filename)
obj2 = reader2.read(filename)
```
```python
%%timeit
reader1.get_data(obj1, level=1)
```
current performance: 2.32 s ± 97.7
after fixing the issue: 1.45 s ± 12.9 ms

```python
%%timeit
reader2.get_data(obj2, level=1)
```
current performance:  1.97 s ± 50.2 ms
after fixing the issue:. 1.93 s ± 141 ms

**Comment by wyli** [comment]
thanks, is it possible to add a test to avoid regression?

**Comment by drbeh** [comment]
> thanks, is it possible to add a test to avoid regression?

Since it was a performance regression, I am not sure how we should set the criteria for the test as it is hardware dependent, especially when dealing with variability across different run of the same class. Do you have any suggestion? Maybe we should just check for regression whenever we have a major change.

**Comment by wyli** [comment]
Maybe just check theres no array copy, which means changing the patch would also change the input array?

**Comment by drbeh** [comment]
> Maybe just check theres no array copy, which means changing the patch would also change the input array?

Right but in this case there is mo use for the input array since the array input is loaded from disk and is being prepared based on the arguments, so if we copy the original array, it will be discarded anyway.

**Comment by wyli** [comment]
Sure, there was a similar performance bug earlier https://github.com/Project-MONAI/MONAI/issues/3322 hope we can add some tests to avoid reoccurring

**Review by wyli — APPROVED** [review]
would be great to have some integration tests

**Pull request merged**
