### PR TITLE
Update spatial_shape for WSIReader

### LINKED ISSUE #3256: None value in image_meta_dict of WSIReader
**Describe the bug**
The `image_meta_dict` of `WSIReader` contains None value.
Checkout this comment for the problem that it causes and more details: https://github.com/Project-MONAI/MONAI/issues/3161#issuecomment-960355992

### PR DESCRIPTION
**Pull request by drbeh**
Fixes #3256 

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]

**Comment by Nic-Ma** [comment]
Hi @drbeh ,

Is there any unit test to cover this spatial_shape property?

Thanks.

**Comment by drbeh** [comment]
> Hi @drbeh ,
> 
> Is there any unit test to cover this spatial_shape property?
> 
> Thanks.

@Nic-Ma, it is not part of the functionality of WSIReader and I am not sure how it is being used in the rest of MONAI. Do we have any documentation on this? so that I know what type of unit test it requires. Thanks

**Comment by wyli** [comment]
> > Hi @drbeh ,
> > Is there any unit test to cover this spatial_shape property?
> > Thanks.
> 
> @Nic-Ma, it is not part of the functionality of WSIReader and I am not sure how it is being used in the rest of MONAI. Do we have any documentation on this? so that I know what type of unit test it requires. Thanks

If we don't know how it is being used and how to verify this feature, why do we create and merge this PR?

**Comment by drbeh** [comment]
You'reright @wyli! But it was an obvious bug to fix. I don't know how and why you are using it but I only know an instance that it failed. #3256
I will make a unit test out of it but it's better to have a concrete unit test for all elements of these dictionaries that are being passed.

**Comment by drbeh** [comment]
@wyli @Nic-Ma, I added a new test for WSIReader that covers the fixed issue here. https://github.com/Project-MONAI/MONAI/pull/3261/files

**Pull request merged**
