### PR TITLE
862 nonlinear histogram augmentation

### LINKED ISSUE #862: Nonlinear histogram intensity transform
**Describe the solution you'd like**
I think it would be useful to have a transform that provides random, nonlinear warping of an image's intensity histogram. This is motivated by research showing that strong contrast adjustments can force networks to focus on learning shapes, rather than intensity differences, increasing the generalisability of trained networks to new data, see e.g. [here](https://arxiv.org/pdf/2003.01995.pdf).

**Additional context**
I've already worked on a version of this transform for my own research, and included a couple of examples below. I can integrate into MONAI if you think it would be a good addition.

Mild augmentation:
image

Strong augmentation:
image

### PR DESCRIPTION
**Pull request by marksgraham**
Fixes #862  .

### Description
Provides a transform for a random nonlinear warp of the image's intensity histrogram.

### Status
**Work in progress**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by marksgraham** [comment]
Hi @Nic-Ma,
Would you be able to take a look at this and provide some feedback?
Thanks,
Mark

**Review by wyli — APPROVED** [review]
thanks @marksgraham, it looks good. could you follow the commands listed here https://github.com/Project-MONAI/MONAI/pull/953/checks?check_run_id=1082369732 to sign the commits?

**Comment by marksgraham** [comment]
Hi @wyli, when I run git `push --force-with-lease origin 862-nonlinear-histogram`
I get:
```
remote: Permission to Project-MONAI/MONAI.git denied to marksgraham.
fatal: unable to access 'https://github.com/Project-MONAI/MONAI.git/': The requested URL returned error: 403
```

**Comment by wyli** [comment]
> Hi @wyli, when I run git `push --force-with-lease origin 862-nonlinear-histogram`
> I get:
> 
> ```
> remote: Permission to Project-MONAI/MONAI.git denied to marksgraham.
> fatal: unable to access 'https://github.com/Project-MONAI/MONAI.git/': The requested URL returned error: 403
> ```

I see, I think that's because `origin` refer to `https://github.com/Project-MONAI/MONAI.git` in your local git,
you should do 
`git push --force-with-lease your-fork 862-nonlinear-histogram`
where `your-fork` should refer to `https://github.com/marksgraham/MONAI.git`, you can check `git remote -v` locally

**Comment by marksgraham** [comment]
I've done as instructed but puzzled that this has introduced merge conflicts

**Comment by wyli** [comment]
@IsaacYangSLA could you help review the signing issue here? 
perhaps you need to `git rebase origin/master` then add new features, instead of `git merge origin/master` @marksgraham

**Comment by marksgraham** [comment]
HI @wyli ,
I think the most straightforward way out of this might be to create a new PR based on the current master branch of MONAI, if that is OK!

**Comment by wyli** [comment]
> HI @wyli ,
> I think the most straightforward way out of this might be to create a new PR based on the current master branch of MONAI, if that is OK!

sounds great! 

but how could we avoid such case in the future? I actually don't know the root cause of this many merging conflicts @marksgraham, I think you had a similar issue earlier @Nic-Ma ?

**Comment by marksgraham** [comment]
> > HI @wyli ,
> > I think the most straightforward way out of this might be to create a new PR based on the current master branch of MONAI, if that is OK!
> 
> sounds great!
> 
> but how could we avoid such case in the future? I actually don't know the root cause of this many merging conflicts @marksgraham, I think you had a similar issue earlier @Nic-Ma ?

I switched machines between making the initial PR and then trying to fix the signing issue - I wonder if differences in my git config between the two machines led to these issues?

**Comment by wyli** [comment]
closing this in favour of #1026

**Pull request closed without merging**
