### PR TITLE
more tests about the transforms  with MetaTensor

### PR DESCRIPTION
**Pull request by wyli**
### Description
- adding tests using itk-python resampling as the reference (tests/test_meta_affine.py).
- reviewed metatensor compatibility in all transforms
- updated integration tests
- added a pixdim property to metatensor

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
this is mostly test case changes, integration/unit tests all work fine.
https://github.com/Project-MONAI/MONAI/actions/runs/2513728775
https://github.com/Project-MONAI/MONAI/actions/runs/2511887659

only notable code change is `MetaTensor.pxidim` property which is computed from the affine. it's tested against itk:
https://github.com/Project-MONAI/MONAI/blob/db0a637ca5317f0ca7a5af131992b795b6b76505/tests/test_meta_affine.py#L154

I'm merging this PR.

**Comment by rijobro** [comment]
Thanks, this is great. I'm glad that spacing is computed on the fly as opposed to being stored.

**Pull request merged**
