### PR TITLE
3527 update pip install commands

### LINKED ISSUE #3527: prefer `pip install`
**Is your feature request related to a problem? Please describe.**
the `python setup.py` based installation approaches are discouraged
```
running develop
/usr/local/python3.7/site-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
/usr/local/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,

```
documentation and test scripts should be updated to use `pip install`

- see also a similar approach used by cupy https://github.com/cupy/cupy/pull/985/files

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Fixes #3527
 

### Description
replace `python setup.py develop` with `python -m pip install -e .`

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

This draft PR overall looks good to me, may I know what's the main problem with `setup.py`?

Thanks in advance.

**Comment by wyli** [comment]
> This draft PR overall looks good to me, may I know what's the main problem with `setup.py`?

Hi @Nic-Ma, the issue is that `--no-build-isolation` is needed, otherwise it'll always download the latest version of the dependencies. But this makes the command less readable, now I'm not sure whether we should go for this command...

**Comment by Nic-Ma** [comment]
Hi @IsaacYangSLA ,

What's your opinion about `setup` and pip install?

Thanks.

**Comment by IsaacYangSLA** [comment]
> Hi @IsaacYangSLA ,
> 
> What's your opinion about `setup` and pip install?
> 
> Thanks.

I never tried the python setup.py path.  If I have the entire source code (like cloned from github), I intuitively use python -m pip install $PROJECT_ROOT.  Maybe it's from this experience (https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigits.md#optional-enable-support-for-plug-ins).

**Comment by ericspod** [comment]
Just to mention here I had a related issue https://github.com/Project-MONAI/MONAI/issues/3552 with the current environment being changed by running `runtests.sh`.

**Comment by ericspod** [comment]
Hi @wyli I think we've changed things with the files modified here so much that this PR isn't relevant now, shall we close this one?

**Pull request closed without merging**
