### PR TITLE
Update patch merging with a for loop

### PR DESCRIPTION
**Pull request by function2-llx**
Fixes #4735

### Description
Update the patch merging process with a for loop to make it less error-prone and more readable.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.

### CODE REVIEW

**Comment by function2-llx** [comment]
I've come up with one issue: in case someone's using 2D Swin Transformer pre-trained model, I've swapped the order of `i` and `j` in the code. It's unnecessary to do the same for 3D since original implementation should be used for existed pre-trained model.

**Review by wyli — APPROVED** [review]

**Pull request merged**
