### PR TITLE
3922 Make UNETR support torchscript

### LINKED ISSUE #3922: network UNETR does not support torchscript
May need to add the support for it.

### PR DESCRIPTION
**Pull request by yiheng-wang-nv**
Signed-off-by: Yiheng Wang <vennw@nvidia.com>

Fixes #3922  .

### Description
This PR makes UNETR support torchscript, and it also changes some unit test typos.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by ahatamiz** [comment]
@yiheng-wang-nv Thanks for the quick action regarding Torchscript support. Everything looks good to me. 

@wyli I think this can be merged without any issues.

**Review by ahatamiz — APPROVED** [review]

**Comment by yiheng-wang-nv** [comment]
There is a mypy error, but it seems not relate to this PR ( https://github.com/Project-MONAI/MONAI/runs/5506206637?check_suite_focus=true#step:7:466) I checked with the dev branch and found the same error locally.

**Comment by wyli** [comment]
> There is a mypy error, but it seems not relate to this PR ( https://github.com/Project-MONAI/MONAI/runs/5506206637?check_suite_focus=true#step:7:466) I checked with the dev branch and found the same error locally.

yes this is from torch update, I had a fix in #3832. I'll merge this PR soon.

**Pull request merged**
