### PR TITLE
[WIP] 365 Inverse spatial transforms

### PR DESCRIPTION
**Pull request by rijobro**
Fixes https://github.com/Project-MONAI/MONAI/issues/365.

Initial proposition for inverting deterministic spatial transforms.

### Status
**Work in progress**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

**To do**

- [x] Implement `inverse` method for a deterministic spatial transform (`SpatialPadd`)
- [x] Implement `inverse` for `Compose` class
- [x] Create serialised representation of transform (`append_applied_transforms` and `get_input_args`)
- [x] Implement for a random class (to check we can safely store random parameters)
- [x] Test with `CacheDataset` and `DataLoader` to check for multiprocessing problems
- [x] Check GPU vs CPU
- [x] Check numpy vs. tensor
- [x] Check inclusion of batch dimension
- [ ] Test with transforms that return lists (e.g., `RandSpatialCropSamplesd`)
- [ ] Add to `transforms.rst`

**Invertible classes**

- [x] Compose
- [x] SpatialPadd
- [x] BorderPadd
- [x] DivisiblePadd
- [x] SpatialCropd
- [x] CenterSpatialCropd
- [x] CropForegroundd
- [x] ResizeWithPadOrCropd
- [x] Spacingd
- [x] Orientationd
- [x] Rotate90d
- [x] Resized
- [x] Flipd
- [x] Rotated
- [x] Zoomd
- [x] RandSpatialCropd
- [ ] RandSpatialCropSamplesd
- [ ] RandWeightedCropd
- [ ] RandCropByPosNegLabeld
- [x] RandRotate90d
- [x] RandAffined
- [x] Rand2DElasticd
- [x] Rand3DElasticd
- [x] RandFlipd
- [x] RandRotated
- [x] RandZoomd

**Not applicable**
- BoundingRectd -- doesn't modify the image, but adds a dictionary entry containing the bounding box.

### CODE REVIEW

**Comment by rijobro** [comment]
@Nic-Ma @wyli proposition ahead of meeting to discuss inverse transforms

**Comment by rijobro** [comment]
fixes #1515.

**Comment by rijobro** [comment]
Hi all, this is getting close to being ready for review. Here's some images of inverted transforms from the 3D spleen segmentation tutorial:

image


The left column is the ground truth images loaded with no transforms. The middle column is after the use of the validation transforms. In the last column, the top image is the inferred segmentation from the network, and the bottom is the that inferred segmentation put back into its original space. Slices were chosen to maximise visualisation of the spleen so change depending on whether in original or transformed space.

@wyli @Nic-Ma @ericspod

**Comment by wyli** [comment]
major feature merged, the remaining tasks are covered by other tickets or PRs, I'm closing this

**Pull request closed without merging**
