### PR TITLE
Implement NrrdReader

### LINKED ISSUE #4238: Implement `NrrdReader` for `nrrd` and `seg.nrrd` files
**Is your feature request related to a problem? Please describe.**
For one project we are working with `seg.nrrd` files to create pixelwise segmentations. However, when trying to load these files with `LoadImaged` I get the following error: 

```
TemplateTypeError: itk.Image is not wrapped for input type `itk.Vector[itk.SS,3], int`.

To limit the size of the package, only a limited number of
types are available in ITK Python. To print the supported
types, run the following command in your python environment:

    itk.Image.GetTypes()

Possible solutions:
* If you are an application user:
** Convert your input image into a supported format (see below).
** Contact developer to report the issue.
* If you are an application developer, force input images to be
loaded in a supported pixel type.

    e.g.: instance = itk.Image[itk.RGBPixel[itk.UC], int].New(my_input)

* (Advanced) If you are an application developer, build ITK Python yourself and
turned to `ON` the corresponding CMake option to wrap the pixel type or image
dimension you need. When configuring ITK with CMake, you can set
`ITK_WRAP_${type}` (replace ${type} with appropriate pixel type such as
`double`). If you need to support images with 4 or 5 dimensions, you can add
these dimensions to the list of dimensions in the CMake variable
`ITK_WRAP_IMAGE_DIMS`.

```

**Describe the solution you'd like**
When reading `seg.nrrd` files with `pynrrd` the files are handled correctly. I would thus propose to implement a `NrrdReader` based on `pynrrd`.
I have already written the `NrrdReader` for private use and would be happy to make a PR.

**Describe alternatives you've considered**
I have iterated through all supported pixel types, but this either raises an error or leads to incorrect import of the images. For example, some images have format `[4, H, W, 1]`. When forcing pixel type to `itk.Image[itk.RGBPixel[itk.UC], int]`, the image is read as `[3, H, W, 1]`, thus omitting a layer. This is a problem, as the number of layers in the different `seg.nrrd` files varies.

### PR DESCRIPTION
**Pull request by kbressem**
Signed-off-by: kbressem <kenobressem@gmail.com>

Fixes #4238.

### Description
This PR proposes the `NrrdReader` class to correctly read `.nrrd` and `.seg.nrrd` files. 

### Status
**Ready for review**

### Files changes/created
```
monai/data/image_reader.py --> add NrrdReader and NrrdImage
monai/data/__init__.py --> add NrrdReader to imports
monai/transforms/io/array.py --> add NrrdReader to imports and "nrrdreader" to SUPPORTED_READERS
monai/config/deviceconfig.py --> add pynrrd to get_optional_config_values

tests/test_init_reader.py  --> add test for NrrdReader
tests/min_tests.py  --> exclude tests for NrrdReader
requirements-dev.txt --> add pynrrd
```

### FIles created
```
tests/test_nrrd_reader.py --> tests for NrrdReader
```

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @kbressem ,

Thanks very much for your contribution.
There are several places need to add the optional package, you can search `pandas` as the reference.

Thanks in advance.

**Comment by kbressem** [comment]
Hi @Nic-Ma 

I've searched for `optional_import("pandas")`, `pandas`, `'optional_import("nibabel")'`, `nibabel` and `nib` in all scripts. Then I went through the scripts, to check if adding `nrrd` as optional import would be usefull.

### `pandas` was imported in:

- `monai/data/iterable_dataset.py` No image reader is called. I believe `nrrd` would not be used
- `monai/data/utils.py` `pandas` is used to convert tables to dicts. `nrrd` would not be used
- `monai/data/dataset.py` No image reader is called. I believe `nrrd` would not be used
- `monai/config/deviceconfig.py` **I've added `nrrd` to `get_optional_config_values`**

### `nibabel` was imported in:

- `monai/transforms/spatial/dictionary.py` `nibabel` is used in `Orientationd` only. `nrrd` would not be used.
- `monai/transforms/spatial/array.py` `nibabel` is used in `SpatialResample` only, `nrrd` would not be used.
- `monai/transforms/io/array.py` **added `nrrd` as optional import and "nrrdreader" to SUPPORTED_READERS**
- `monai/data/image_reader.py` obviously added `nrrd` :)
- `monai/data/utils.py` `nibabel` is used to reorient spatial axes. `nrrd` would not be used
- `monai/data/nifti_writer.py` `nrrd` would not be used
- `monai/data/image_writer.py` Currently there is no `NrrdWriter`. We are working on one in MONAI-Label and would like to contribute in a future PR.
- `monai/utils/module.py` adding `nrrd` here would not make sense
- `monai/config/deviceconfig.py` I've added `nrrd` to `get_optional_config_values`

I did not find any new instance where importing `nrrd` would be useful. Did I miss something?

**Comment by Nic-Ma** [comment]
Hi @kbressem ,

Sorry maybe I didn't make it clear.
I mean you need to add new optional import into some config files, referring to `pandas`. For example:
https://github.com/Project-MONAI/MONAI/blob/dev/setup.cfg
https://github.com/Project-MONAI/MONAI/blob/dev/docs/requirements.txt
https://github.com/Project-MONAI/MONAI/blob/dev/requirements-dev.txt
https://github.com/Project-MONAI/MONAI/blob/dev/environment-dev.yml
https://github.com/Project-MONAI/MONAI/blob/dev/docs/source/installation.md
https://github.com/Project-MONAI/MONAI/blob/dev/monai/config/deviceconfig.py

Thanks.

**Review by Nic-Ma — APPROVED** [review]

**Comment by kbressem** [comment]
> Hi @kbressem ,
> 
> Sorry maybe I didn't make it clear. I mean you need to add new optional import into some **project config files**, referring to `pandas`. For example: https://github.com/Project-MONAI/MONAI/blob/dev/setup.cfg https://github.com/Project-MONAI/MONAI/blob/dev/docs/requirements.txt https://github.com/Project-MONAI/MONAI/blob/dev/requirements-dev.txt https://github.com/Project-MONAI/MONAI/blob/dev/environment-dev.yml https://github.com/Project-MONAI/MONAI/blob/dev/docs/source/installation.md https://github.com/Project-MONAI/MONAI/blob/dev/monai/config/deviceconfig.py
> 
> Thanks.

Thank you for the clarification. I have added `pynrrd` to all required files.

**Comment by wyli** [comment]
this looks nice, one additional test that is worth adding is to check the consistency of the writer/reader...

ideally we should have a `TestLoadSaveNrrd`, structured like this one:
https://github.com/Project-MONAI/MONAI/blob/812275ae5f4a1bc8a69b70a9823632b6f30a5724/tests/test_image_rw.py#L82-L117
the goal is to test whether the nrrd file created by monai's `ITKWriter` is readable by monai's `NrrdReader` for some basic (non multichannel?)cases.

**Comment by kbressem** [comment]
> the goal is to test whether the nrrd file created by monai's `ITKWriter` is readable by monai's `NrrdReader` for some basic (non multichannel?)cases.

I have added a `TestLoadSaveNrrd` class  to `test_image_rw.py` which tests writing and reading 2d and 3d images. At the moment this only writes using `ITKWriter`, in the future an `NrrdWriter` could be used: https://github.com/Project-MONAI/MONAILabel/pull/779

**Review by wyli — APPROVED** [review]

**Pull request merged**
