### PR TITLE
3021 ITK Reader - support of reversed spatial indexing

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Fixes https://github.com/Project-MONAI/MONAI/issues/3021
fixes https://github.com/Project-MONAI/MONAI/issues/2891
follow-up of https://github.com/Project-MONAI/MONAI/issues/1357

adds a `reverse_indexing` option to the itkreader, so that model trained with `reverse_indexing=True` could be compatible with the use case https://github.com/Project-MONAI/MONAI/issues/2891.

### Description
Screenshot 2021-12-19 at 01 06 04

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
Fyi @thewtex @hjmjohnson

**Review by Nic-Ma — APPROVED** [review]
Looks good to me.
But I am not very sure about the use cases, @ericspod @thewtex could you please help also review it?

Thanks in advance.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

And I see some CI test errors in this PR, could you please help take a look?

Thanks in advance.

**Pull request merged**
