### PR TITLE
237 add MedNIST dataset

### LINKED ISSUE #237: add descriptions for the MedNIST dataset
demo based on MedNIST is in place, we still miss the descriptions such as data source and author, if we choose to redistribute the files (~70MB) we need the licensing information.
see also #151 

we may also provide python API such as `monai.data.MedNIST()` to make the dataset accessible.
(maybe related to #88 )

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #237 .

### Description
This PR added MedNIST dataset link to the tutorial.

### Status
**Ready**

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [ ] Docstrings/Documentation updated

### CODE REVIEW

**Comment by ericspod** [comment]
Should we be using dropbox for this? Perhaps GIT LFS through github makes more sense. Also using the program `tar` makes this almost impossible to run on Windows, Python's `tarfile` library perhaps should be used to access the contents.

**Comment by wyli** [comment]
thanks, updated to use `tarfile`. i don't have any preference for the file hosting please feel free to change

**Comment by tvercaut** [comment]
I agree that using git lfs with no tarball/zip or similar would be much better.

**Comment by Nic-Ma** [comment]
> Should we be using dropbox for this? Perhaps GIT LFS through github makes more sense. Also using the program `tar` makes this almost impossible to run on Windows, Python's `tarfile` library perhaps should be used to access the contents.

Hi @ericspod ,

Could you please help set the expected storage for this dataset? Or feel free to submit PR directly.
Both Wenqi and I don't have much experience with it.
Thanks.

**Comment by Nic-Ma** [comment]
Hi @ericspod and @tvercaut ,

As we are closing to v0.1 release deadline, if we don't have a quick solution here, can we merge this PR first? At least users can get the link in the tutorial.
Thanks.

**Comment by tvercaut** [comment]
The simplest would be to create a new `MedNIST` (or similar name) repo under `Project-MONAI` and enable git lfs on it (see https://help.github.com/en/github/managing-large-files). That said, it would be best to do this once the licensing question discussed in #237 has been resolved.

**Comment by ericspod** [comment]
I would leave sorting LFS off until after the v0.1 release. It's not critical, just a best practice thing, and will make more sense the more examples with large scale data we add.

**Comment by Nic-Ma** [comment]
> I would leave sorting LFS off until after the v0.1 release. It's not critical, just a best practice thing, and will make more sense the more examples with large scale data we add.

So do you agree to merge this PR first for v0.1 and add LFS support later?
Thanks.

**Comment by ericspod** [comment]
@tvercaut mentioned a licensing issue, once that is resolved yes we merge.

**Pull request merged**
