### PR TITLE
STYLE: Prefer fstrings for python 3.6+

### LINKED ISSUE #358: Prefer python 3.6+ fstrings formatting use
Code style modernization and consistency.  fstrings are common in other modern languages like javascript/typescript.

The use of fstrings provides improved readability.

**Describe the solution you'd like**
Prefer the use of fstrings over %-print and format-print
 
**Describe alternatives you've considered**
Leave code as is with python 2.6 compatibility.

**Additional context**

https://medium.com/@ikamenshchikov/f-strings-make-your-python-code-faster-and-more-readable-today-579ef9ca0313

https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/

### PR DESCRIPTION
**Pull request by hjmjohnson**
Fixes #358

### Description

The primary benefit is readability:

Comparing percent and .format call formatting vs f-string:
 - with f-string, you don’t have to order multiple inputs
   in your head to see what output will look like
 - Extra parenthesis, and binary operation or function call
   can become last drop to make a complicated piece just too
   much to parse. Not that f-string did any magic, but it
   lacks an extra set of parenthesis.
 - It also uses 6 chars less than percent formatting and
   10 chars less than the format call.

```bash
pip install flynt
flint

Running flynt v.0.46.1
Execution time:                            1.270s
Files modified:                            36
Character count reduction:                 775 (0.08%)

Per expression type:
Old style (`%`) expressions attempted:     94/102 (92.2%)
`.format(...)` calls attempted:            69/70 (98.6%)
No `.format(...)` calls attempted.
F-string expressions created:              146
Out of all attempted transforms, 9 resulted in errors.
To find out specific error messages, use --verbose flag.
```
### Status
**Ready**

### Types of changes
- [X] Style

### CODE REVIEW

**Comment by hjmjohnson** [comment]
> thanks, shall we keep [monai/_version.py](https://github.com/Project-MONAI/MONAI/blob/42b3b7201961bd889d59132b61d4bfb74d7006cf/monai/_version.py) as it is autogenerated by versioneer

Done!

**Comment by hjmjohnson** [comment]
> Looks good to me.
> Could you please also help update the strings in existing notebooks if possible?
> Thanks.

I will have some student help starting May 18th.  I'll have them work on it then.  Could you make an issue and assign it to me?

**Comment by hjmjohnson** [comment]
> > Looks good to me.
> > Could you please also help update the strings in existing notebooks if possible?
> > Thanks.
> 
> I will have some student help starting May 18th. I'll have them work on it then. Could you make an issue and assign it to me?

I am a bit concerned about then needing to spend a lot of effort re-rendering the notebooks.

**Comment by Nic-Ma** [comment]
Sounds good.
Thanks again for your great contribution here!

**Pull request merged**
