### PR TITLE
3535 - drop python 36 support

### LINKED ISSUE #3535: Drop python 3.6 support
**Is your feature request related to a problem? Please describe.**

Python 3.6 official end of support date is 23rd Dec 2021
- https://www.python.org/downloads/
- https://www.python.org/dev/peps/pep-0494/

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Fixes #3535

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]
Looks good to me.
@ericspod @madil90 @IsaacYangSLA do you guys have any concerns about dropping 3.6?

Thanks in advance.

**Comment by ericspod** [comment]
Our requirement earlier was to support 3.6 because that's what was available on Colab, if they've moved to later versions then so long as no one else has voiced a need for 3.6 we're good.

**Comment by wyli** [comment]
thanks, I updated the version check to raise a warning instead of error https://github.com/Project-MONAI/MONAI/pull/3536/commits/2af2cd5ecafc42cd6458ef9da646ccf27c817588#diff-379462977bbcef7af976c5752da859e668db4e78f04b5b6a1ded9a33225db1ca, so that it wouldn't put a hard stop on any existing use cases

**Pull request merged**
