### PR TITLE
3621 fixes `tests/test_handler_metrics_saver_dist.py`

### LINKED ISSUE #3621: `test_handler_metrics_saver_dist` error
**Describe the bug**
a frequent error from the premerge tests, e.g. 
- https://github.com/Project-MONAI/MONAI/runs/4753115139?check_suite_focus=true
- https://github.com/Project-MONAI/MONAI/runs/4773096722?check_suite_focus=true
```
tests/test_handler_metrics_saver_dist.py
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/__w/MONAI/MONAI/tests/test_handler_metrics_saver_dist.py", line 87, in _run
    for i, row in enumerate(f_csv):
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/__w/MONAI/MONAI/tests/utils.py", line 396, in run_process
    raise e
  File "/__w/MONAI/MONAI/tests/utils.py", line 387, in run_process
    func(*args, **kwargs)
  File "/__w/MONAI/MONAI/tests/utils.py", line 557, in _call_original_func
    return f(*args, **kwargs)
  File "/__w/MONAI/MONAI/tests/test_handler_metrics_saver_dist.py", line 31, in test_content
    self._run(tempdir)
  File "/__w/MONAI/MONAI/tests/test_handler_metrics_saver_dist.py", line 87, in _run
    for i, row in enumerate(f_csv):
OSError: [Errno 9] Bad file descriptor
F
======================================================================
FAIL: test_content (__main__.DistributedMetricsSaver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/MONAI/MONAI/tests/utils.py", line 432, in _wrapper
    assert results.get(), "Distributed call failed."
AssertionError: Distributed call failed.

----------------------------------------------------------------------
Ran 1 test in 10.636s
```

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Fixes #3621

### Description
adds a barrier to sync the processes

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

If `barrier()` works for this issue, could you please help add it to the `DistCall` test utility as @vfdev-5 suggested: https://github.com/Project-MONAI/MONAI/pull/3641#discussion_r782199847
And I would suggest to change the `get_rank()` logic back to the original direct call.
What do you think?

Thanks in advance.

**Comment by wyli** [comment]
I think this is good given the repeated tests are ok. I don't think the utility should be updated at the moment, unless we see different further issues... @Nic-Ma

**Review by Nic-Ma — APPROVED** [review]
Sure, looks good to me.

Thanks.

**Pull request merged**
