### PR TITLE
3477 Update ignite dependency in CI and release to 0.4.7

### LINKED ISSUE #3477: Update CI tests and packaging for ignite v0.4.7
**Is your feature request related to a problem? Please describe.**
Currently, we always set the minimal ignite requirements to 0.4.4:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/config/deviceconfig.py#L256
And set CI tests and packaging to the latest ignite version for compatible tests and verify / leverage the latest features.
Congratulations @vfdev-5 for the v0.4.7 release of ignite:
https://github.com/pytorch/ignite/tree/v0.4.7
I will try to update our dependency ASAP.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #3477 .

### Description
This PR updated the ignite dependency in CI and release to 0.4.7.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @ericspod @wyli @rijobro ,

All the unit tests and integration tests passed in CI.
Ready for review.

Thanks in advance.

**Review by wyli — APPROVED** [review]
Thanks, it looks good to me.

**Pull request merged**
