### PR TITLE
1979 Enhance TTA to align with Invertd args and support no label

### LINKED ISSUE #1979: TestTimeAugmentation assumes label is present
**Describe the bug**
During training/testing/validation, ground truth labels are often present. However, at deployment only the image will be present. The way TTA is currently set up assumes that both image and label are present, which needs to be modified.

cc @diazandr3s

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #1979 .

### Description
This PR enhanced the TTA module to align with `Invertd` transform args and support the inference case without label, just set `orig_key` to the same as `image_key`.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
I will also update the TTA tutorial when this PR merged.

Thanks.

**Review by wyli — APPROVED** [review]
Thanks, perhaps @rijobro could confirm this change

**Comment by Nic-Ma** [comment]
The funtion in the tutorial is:
```py

tt_aug = TestTimeAugmentation(
    val_transforms,
    batch_size=5,
    num_workers=0,
    inferrer_fn=partial(infer_seg, model=model),  # fn to infer segmentation
    device=device
)
```
Seems no need to update.

Thanks.

**Pull request merged**
