### PR TITLE
3335 Fix hash verification of Clang

### LINKED ISSUE #3335: unit test error from `python -m tests.clang_format_utils`
**Describe the bug**
error from `python -m tests.clang_format_utils`
```
2021-11-14 22:26:15,861 - INFO - Downloaded: /__w/MONAI/MONAI/.clang-format-bin/clang-format
2021-11-14 22:26:15,864 - ERROR - check_hash failed 938869fb71b05f5ba345ab36dfbbc4388f53a550.
clang-format: 1.86MB [00:02, 675kB/s]                            
Download /__w/MONAI/MONAI/.clang-format-bin/clang-format failed: sha1 check of downloaded file failed: URL=https://oss-clang-format.s3.us-east-2.amazonaws.com/linux64/clang-format-linux64, filepath=/__w/MONAI/MONAI/.clang-format-bin/clang-format, expected sha1=9073602de1c4e1748f2feea5a0782417b20e3043.
Please remove /__w/MONAI/MONAI/.clang-format-bin/clang-format and retry.
```

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #3335 .

### Description
This PR fixed the hash verification of Clang format package, I think they updated the binary file in Amazon S3.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
Hi @Nic-Ma, this has been updated to use sha256 in the pytorch repo https://github.com/pytorch/pytorch/blob/1adeeabdc0c8832420c091c5c668843768530d7f/tools/linter/adapters/clangtidy_init.py#L128 I recommend we use https://github.com/Project-MONAI/MONAI/pull/3340.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

OK, looks good to me.
I will close this PR.

Thanks.

**Pull request closed without merging**
