### PR TITLE
2045 2058 Add support `device` arg in TransformInverter

### LINKED ISSUE #2045: Add support to move data to `device` after inverting
**Is your feature request related to a problem? Please describe.**
Need to enhance the `TransformInverter` handler to move data to expected `device`.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #2045 #2058 .

### Description
This PR added support to set whether convert data to PyTorch Tensor and specify target device.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
could you address #2058 in this PR as well? they are potentially conflicting and should be verified together

**Comment by Nic-Ma** [comment]
> could you address #2058 in this PR as well? they are potentially conflicting and should be verified together

Sure, I updated the PR to cover #2058 now, could you please help review it again?

Thanks in advance.

**Review by wyli — APPROVED** [review]
thanks!

**Pull request merged**
