### PR TITLE
Auto3Dseg datalist folds enhancements

### PR DESCRIPTION
**Pull request by myron**
### Description

Adds several enhancements to Auto3Dseg datalist fold handling, and fixes  https://github.com/Project-MONAI/MONAI/issues/6201

- automatically sets number of cross-validation folds num_folds based on the number of folds provided in the input datalist json file (instead of setting it always to 5)
-  always saves/copies the input datalist json files into the work_dir (previously it wasn't copied, which makes the work_dir not fully self contained for reproducibility
- if the fold (key) is not provided, but the "validation" key is specified, then "validation" items are used to generate a single-fold split with num_fold==1
- if the fold (key) is not provided and there is no "validation" key, then 5 folds will be automatically randomly generated (with a user warning) 

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by myron** [comment]
flake test fails, even though I ran --autofix several times. can someone help please

**Comment by KumoLiu** [comment]
> flake test fails, even though I ran --autofix several times. can someone help please

Hi @myron, from the error message, I think you could change L407 with:
`for i, (_train_idx, valid_idx) in enumerate(kf.split(datalist["training"])):`
https://github.com/Project-MONAI/MONAI/blob/2f5442ee13ba41a1f65e1e6550dd2897316a6eff/monai/apps/auto3dseg/auto_runner.py#L407
```
/home/runner/work/MONAI/MONAI/monai/apps/auto3dseg/auto_runner.py:407:21: B007 Loop control variable 'train_idx' not used within the loop body. If this is intended, start the name with an underscore.
1     B007 Loop control variable 'train_idx' not used within the loop body. If this is intended, start the name with an underscore.
1
Check failed!
Please run auto style fixes: ./runtests.sh --autofix
Error: Process completed with exit code 1.
```

Thanks!

**Comment by myron** [comment]
I think I've fixed all the mypy and flake issues, please check

**Review by wyli — APPROVED** [review]

**Pull request merged**
