### PR TITLE
6166 drop py37 and torch 1.8

### LINKED ISSUE #6166: deprecating tests for python3.7, torch1.8.*
**Is your feature request related to a problem? Please describe.**
with new tests in https://github.com/Project-MONAI/MONAI/issues/6152, now removing tests for
- python3.7 end of life 27 Jun 2023
- torch 1.8.* and cuda10.2

### PR DESCRIPTION
**Pull request by wyli**
Fixes #6166

### Description
- reviewed the package metadata
- keep testing and code logic

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]
Hi @wyli ,

What do you mean "keep testing and code logic"?
I think we should also remove the test answers for PyTorch 1.8:
https://github.com/Project-MONAI/MONAI/blob/dev/tests/testing_data/integration_answers.py#L224

Others look good to me.

Thanks.

**Comment by wyli** [comment]
> What do you mean "keep testing and code logic"? 

I didn't change the code logic such as
https://github.com/Project-MONAI/MONAI/blob/4f8bc596499981642dd71d30475d2fd212616958/monai/transforms/utils.py#L1485

I think we can keep them and remove it when we drop torch 1.9 in case it's still being used somewhere.

> I think we should also remove the test answers for PyTorch 1.8: https://github.com/Project-MONAI/MONAI/blob/dev/tests/testing_data/integration_answers.py#L224
> 

the tests also matches cuda10.x + recent pytorch versions, it's not torch 1.8 only, I'll update the docstring

**Comment by Nic-Ma** [comment]
> > What do you mean "keep testing and code logic"?
> 
> I didn't change the code logic such as
> 
> https://github.com/Project-MONAI/MONAI/blob/4f8bc596499981642dd71d30475d2fd212616958/monai/transforms/utils.py#L1485
> 
> I think we can keep them and remove it when we drop torch 1.9 in case it's still being used somewhere.
> 
> > I think we should also remove the test answers for PyTorch 1.8: https://github.com/Project-MONAI/MONAI/blob/dev/tests/testing_data/integration_answers.py#L224
> 
> the tests also matches cuda10.x + recent pytorch versions, it's not torch 1.8 only, I'll update the docstring

OK, sounds good to me.

Thanks.

**Pull request merged**
