### PR TITLE
Add rank to the engine.state

### PR DESCRIPTION
**Pull request by Nic-Ma**
### Description
This PR is a non-breaking change to our workflows, added `rank` to the `engine.state`, then we don't need to call `dist.get_rank()` repeatedly in distributed data-parallel programs based on workflows.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
hi @vfdev-5, just wanted to check this with you, is this the expected way for an ignite user to resolve the rank information?

**Comment by vfdev-5** [comment]
Hi @wyli , since v0.4.x we start to provide an abstraction on various [distributed frameworks/backends (nccl/gloo for gpu/cpu via native torch, tpu via torch_xla, horovod)](https://pytorch.org/ignite/distributed.html), so user can do the following:
```python
import ignite.distributed as idist

idist.get_rank()
```
which is dispatched to the current backend and its function like `dist.get_rank()`.
So, if user would like to use `ignite.distributed`, we recommend to do `idist.get_rank()`. In other cases, yes, it is possible to put all those distributed communication info into `engine.state`. Hope this could answer your question.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Do you still have any concern about this PR?
Thanks.

**Review by wyli — APPROVED** [review]
thanks, I'm not sure what the use case is but I guess it's ok for now according to the comments

**Pull request merged**
