### PR TITLE
extending the mlp module

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

### Description
(this is a follow-up of PR https://github.com/Project-MONAI/MONAI/pull/4074 and the discussions.)

This PR extends the MLPBlock (multi-layer perceptron) with
- configurable activation function
- shared or independent dropout instances

the refactoring is inspired by #4074 https://github.com/Project-MONAI/MONAI/pull/4074#issuecomment-1088802998 and the goal is to 
- enhance the flexibility of the essential building blocks and 
- encourage the reuse of the existing components when bringing in new network models.

previously trained models (such as MMAR) can still be used with this update
verified: https://github.com/Project-MONAI/MONAI/runs/5881423584?check_suite_focus=true

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [x] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
this is compatible with previously released model weights, verified here https://github.com/Project-MONAI/MONAI/runs/5881423584?check_suite_focus=true

**Review by yiheng-wang-nv — APPROVED** [review]

**Comment by ericspod** [comment]
I would add some description or comment explaining why this is done and what the meaning is of the modes.

**Comment by ahatamiz** [comment]
Looks good. Please merge so we can update the swin unetr PR.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I think @yiheng-wang-nv @ahatamiz approved the PR, do you have any missing parts to add or update?

Thanks.

**Pull request merged**
