### PR TITLE
403 consistent interp var name

### PR DESCRIPTION
**Pull request by hjmjohnson**
Fixes # 403

### Description
Use consistent naming for interpolation order

### Status
Ready

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [X] Breaking change (fix or new feature that would cause existing functionality to change)
           variable names changed
- [X ] New tests added to cover the changes tests did not cover changed behavior
- [X] Docstrings/Documentation updated

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Could you please help review this PR first as you developed most of the interpolation code?
Thanks.

**Comment by hjmjohnson** [comment]
@wyli Do you have concerns with this?

**Comment by wyli** [comment]
> @wyli Do you have concerns with this?

I agree this is a good direction but not sure how we extend the Enum in the near future to be compatible with pytorch's string based notation such as `mode='bilinear'` https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L3274 any idea? could we make some aliases?

**Comment by hjmjohnson** [comment]
> > @wyli Do you have concerns with this?
> 
> I agree this is a good direction but not sure how we extend the Enum in the near future to be compatible with pytorch's string based notation such as `mode='bilinear'` https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L3274 any idea? could we make some aliases?

I don't see how that desire is related to the current refactoring. I simply replaced integers with IntEnums that are interchangeable with integers, but have descriptive names.  

We could, as a separate effort, extend the enum to have a member function that returns a string based on the enumeration value.

**Comment by wyli** [comment]
> > > @wyli Do you have concerns with this?
> > 
> > 
> > I agree this is a good direction but not sure how we extend the Enum in the near future to be compatible with pytorch's string based notation such as `mode='bilinear'` https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L3274 any idea? could we make some aliases?
> 
> I don't see how that desire is related to the current refactoring. I simply replaced integers with IntEnums that are interchangeable with integers, but have descriptive names.
> 
> We could, as a separate effort, extend the enum to have a member function that returns a string based on the enumeration value.

You are right, we can have another iteration for this.

**Pull request merged**
