### PR TITLE
Add GPU-enabled function "get_largest_connected_component_mask"

### PR DESCRIPTION
**Pull request by dongyang0122**
Fixes # .

### Description
Add GPU-enabled function "get_largest_connected_component_mask" using cuCIM and CuPy.

### Status
Ready

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
Hi Dong, could you help fix the unit tests, you can run them with command: `python -m tests.test_keep_largest_connected_componentd`, the errors are https://github.com/Project-MONAI/MONAI/runs/4858242672?check_suite_focus=true#step:7:19139

**Comment by dongyang0122** [comment]
Yes, working on it.

**Review by wyli — APPROVED** [review]
Thanks, it looks good to me.

**Pull request merged**
