### PR TITLE
3263 Fix tests with latest cuCIM

### LINKED ISSUE #3263: nightly tests error: test_masked_inference_wsi_dataset
**Describe the bug**
```
======================================================================
ERROR: test_read_patches_cucim_2 (tests.test_masked_inference_wsi_dataset.TestMaskedInferenceWSIDataset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/jenkins/agent/workspace/Monai-latest-image/tests/test_masked_inference_wsi_dataset.py", line 169, in test_read_patches_cucim
    dataset = MaskedInferenceWSIDataset(**input_parameters)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 197, in __init__
    self.data = self._prepare_data(data)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 207, in _prepare_data
    prepared_sample = self._prepare_a_sample(sample)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 230, in _prepare_a_sample
    image = self.image_reader.read(sample["image"])
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/data/image_reader.py", line 715, in read
    img = self.wsi_reader(name)
ValueError: Cannot find a plugin to handle '/home/jenkins/agent/workspace/Monai-latest-image/tests/testing_data/temp_uc?id=1sGTKZlJBIz53pfqTxoTqiIQzIoEzHLAe'!

======================================================================
ERROR: test_read_patches_cucim_3 (tests.test_masked_inference_wsi_dataset.TestMaskedInferenceWSIDataset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/jenkins/agent/workspace/Monai-latest-image/tests/test_masked_inference_wsi_dataset.py", line 169, in test_read_patches_cucim
    dataset = MaskedInferenceWSIDataset(**input_parameters)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 197, in __init__
    self.data = self._prepare_data(data)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 207, in _prepare_data
    prepared_sample = self._prepare_a_sample(sample)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 230, in _prepare_a_sample
    image = self.image_reader.read(sample["image"])
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/data/image_reader.py", line 715, in read
    img = self.wsi_reader(name)
ValueError: Cannot find a plugin to handle '/home/jenkins/agent/workspace/Monai-latest-image/tests/testing_data/temp_uc?id=1sGTKZlJBIz53pfqTxoTqiIQzIoEzHLAe'!

======================================================================
ERROR: test_read_patches_cucim_4 (tests.test_masked_inference_wsi_dataset.TestMaskedInferenceWSIDataset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/jenkins/agent/workspace/Monai-latest-image/tests/test_masked_inference_wsi_dataset.py", line 169, in test_read_patches_cucim
    dataset = MaskedInferenceWSIDataset(**input_parameters)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 197, in __init__
    self.data = self._prepare_data(data)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 207, in _prepare_data
    prepared_sample = self._prepare_a_sample(sample)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 230, in _prepare_a_sample
    image = self.image_reader.read(sample["image"])
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/data/image_reader.py", line 715, in read
    img = self.wsi_reader(name)
ValueError: Cannot find a plugin to handle '/home/jenkins/agent/workspace/Monai-latest-image/tests/testing_data/temp_uc?id=1sGTKZlJBIz53pfqTxoTqiIQzIoEzHLAe'!

```

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #3263 .

### Description
This PR fixed the issue that cuCIM can't find a suitable handler.
The root cause is that: this PR https://github.com/Project-MONAI/MONAI/pull/3006 changed the URL of test data, then can't parse the image type from URL, and latest cuCIM added check for image type.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
I tested locally, all tests passed.

Thanks.

**Review by wyli — APPROVED** [review]
thanks for the quick fixes!

**Pull request merged**
