### PR TITLE
Remove GitHub based nightly pipeline

### LINKED ISSUE #2628: Migrate GitHub CI to NVIDIA's internal CI system
**Is your feature request related to a problem? Please describe.**
GitHub CI/CD is currently unscalable & the increased number of users have made PR merge times very large.

**Describe the solution you'd like**
 NVIDIA's internal CI/CD solution can scale and has access to a variety of GPU types for thorough testing. GitHub CI/CD will be deprecated and NVIDIA's solution will be used instead.

**Details**
- The nightly & release pipelines will run inside NVIDIA's system independent of GitHub.
- The pre-merge pipeline will be connected to GitHub. Authorized users can comment '/build' to launch a job. Logs of the job will be sent back to GitHub.

### PR DESCRIPTION
**Pull request by madil90**
Part of #2628  .

### Description
This PR deprecates the GitHub nightly pipeline. NVIDIA's internal CI/CD solution is running and testing MONAI pipeline 

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by wyli — APPROVED** [review]
Thanks, could you sign the commit?

**Comment by madil90** [comment]
done

**Comment by wyli** [comment]
looks like we are still having some testing issues @madil90?
```


Running tests in folder: '.'                                                         
With file pattern: 'test_((?!integration).)'                                         
monai test runner: excluding tests.test_integration_classification_2d                
monai test runner: excluding tests.test_integration_determinism                      
monai test runner: excluding tests.test_integration_workflows                        
monai test runner: excluding tests.test_integration_sliding_window                   
monai test runner: excluding tests.test_integration_stn                              
monai test runner: excluding tests.test_integration_unet_2d                          
monai test runner: excluding tests.test_integration_segmentation_3d                  
monai test runner: excluding tests.test_integration_workflows_gan                    
Traceback (most recent call last):                                                   
  File "./tests/runner.py", line 133, in <module>                                    
    tests = unittest.TestLoader().loadTestsFromNames(cases)                          
  File "/opt/conda/lib/python3.8/unittest/loader.py", line 220, in loadTestsFromNames     
    suites = [self.loadTestsFromName(name, module) for name in names]                
  File "/opt/conda/lib/python3.8/unittest/loader.py", line 220, in <listcomp>        
    suites = [self.loadTestsFromName(name, module) for name in names]                
  File "/opt/conda/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName     
    module = __import__(module_name)                                                                                         
  File "/tmp/tmp.Lw7YoQlEiC/tests/test_bending_energy.py", line 25, in <module>      
    {"pred": torch.ones((1, 3, 5, 5, 5), device=device)},                            
RuntimeError: CUDA error: no kernel image is available for execution on the device     
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.     
For debugging consider passing CUDA_LAUNCH_BLOCKING=1. 
```

**Comment by madil90** [comment]
@wyli Which test is this? This PR doesn't contain any code changes. 

Perhaps they were due to outdated branch. I've rebased it and re-running tests.

**Pull request closed without merging**
