### PR TITLE
followup of #1878

### PR DESCRIPTION
**Pull request by wyli**
update tests (`TEST_CASE_5` duplicated), remove json loading (https://github.com/Project-MONAI/MONAI/pull/1878#discussion_r605015813)

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Comment by behxyz** [comment]
Hi @wyli, why are you removing the json loading part? For pathology, since this metric relies on all the ground truth mask and all the probability masks, it should be called independently after all the inferences are done, and they need be defined in a json fie.

**Comment by wyli** [comment]
> Hi @wyli, why are you removing the json loading part? For pathology, since this metric relies on all the ground truth mask and all the probability masks, it should be called independently after all the inferences are done, and they need be defined in a json fie.

yes before the data working group provides a concrete solution we shouldn't couple the lesion evaluation module with json encoding/decoding logic. if it's really needed please write a separate json loader. This class should only work with `Sequence[Dict]`. my previous comment was somehow ignored... (https://github.com/Project-MONAI/MONAI/pull/1878#discussion_r605015813)

**Comment by wyli** [comment]
thanks for the update @behxyz! there's an example of deepgrow with a demo script to show a task-specific json loader https://github.com/Project-MONAI/tutorials/blob/55006d748626f6af59567a295725ccbd3bdd6bef/deepgrow/ignite/train.py#L315

**Comment by behxyz** [comment]
> > Hi @wyli, why are you removing the json loading part? For pathology, since this metric relies on all the ground truth mask and all the probability masks, it should be called independently after all the inferences are done, and they need be defined in a json fie.
> 
> yes before the data working group provides a concrete solution we shouldn't couple the lesion evaluation module with json encoding/decoding logic. if it's really needed please write a separate json loader. This class should only work with `Sequence[Dict]`. my previous comment was somehow ignored... ([#1878 (comment)](https://github.com/Project-MONAI/MONAI/pull/1878#discussion_r605015813))

OK, I'll add a separate json reader till we have an agreed upon solution. Would this be the topic of data WG or pathology WG?

**Comment by behxyz** [comment]
I updated the test case number to be in an order and committed to your PR.

**Review by behxyz — APPROVED** [review]

**Pull request merged**
