### PR TITLE
Update make_nifti

### PR DESCRIPTION
**Pull request by rijobro**
### Description
Allow test image creation to save to different folders and with different file names.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Review by wyli — APPROVED** [review]
thanks, please add the unit tests to https://github.com/Project-MONAI/MONAI/blob/2500eddf06b8de847519e4584b3a0ef9fe3f0b90/tests/min_tests.py#L29 or add a decorator for skipif nibabel is not installed

**Comment by rijobro** [comment]
done, thanks.

**Pull request merged**
