### PR TITLE
Passing the activation function of the SegResNet to the Residual Blocks

### LINKED ISSUE #3414: Make activation function a parameter of ResBlock
The activation function of a ResBlock is currently hard coded. It would be nice if we could set it ourselves to a specific activation function.

https://github.com/Project-MONAI/MONAI/blob/73d9afa0e21ed190a8582f2ef087d3a98388bec6/monai/networks/blocks/segresnet_block.py#L69

### PR DESCRIPTION
**Pull request by patricio-astudillo**
Fixes #3414

### Description
A few sentences describing the changes proposed in this pull request.

### Status
**Ready/Work in progress/Hold**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by patricio-astudillo** [comment]
@yiheng-wang-nv or @Nic-Ma would it be possible to review this PR please?

**Comment by wyli** [comment]
thanks, could you please sign the commits? https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md#signing-your-work 

(the section on preparing pull requests also provides some useful information about running unit tests locally: https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md#preparing-pull-requests)

**Review by wyli — APPROVED** [review]
thanks, I've made minor updates and locally verified that the mmar model loading tests work fine.

**Pull request merged**
