### PR TITLE
6007 reverse_indexing for PILReader

### LINKED ISSUE #6007: option for LoadImage to be compatible with torchvision save_image
**Is your feature request related to a problem? Please describe.**
for 2d natural images the current loader is not consistent with the common computer vision conversion:
```py
import numpy as np
import torchvision

import monai
from monai.transforms import LoadImage

monai.apps.utils.download_url("https://monai.io/assets/img/MONAI-logo_color.png")

img = LoadImage(image_only=True, ensure_channel_first=True)("MONAI-logo_color.png")  # PILReader
torchvision.utils.save_image(img, "MONAI-logo_color_torchvision.png", normalize=True)
```
the output `MONAI-logo_color_torchvision.png` is transposed compared with `MONAI-logo_color.png`

would be great to add an option to the PIL-backend reader `LoadImage(reader="PILReader")` to support this use case.

see also
- https://github.com/Project-MONAI/MONAI/issues/4862

cc @holgerroth

### PR DESCRIPTION
**Pull request by wyli**
Fixes #6007

### Description
- reverse_indexing = False:
to support consistency with PIL/torchvision
```py
img = LoadImage(image_only=True, ensure_channel_first=True, reverse_indexing=False)("MONAI-logo_color.png")  # PILReader
torchvision.utils.save_image(img, "MONAI-logo_color_torchvision.png", normalize=True)
```
- reverse_indexing = True:
to support consistency with other backends in monai
```py
img = LoadImage(image_only=True, ensure_channel_first=True, reader="PILReader", reverse_indexing=True)(filename)  # PIL backend
img_1 = LoadImage(image_only=True, ensure_channel_first=True, reader="ITKReader")(filename)  # itk backend
np.testing.assert_allclose(img, img_1)  # true
```

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [x] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by holgerroth — APPROVED** [review]
That's useful. Thanks!

**Review by KumoLiu — APPROVED** [review]

**Pull request merged**
