### PR TITLE
Remove unused `cls_token` from patchembedding

### LINKED ISSUE #3454: Unused cls_token in PatchEmbeddingBlock
**Describe the bug**
When I was training the `ViT` with `torch DistributedDataParallel`, during backward, `torch` raises error and reports that 
```
Parameters which did not receive grad for rank 0: vit.patch_embedding.cls_token
```
which means that the `cls_token` did not participate in the backward process.

I checked the implementation of `ViT` and `PatchEmbeddingBlock` and found the unused `cls_token` in `monai.networks.blocks.patchembedding.py: PatchEmbeddingBlock`.
image

**To Reproduce**
1. set environment variable in shell `TORCH_DISTRIBUTED_DEBUG=INFO`
2. train `ViT` with `torch DistributedDataParallel`

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #3454 .

### Description
This PR removed the unused arg `cls_token` from patchembedding.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @ahatamiz @wyli ,

I found that the `self.n_patches` and `self.patch_dim` are only used in the same function, should we change them to local variables? Or keep them for outside access as member variables?

Thanks in advance.

**Comment by wyli** [comment]
This might break the pretrained model loading in https://github.com/Project-MONAI/tutorials/tree/master/self_supervised_pretraining, @finalelement could you please help confirm?

**Review by ahatamiz — APPROVED** [review]
It looks good to me. `self.cls_token ` is not used anywhere.

**Comment by ahatamiz** [comment]
> This might break the pretrained model loading in https://github.com/Project-MONAI/tutorials/tree/master/self_supervised_pretraining, @finalelement could you please help confirm?

Hi @wyli,

Sure. Let me investigate this. 

Thanks

**Comment by ahatamiz** [comment]
Hi @wyli and @Nic-Ma 

I did not see the issue with pretrained weights. Let me investigate more on this one. 

Thanks

**Comment by wyli** [comment]
> Hi @wyli and @Nic-Ma
> 
> I did not see the issue with pretrained weights. Let me investigate more on this one.
> 
> Thanks

We are going to release 0.8.1 soon, if this commit is a breaking change I'll be reluctant to include it... Please help analyse here

**Pull request merged**
