### PR TITLE
1900 Add support to save patch data into NIfTI or PNG files

### LINKED ISSUE #1900: SaveImageD transform need to support list of dict data
**Is your feature request related to a problem? Please describe.**
Currently, several crop transforms may generate a batch of data, but the `SaveImageD` transform will save them with the same file name and overwrite, need an index or something to distinguish batch data.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #1900 .

### Description
This PR added support to save patch data into nifti or png files.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by wyli — COMMENTED** [review]
is it possible to make `patch_index` part of the `meta_data`? I feel image array + meta make more sense than array + meta + patch_index

**Review by wyli — APPROVED** [review]

**Comment by Nic-Ma** [comment]
> is it possible to make `patch_index` part of the `meta_data`? I feel image array + meta make more sense than array + meta + patch_index

In the sample crop, the output data is a list of dict, so I think we should add the index to the dict directly.

Thanks.

**Pull request merged**
