### PR TITLE
1007 fix ITK order issue

### LINKED ISSUE #1007: LoadImage Fails to Load Certain JPEGs
**Describe the bug**
LoadImage fails to correctly load certain JPEGs. The produced array contains streaked information. Test image included:

bad_image
.

**To Reproduce**

```py
im=LoadImage(image_only=True)("bad_image.jpg")
plt.imshow(im[0],cmap="gray")
```

This produces

result

**Expected behavior**
Image should look like the attached image but comes out corrupted when viewed with matplotlib, using `plt.imread` does work.

**Environment (please complete the following information):**
 - Ubuntu
 - Python version 3.7
 - MONAI version 62903b6924e572edfb0d44ce333dd0251e659bfe
 - CUDA/cuDNN version 11, 7.5
 - GPU Titan Xp

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #1007 .

### Description
This PR removed the `keep_axis` argument in ITK as @ericspod found it doesn't work well in #1007 .
So we suppose the loaded data shape is `CDWH` and orientation is also different from NIbabel. If user want to change the shape, they can do it in numpy level.
And I will submit another PR later to use `Nibabel` as the default ImageReader of `LoadImage` transform, then we don't need to consider how to keep the shape & orientation in ITK vs Nibabel, people will use ITK only for DICOM and other formats.
If still want to keep ITK and Nibabel aligned, need ITK team to help work on another PR later.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Is this what you expected?
Thanks.

**Comment by ericspod** [comment]
Looks good to me, this is the change that would work for what I'm doing however setting Nibabel to be the default image reader will require setting parameters for loading jpeg, png, and other standard image formats. If we want the default behaviour of `LoadImage` to be just that, able to load any supported image, we shouldn't make niftis the default. With this change ITK should function as expected.

**Review by ericspod — APPROVED** [review]

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Thanks for your review.
The reason I want to change the default reader of `LoadImage` transform to Nibabel is:
1. The data order and shape may not be expected? As it's C order and different from Nibabel?
2. ITK crashes in multi-threads, can't be compatible with `CacheDataset` and `SmartCacheDataset`.

So I feel maybe it's "safer" to use Nibabel as default for MONAI v0.3, if want to load JPG or PNG, user can set `PILReader` or `ITKReader`?
And `ITKReader` can work for DICOM.
In most cases, users will load Nifti files.
What do you think?

Thanks.

**Comment by ericspod** [comment]
I'm just concerned with being too nifti focused especially since a number of our examples are not nifti based. The data ordering is a bit of an issue but I think it's generally expected that photographic file formats will have HWC ordering, this is what Matplotlib's imshow expects and what all readers for jpeg, png, etc. produce, PIL included. We kind of treat *colour* channels different from tensor channels as we consider them in deep learning. We might have one already by a `TransposeTransform` to do the HWC -> CHW conversion would be the easy fix for this. 

A second issue is these colour images for biomedical applications are typically greyscale so we only want to select one colour channel and not keep all 3 or 4. A third to deal with is some images don't have channel at all, png and others can store single channel images representing masks or luminance maps so the output has HW shape. A transform that does the HWC -> CHW conversion only when the input has a channel dimension would be nice for that. 

The threading issue could be a show-stopper though so perhaps that's more important to work around since caching makes a huge difference.

**Comment by aylward** [comment]
I think we should keep using the itk reader.

Regarding your two points
1) If you would rather have a different ordering, adding a few simple
python statements to the itkreader to reorder the axis in MONAI would fix
that.  It will then work for every file format, returning a consistent
ordering.
2) I believe Hans Johnson and others can help fix the multithreading.
Also, doesn't nibabble use ITK internally?   So, does it not have the same
issue?   Itk is highly multithreaded, so Hans is investigating, and I'd be
surprised if there was an inherent problem.  He wrote the caching system
and he knows itk, so I can't think of anyone better for this task.  You've
got great itk support on your team, use it!

Most importantly, I think we should STRONGLY avoid requiring users to hard
code the file type to be read in their scripts.   This is what motivated
this entire refactoring.   If you want code to be reusable, one of the
first and most important requirements is that it's IO must be file type
agnostic.   MONAI should not be thought of as an end to end solution; it
must integrate with larger research workflows, and not require those
workflows to conform to particular file formats that may change based on
which MONAI script is run.

If the above two are fixed, I think we should continue our commitment to
ITK as the default file reader.

I suggest waiting a few days for itk folks to work with you to address this.

Thanks for considering this,
Stephen

**Comment by Nic-Ma** [comment]
Hi @aylward ,

Thanks very much for your explanation and help here!
Sure, let's wait several days, as we try to code-freeze v0.3 soon, we need to finalize this IO part at this weekend.

Thanks.

**Pull request merged**
