### PR TITLE
Quote $PY_EXE variable to deal with Python path that contain spaces in Bash

### LINKED ISSUE #5857: runtests.sh does not work on Windows
**Describe the bug**
Trying to run tests on a Windows machine, as per the PR template, does not work. The obvious problem is that my python path has spaces in it.

**To Reproduce**
```log
Dzenan@Ryzenator MINGW64 /m/Dev/MONAI (dev)
$ ./runtests.sh -f -u --net --coverage
./runtests.sh: line 115: /c/Program: No such file or directory
./runtests.sh: line 116: [: : integer expression expected
PYTHONPATH: /m/Dev/MONAI:
Python: /c/Program Files/Python39/python
./runtests.sh: line 123: /c/Program: No such file or directory
```

**Expected behavior**
Tests are run, similarly to a Linux machine.

**Environment**

```
Dzenan@Ryzenator MINGW64 /m/Dev/MONAI (dev)
$ python -c 'import monai; monai.config.print_debug_info()'
C:\Program Files\Python39\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (5.0.0)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
================================
Printing MONAI config...
================================
MONAI version: 1.1.0+25.g11810a3e.dirty
Numpy version: 1.21.2
Pytorch version: 1.12.0+cu116
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 11810a3e61c8a60034df5a12d336578705ae6052
MONAI __file__: M:\Dev\MONAI\monai\__init__.py

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
ITK version: 5.3.0
Nibabel version: 3.2.1
scikit-image version: 0.18.3
Pillow version: 9.2.0
Tensorboard version: 2.6.0
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.13.0+cu116
tqdm version: 4.62.2
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: 5.8.0
pandas version: 1.3.2
einops version: NOT INSTALLED or UNKNOWN VERSION.
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Windows
Win32 version: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Win32 edition: Professional
Platform: Windows-10-10.0.22621-SP0
Processor: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
Machine: AMD64
Python version: 3.9.13
Process name: python.exe
Command: ['C:\\Program Files\\Python39\\python.exe', '-c', 'import monai; monai.config.print_debug_info()']
Open files: [popenfile(path='C:\\Windows\\System32\\en-US\\tzres.dll.mui', fd=-1), popenfile(path='C:\\Windows\\System32\\en-US\\KernelBase.dll.mui', fd=-1), popenfile(path='C:\\Windows\\System32\\en-US\\kernel32.dll.mui', fd=-1)]
Num physical CPUs: 12
Num logical CPUs: 24
Num usable CPUs: 24
CPU usage (%): [0.0, 0.0, 11.5, 0.4, 6.0, 7.7, 0.0, 0.2, 1.9, 0.2, 0.2, 0.6, 1.1, 0.4, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.2, 2.6, 0.0, 0.0]
CPU freq. (MHz): 3001
Load avg. in last 1, 5, 15 mins (%): [0.0, 0.0, 0.0]
Disk usage (%): 52.3
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 63.9
Available memory (GB): 34.6
Used memory (GB): 29.3

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 11.6
cuDNN enabled: True
cuDNN version: 8302
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
GPU 0 Name: NVIDIA GeForce RTX 3090
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 82
GPU 0 Total memory (GB): 24.0
GPU 0 CUDA capability (maj.min): 8.6
```

### PR DESCRIPTION
**Pull request by ytl0623**
Fixes #5857.

### Description
When dealing with paths that contain spaces in Bash, it's important to properly quote the variables to ensure that spaces are handled correctly. So, maybe we can replace all `$PY_EXE` variables to `"$PY_EXE"` in the `runtests.sh` file.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by ericspod** [comment]
Hi @ytl0623 thanks for the contribution. Could you please remove the changes to the source files that have been introduced? These are unrelated to the `runtests.sh` script file. Once that's done we can check that the script still works manually.

**Comment by ytl0623** [comment]
Hi @ericspod, I've removed other unrelated changes to the `runtests.sh` script file. Could you please help me review?

Thanks in advance!

**Review by ericspod — APPROVED** [review]
Looks good now, thanks!

**Comment by dzenanz** [comment]
This partly works:
```log
Dzenan@Ryzenator MINGW64 /m/Dev/MONAI (dev)
$ ./runtests.sh --quick --unittests  --disttests
Run tests under /m/Dev/MONAI
PYTHONPATH: /m/Dev/MONAI:
Python: /c/Program Files/Python39/python
MONAI version: 1.3.0+38.gac6bd5dd
Numpy version: 1.22.4
Pytorch version: 2.0.1+cu117
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: ac6bd5dd4ccd6c1e19c259dc93e1eb61610c7876
MONAI __file__: M:\Dev\MONAI\monai\__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.11
ITK version: 5.3.0
Nibabel version: 3.2.1
scikit-image version: 0.22.0
scipy version: 1.11.4
Pillow version: 9.2.0
Tensorboard version: 2.6.0
gdown version: 4.7.1
TorchVision version: 0.15.2+cu117
tqdm version: 4.62.2
lmdb version: 1.4.1
psutil version: 5.8.0
pandas version: 1.3.2
einops version: 0.7.0
transformers version: 4.21.3
mlflow version: 2.8.1
pynrrd version: 1.0.0
clearml version: 1.13.2

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

--------------------------------------------------------------------------------
quick
--------------------------------------------------------------------------------
coverage
--------------------------------------------------------------------------------
unittests
2.0.1+cu117
tensor([[0.3538, 0.6480, 0.5858],
        [0.6119, 0.5092, 0.2991],
        [0.1511, 0.2344, 0.4977],
        [0.5254, 0.6991, 0.4507],
        [0.0519, 0.8435, 0.1419]])
./runtests.sh: line 723: /c/Program: No such file or directory
```

**Comment by ericspod** [comment]
Yes it looks like we missed a few places, wherever `${cmd}` occurs it needs to be quoted as well. @ytl0623 could you do that fix and propose a new PR? Thanks!

**Comment by dzenanz** [comment]
I could give it a try.

**Comment by dzenanz** [comment]
Uh-oh, a few quick tries all failed. The closest I got was: `./runtests.sh: line 723: /c/Program Files/Python39/python -m coverage run --append ./tests/runner.py -p "^(?!test_integration).*(?<!_dist)$": No such file or directory`. I will leave this to someone more familiar with bash syntax.

**Comment by ytl0623** [comment]
Hi, @dzenanz @ericspod, maybe you can try `${cmdPrefix}"${cmd}" ./tests/runner.py -p "^(?!test_integration).*(?<!_dist)$"`

This works for me.
```
unittests
Running tests in folder: '.'
With file pattern: '^(?!test_integration).*(?<!_dist)$'
monai test runner: excluding tests.test_rankfilter_dist
monai test runner: excluding tests.test_integration_determinism
monai test runner: excluding tests.test_integration_autorunner
monai test runner: excluding tests.test_integration_fast_train
monai test runner: excluding tests.test_integration_gpu_customization
monai test runner: excluding tests.test_call_dist
monai test runner: excluding tests.test_integration_stn
monai test runner: excluding tests.test_cumulative_average_dist
monai test runner: excluding tests.test_sampler_dist
monai test runner: excluding tests.test_integration_bundle_run
monai test runner: excluding tests.test_integration_segmentation_3d
monai test runner: excluding tests.test_integration_workers
monai test runner: excluding tests.test_timedcall_dist
monai test runner: excluding tests.test_handler_metrics_saver_dist
monai test runner: excluding tests.test_integration_nnunetv2_runner
monai test runner: excluding tests.test_handler_confusion_matrix_dist
monai test runner: excluding tests.test_integration_unet_2d
monai test runner: excluding tests.test_integration_lazy_samples
monai test runner: excluding tests.test_integration_workflows_gan
monai test runner: excluding tests.test_persistentdataset_dist
monai test runner: excluding tests.test_weighted_random_sampler_dist
monai test runner: excluding tests.test_lmdbdataset_dist
monai test runner: excluding tests.test_handler_rocauc_dist
monai test runner: excluding tests.test_handler_classification_saver_dist
monai test runner: excluding tests.test_prepare_batch_default_dist
monai test runner: excluding tests.test_handler_regression_metrics_dist
monai test runner: excluding tests.test_evenly_divisible_all_gather_dist
monai test runner: excluding tests.test_integration_workflows
monai test runner: excluding tests.test_integration_sliding_window
monai test runner: excluding tests.test_integration_classification_2d
monai test runner: excluding tests.test_fl_monai_algo_dist
monai test runner: excluding tests.test_cv2_dist
```

**Comment by dzenanz** [comment]
That's one of the first things I tried. That gives me: `./runtests.sh: line 723: /c/Program Files/Python39/python -m coverage run --append: No such file or directory`

**Pull request merged**
