### PR TITLE
Cherry pick #7859 for 1.3.2

### PR DESCRIPTION
**Pull request by KumoLiu**
### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by KumoLiu** [comment]
Hi @ericspod, could you please help fix the DCO issue? Thanks!

**Comment by ericspod** [comment]
> Hi @ericspod, could you please help fix the DCO issue? Thanks!

I tried this with the two different messages it suggested, my signoffs are in the commit log now so I think we're good to just force it to pass.

**Review by ericspod — APPROVED** [review]
This is the only fix I think we need for 1.3.2, this change should solve the issue for now and our tests should pass. Thanks!

**Comment by ericspod** [comment]
Do we want to merge this into a separate 1.3.2 branch and do the hotfix release from there? If you've cherry-picked from 1.3.1 then that will have only this change as the difference versus 1.3.1 as we want.

**Comment by KumoLiu** [comment]
> > Hi @ericspod, could you please help fix the DCO issue? Thanks!
> 
> I tried this with the two different messages it suggested, my signoffs are in the commit log now so I think we're good to just force it to pass.

Hi @ericspod, since dco is manually set to pass. I guess it still has not passed yet. Could you please check your github email config by using `git config user.email`? I guess you are using `eric.kerfoot@kcl.ac.uk` to this [commit](https://github.com/Project-MONAI/MONAI/pull/7873/commits/589f1b4b18a68ca4cd6cadc6a18f8500548f2b3e), so it's still not work, you can try set `17726042+ericspod@users.noreply.github.com` in your config.

> Do we want to merge this into a separate 1.3.2 branch and do the hotfix release from there?

Yes, I will create one.

**Comment by ericspod** [comment]
> > > Hi @ericspod, could you please help fix the DCO issue? Thanks!
> > 
> > 
> > I tried this with the two different messages it suggested, my signoffs are in the commit log now so I think we're good to just force it to pass.
> 
> Hi @ericspod, since dco is manually set to pass. I guess it still has not passed yet. Could you please check your github email config by using `git config user.email`? I guess you are using `eric.kerfoot@kcl.ac.uk` to this [commit](https://github.com/Project-MONAI/MONAI/pull/7873/commits/589f1b4b18a68ca4cd6cadc6a18f8500548f2b3e), so it's still not work, you can try set `17726042+ericspod@users.noreply.github.com` in your config.

That seems to have done it.

**Pull request merged**
