### PR TITLE
WIP - Enable pytype

### PR DESCRIPTION
**Pull request by wyli**
part of #476 .

### Description
enable pytype checking in quick tests

### Status
**Work in progress**

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [ ] Docstrings/Documentation updated

### CODE REVIEW

**Comment by wyli** [comment]
@hjmjohnson I'm trying to enable pytype tests, and ideally we should mute all existing warnings with proper pytype config before we introduce new type hints. what do you think? the command is here: https://github.com/Project-MONAI/MONAI/blob/e0d0017d9d4c46e80e61d713d76dff0a937d3b16/.github/workflows/pythonapp.yml#L32
please send PR to this branch or let me know how i can improve this

**Comment by hjmjohnson** [comment]
@wyli We are working on this as well.

**Comment by hjmjohnson** [comment]
This will not work until after all the changes in #473 are included.

**Comment by hjmjohnson** [comment]
@wyli Would you like to have a zoom meeting to discuss moving forward?

**Comment by wyli** [comment]
closing this in favor of #492 thanks @hjmjohnson!

**Pull request closed without merging**
