### PR TITLE
upgrade pytorch version

### LINKED ISSUE #6221: Update base PyTorch docker to 23.02
**Is your feature request related to a problem? Please describe.**
As the PyTorch had been upgraded to 23.02, and it's used in MONAI toolkit 1.0.1, would be nice to also update the MONAI 1.2.0 base docker.
Otherwise, some new features (like TensorRT export) may not work in the old PyTorch docker.

### PR DESCRIPTION
**Pull request by YanxuanLiu**
Fixes #6221 

### Description

Upgrade Pytorch version to 23.02

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]
Looks good to me.
@wyli Could you please help double confirm it?

Thanks in advance.

**Comment by wyli** [comment]
Hi @YanxuanLiu  there are testing issues, please see the blossom logs.

**Pull request merged**
