### PR TITLE
948 Fix existing folder issue in PersistentDataset

### LINKED ISSUE #948: PersistentDataset breaks if given existing folder
**Describe the bug**
If we pass a string to the cache_dir argument of the PersistentDataset that points towards an already existing directory the dataset creation will error out. 

**To Reproduce**
Create a folder (I used pathlib.Path.mkdir) and pass the absolute path string to cache_dir argument.

**Expected behavior**
The existing folder is used and caching happens.

**Actual behavior**
The following error happens:
```
Traceback (most recent call last):
  File "/home/danieltudosiu/projects/nmpevqvae/code_fine_tuning/experiment.py", line 123, in <module>
    conditional_in_channels = iter(data_loader).__next__()[
  File "/home/danieltudosiu/projects/nmpevqvae/evenv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/danieltudosiu/projects/nmpevqvae/evenv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/danieltudosiu/projects/nmpevqvae/evenv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danieltudosiu/projects/nmpevqvae/evenv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danieltudosiu/projects/nmpevqvae/evenv/lib/python3.6/site-packages/monai/data/dataset.py", line 197, in __getitem__
    pre_random_item = self._pre_first_random_cachecheck(self.data[index])
  File "/home/danieltudosiu/projects/nmpevqvae/evenv/lib/python3.6/site-packages/monai/data/dataset.py", line 176, in _pre_first_random_cachecheck
    json.dumps(item_transformed, sort_keys=True).encode("utf-8")
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ndarray' is not JSON serializable
```

**Environment (please complete the following information):**
 - OS - Ubuntu 18.04
 - Python version - 3.6
 - MONAI version [e.g. git commit hash] - 0.2 release
 - CUDA/cuDNN version - 11/8.0.2
 - GPU models and configuration - 2 x Titan V

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #948 .

### Description
This PR fixed no existing folder issue in PersistentDataset and make doc-string more clear.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
thanks, could you add a few test cases to cover the changes?

**Comment by Nic-Ma** [comment]
> thanks, could you add a few test cases to cover the changes?

Sure, added test to cover it.
Thanks.

**Comment by wyli** [comment]
> > thanks, could you add a few test cases to cover the changes?
> 
> Sure, added test to cover it.
> Thanks.

thanks, this key should be `"cached"`? https://github.com/Project-MONAI/MONAI/blob/46166af03add794df65156b56d6e3233923a2211/monai/data/dataset.py#L199

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Seems it's a long time bug, updated to `cached` now.
Thanks.

**Review by wyli — APPROVED** [review]
thanks @Nic-Ma

**Pull request merged**
