### PR TITLE
1042 support DICOM series in 1 folder

### LINKED ISSUE #1042: Add support to read DICOM series
**Is your feature request related to a problem? Please describe.**
For 3D DICOM image, it can save several 2D images in series, so we need to leverage ITK to read them.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #1042 .

### Description
This PR implemented reading logic for DICOM series in 1 folder.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
I tested it with DICOM folder locally:
image

Thanks.

**Comment by Nic-Ma** [comment]
@wyli , you test case looks good to me.
Thanks.

**Review by wyli — APPROVED** [review]

**Comment by jnc13** [comment]
Hi @Nic-Ma, should this be able to cope with a "normal" scanner output where there may be multiple DICOM series' in one folder?
I can successfully use LoadImaged for a folder with including a small number of images comprising one DICOM series, but when I instead feed it a folder for a complete set of DICOM images from one scan I get an error: `OSError: the directory: C:\Users\...\DICOM\ contains more than one DICOM series.`
Is this a known issue?

**Comment by Nic-Ma** [comment]
Hi @jnc13 ,

Could you please help provide your full test program and error log?
I think maybe it's some `file-write` error that it only writes to the empty folder.

Thanks.

**Comment by jnc13** [comment]
Hi @Nic-Ma ,
Yes sure, here is the whole script:

```
import monai
import numpy as np
import glob
import os
import shutil
import matplotlib.pyplot as plt
import torch
from monai.config import print_config
from monai.data import CacheDataset, DataLoader, Dataset, NiftiSaver, ITKReader
from monai.inferers import sliding_window_inference
from monai.losses import DiceLoss
from monai.networks.layers import Norm
from monai.networks.nets import UNet, UNETR
from monai.utils import set_determinism
from monai.metrics import DiceMetric, compute_hausdorff_distance, compute_average_surface_distance
from monai.handlers import SegmentationSaver
from monai.optimizers import Novograd
from monai.transforms import (
    Activations,
    AsDiscrete,
    Compose,
    LoadImaged,
    NormalizeIntensityd,
    Orientationd,
    Spacingd,
    ToTensord,
    AddChanneld,
)

print_config()

# Set up image loading
dcm_path = 'C:\\Users\\[removed details]\\DICOM\\'
data_dicts = [{"image": dcm_path}]
loader = LoadImaged(keys="image")

#Check image loaded correctly

data_dict_check = loader(data_dicts[0])
print(f"first image shape: {data_dict_check['image'].shape}")
print(f"first image spacing:\n{data_dict_check['image_meta_dict']['spacing']}")

    
val_files = data_dicts[:]

    #Transformations must match those used during training
val_transforms = Compose(
    [
        LoadImaged(keys=["image"], dtype=np.float32),
        AddChanneld(keys=["image"]),
        Spacingd(
            keys=["image"],
            pixdim=(3, 3, 3),
        ),
        Orientationd(keys=["image"], axcodes="PLS"),
        NormalizeIntensityd(keys="image", nonzero=True, channel_wise=True),
        ToTensord(keys=["image"]),
    ]
    )

val_ds = CacheDataset(data=val_files, transform=val_transforms, cache_rate=1.0, num_workers=0)
val_loader = DataLoader(val_ds, batch_size=1, num_workers=0)

set_determinism(seed=0)

#Again, model must match that used for training
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    
model = UNet(
        dimensions=3,
        in_channels=1,
        out_channels=2,
        channels=(16, 32, 64, 128, 256),
        strides=(2, 2, 2, 2),
        num_res_units=2,
    ).to(device)
    

# Reminder of some previous settings
loss_function = DiceLoss(to_onehot_y=False, sigmoid=True, squared_pred=True)
optimizer = torch.optim.Adam(model.parameters(), 1e-4, weight_decay=1e-5, amsgrad=True)
post_pred = AsDiscrete(argmax=True, to_onehot=True, n_classes=2)
post_label = AsDiscrete(to_onehot=True, n_classes=2)

# Loading model
model_location = "C://Users//[removed details]//model.pth"
trained_model = model_location
model.load_state_dict(torch.load(trained_model))
model.eval()
    

#Example slices to plot
slices_aug = [3,1]


with torch.no_grad():
        for image in range(len(case_name)):           
            val_input = val_ds[image]["image"].unsqueeze(0).to(device)
            post_trans = Compose([Activations(sigmoid=True), AsDiscrete(threshold_values=True)])  

            roi_size = [96,96,64]
            sw_batch_size = 4
            val_output = sliding_window_inference(val_input, roi_size, sw_batch_size, model)
            val_output_bin = post_trans(val_output)

            # Plot scan image at chosen slice
            plt.figure("image", (4,4))
            plt.title(f"Image")           
            plt.imshow(val_ds[image]["image"][0, :, slices_aug[image], :].detach().cpu(), cmap="gray")

            plt.show()
            
            print("image shape:", val_input.shape)
            print("segmentation shape:", val_output_bin.shape)
                        
            # Model segmentation outputs at chosen slice
            plt.figure("output binarised", (10, 4))
            for i in range(2):
                plt.subplot(1, 2, i + 1)
                plt.title(f"output binarised argmax {i}")
                plt.imshow(val_output_bin[0, i, :, slices_aug[image], :].detach().cpu())
            plt.show()

```






Output if I run it on a whole set of DICOM images:

```
MONAI version: 0.6.0
Numpy version: 1.21.1
Pytorch version: 1.9.0+cpu
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 0ad9e73639e30f4f1af5a1f4a45da9cb09930179

Optional dependencies:
Pytorch Ignite version: 0.4.5
Nibabel version: 3.2.1
scikit-image version: 0.18.2
Pillow version: 8.3.1
Tensorboard version: 2.4.0
gdown version: 3.13.0
TorchVision version: 0.10.0+cpu
ITK version: 5.2.0
tqdm version: 4.61.2
lmdb version: 1.2.1
psutil version: 5.8.0
pandas version: 1.3.0
einops version: 0.3.0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

Traceback (most recent call last):

  File "C:\Users\jc3456\OneDrive - University of Bath\Documents\GitHub\CTPA-PH-tool\dicom_reading.py", line 49, in <module>
    data_dict_check = loader(data_dicts[0])

  File "C:\Users\jc3456\Anaconda3\envs\MONAI_2_aorta_06\lib\site-packages\monai\transforms\io\dictionary.py", line 113, in __call__
    data = self._loader(d[key], reader)

  File "C:\Users\jc3456\Anaconda3\envs\MONAI_2_aorta_06\lib\site-packages\monai\transforms\io\array.py", line 163, in __call__
    img = reader.read(filename)

  File "C:\Users\jc3456\Anaconda3\envs\MONAI_2_aorta_06\lib\site-packages\monai\data\image_reader.py", line 191, in read
    raise OSError(f"the directory: {name} contains more than one DICOM series.")

OSError: the directory: C:\Users\[removed details]\DICOM\ contains more than one DICOM series.
```

Whereas if I only include a subset of images (all from one scan still) in the directory, the output is as expected:

```
MONAI version: 0.6.0
Numpy version: 1.21.1
Pytorch version: 1.9.0+cpu
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 0ad9e73639e30f4f1af5a1f4a45da9cb09930179

Optional dependencies:
Pytorch Ignite version: 0.4.5
Nibabel version: 3.2.1
scikit-image version: 0.18.2
Pillow version: 8.3.1
Tensorboard version: 2.4.0
gdown version: 3.13.0
TorchVision version: 0.10.0+cpu
ITK version: 5.2.0
tqdm version: 4.61.2
lmdb version: 1.2.1
psutil version: 5.8.0
pandas version: 1.3.0
einops version: 0.3.0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

first image shape: (30, 512, 512)
first image spacing:
[0.77734375 0.77734375 2.        ]
Loading dataset: 100%|██████████| 1/1 [00:00<00:00, 12.69it/s]
Processing 0

￼
image shape: torch.Size([1, 1, 133, 9, 342])
segmentation shape: torch.Size([1, 2, 133, 9, 342])
```

The original scan files are 599 DICOM images. I got the output working with no errors when I tried it just on 30 of those files. 
For reference, here is what ITK Snap shows for the DICOM series':
image

I'd really like to get it working on the whole DICOM series and ideally would be able to tell it to run with the series containing the most images. Should that be possible?

Thanks as always

**Comment by wyli** [comment]
thanks for the detailed report. the v0.7.0 release will some improvements in this area, with a series name parameter: https://github.com/Project-MONAI/MONAI/blob/790fc8f572322c6a4c1ab527acfb27447be4bb66/monai/data/image_reader.py#L155 could you please try it with `pip install monai==0.7.0rc4` for now?

**Comment by jnc13** [comment]
Fantastic, I'm glad to see the developments in v0.7.0.
Using v0.7.0 got the first stage of this working, thank you @wyli
I can now successfully feed a directory of all images from a scan with no errors.

Now I'm trying to incorporate the series_name variable so that I can select a specific DICOM series. My above code was a bit convoluted and misleading because as you see I don't actually use LoadImaged for the main processing instead it takes place with:

```
val_files = data_dicts[:]
val_ds = CacheDataset(data=val_files, transform=val_transforms, cache_rate=1.0, num_workers=0)
val_loader = DataLoader(val_ds, batch_size=1, num_workers=0)
```

I have had a go at integrating the new series_name argument but do you please have any recommendations for how to integrate this series_name parameter in this workflow?

Thanks in advaance

**Pull request merged**
