### PR TITLE
5027 Update PyTorch base docker to 22.08

### LINKED ISSUE #5027: Update base PyTorch docker to 22.08
**Is your feature request related to a problem? Please describe.**
Thanks @deepib for the request.
PyTorch docker 22.08 is available now, would be nice to update the base docker of MONAI and update the CI tests to cover it.

### LINKED ISSUE #5037: integration error `test_signal_rand_add_squarepulse_partial`
**Describe the bug**
```py
[2022-08-31T01:07:06.050Z] ======================================================================
[2022-08-31T01:07:06.050Z] ERROR: test_correct_parameters_multi_channels_0 (tests.test_signal_rand_add_squarepulse_partial.TestSignalRandAddSquarePulsePartialNumpy)
[2022-08-31T01:07:06.050Z] ----------------------------------------------------------------------
[2022-08-31T01:07:06.050Z] Traceback (most recent call last):
[2022-08-31T01:07:06.050Z]   File "/usr/local/lib/python3.8/dist-packages/parameterized/parameterized.py", line 533, in standalone_func
[2022-08-31T01:07:06.050Z]     return func(*(a + p.args), **p.kwargs)
[2022-08-31T01:07:06.050Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/tests/test_signal_rand_add_squarepulse_partial.py", line 39, in test_correct_parameters_multi_channels
[2022-08-31T01:07:06.050Z]     partialsquaresignal = partialsquare(sig)
[2022-08-31T01:07:06.050Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/signal/array.py", line 351, in __call__
[2022-08-31T01:07:06.050Z]     squaredpulse_partial = self.magnitude * squarepulse(self.freqs * time_partial)
[2022-08-31T01:07:06.050Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/utils.py", line 1784, in squarepulse
[2022-08-31T01:07:06.050Z]     tmod = torch.remainder(t, 2 * torch.pi)
[2022-08-31T01:07:06.050Z] AttributeError: module 'torch' has no attribute 'pi'
[2022-08-31T01:07:06.050Z] 
[2022-08-31T01:07:06.050Z] ======================================================================
[2022-08-31T01:07:06.050Z] ERROR: test_correct_parameters_multi_channels_0 (tests.test_signal_rand_add_squarepulse_partial.TestSignalRandAddSquarePulsePartialTorch)
[2022-08-31T01:07:06.050Z] ----------------------------------------------------------------------
[2022-08-31T01:07:06.050Z] Traceback (most recent call last):
[2022-08-31T01:07:06.050Z]   File "/usr/local/lib/python3.8/dist-packages/parameterized/parameterized.py", line 533, in standalone_func
[2022-08-31T01:07:06.050Z]     return func(*(a + p.args), **p.kwargs)
[2022-08-31T01:07:06.050Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/tests/test_signal_rand_add_squarepulse_partial.py", line 53, in test_correct_parameters_multi_channels
[2022-08-31T01:07:06.050Z]     partialsquaresignal = partialsquare(sig)
[2022-08-31T01:07:06.050Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/signal/array.py", line 351, in __call__
[2022-08-31T01:07:06.050Z]     squaredpulse_partial = self.magnitude * squarepulse(self.freqs * time_partial)
[2022-08-31T01:07:06.051Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/utils.py", line 1784, in squarepulse
[2022-08-31T01:07:06.051Z]     tmod = torch.remainder(t, 2 * torch.pi)
[2022-08-31T01:07:06.051Z] AttributeError: module 'torch' has no attribute 'pi'
[2022-08-31T01:07:06.051Z] 
[2022-08-31T01:07:06.051Z] ======================================================================
[2022-08-31T01:07:06.051Z] ERROR: test_correct_parameters_multi_channels_0 (tests.test_signal_rand_add_squarepulse.TestSignalRandAddSquarePulseNumpy)
[2022-08-31T01:07:06.051Z] ----------------------------------------------------------------------
[2022-08-31T01:07:06.051Z] Traceback (most recent call last):
[2022-08-31T01:07:06.051Z]   File "/usr/local/lib/python3.8/dist-packages/parameterized/parameterized.py", line 533, in standalone_func
[2022-08-31T01:07:06.051Z]     return func(*(a + p.args), **p.kwargs)
[2022-08-31T01:07:06.051Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/tests/test_signal_rand_add_squarepulse.py", line 37, in test_correct_parameters_multi_channels
[2022-08-31T01:07:06.051Z]     squaredsignal = squared(sig)
[2022-08-31T01:07:06.051Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/signal/array.py", line 221, in __call__
[2022-08-31T01:07:06.051Z]     squaredpulse = self.magnitude * squarepulse(self.freqs * time)
[2022-08-31T01:07:06.051Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/utils.py", line 1784, in squarepulse
[2022-08-31T01:07:06.051Z]     tmod = torch.remainder(t, 2 * torch.pi)
[2022-08-31T01:07:06.051Z] AttributeError: module 'torch' has no attribute 'pi'
[2022-08-31T01:07:06.051Z] 
[2022-08-31T01:07:06.051Z] ======================================================================
[2022-08-31T01:07:06.051Z] ERROR: test_correct_parameters_multi_channels_0 (tests.test_signal_rand_add_squarepulse.TestSignalRandAddSquarePulseTorch)
[2022-08-31T01:07:06.051Z] ----------------------------------------------------------------------
[2022-08-31T01:07:06.051Z] Traceback (most recent call last):
[2022-08-31T01:07:06.051Z]   File "/usr/local/lib/python3.8/dist-packages/parameterized/parameterized.py", line 533, in standalone_func
[2022-08-31T01:07:06.051Z]     return func(*(a + p.args), **p.kwargs)
[2022-08-31T01:07:06.051Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/tests/test_signal_rand_add_squarepulse.py", line 49, in test_correct_parameters_multi_channels
[2022-08-31T01:07:06.051Z]     squaredsignal = squared(sig)
[2022-08-31T01:07:06.051Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/signal/array.py", line 221, in __call__
[2022-08-31T01:07:06.051Z]     squaredpulse = self.magnitude * squarepulse(self.freqs * time)
[2022-08-31T01:07:06.051Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/utils.py", line 1784, in squarepulse
[2022-08-31T01:07:06.051Z]     tmod = torch.remainder(t, 2 * torch.pi)
[2022-08-31T01:07:06.051Z] AttributeError: module 'torch' has no attribute 'pi'
[2022-08-31T01:07:06.051Z] 
[2022-08-31T01:07:06.051Z] ----------------------------------------------------------------------
```

versions:
```
[2022-08-31T00:45:17.041Z] MONAI version: 0.9.1+76.g6690cbe4
[2022-08-31T00:45:17.043Z] Numpy version: 1.23.2
[2022-08-31T00:45:17.043Z] Pytorch version: 1.9.1+cu102
[2022-08-31T00:45:17.043Z] MONAI flags: HAS_EXT = True, USE_COMPILED = True, USE_META_DICT = False
[2022-08-31T00:45:17.043Z] MONAI rev id: 6690cbe496d877a2862d9d3351bd829d634b4c58
[2022-08-31T00:45:17.043Z] MONAI __file__: /home/jenkins/agent/workspace/Monai-pytorch-versions/monai/__init__.py
[2022-08-31T00:45:17.043Z] 
[2022-08-31T00:45:17.043Z] Optional dependencies:
[2022-08-31T00:45:17.043Z] Pytorch Ignite version: 0.4.9
[2022-08-31T00:45:17.043Z] Nibabel version: 4.0.1
[2022-08-31T00:45:17.043Z] scikit-image version: 0.19.3
[2022-08-31T00:45:17.043Z] Pillow version: 9.2.0
[2022-08-31T00:45:17.043Z] Tensorboard version: 2.10.0
[2022-08-31T00:45:17.043Z] gdown version: 4.5.1
[2022-08-31T00:45:17.043Z] TorchVision version: 0.10.1+cu102
[2022-08-31T00:45:17.043Z] tqdm version: 4.64.0
[2022-08-31T00:45:17.043Z] lmdb version: 1.3.0
[2022-08-31T00:45:17.043Z] psutil version: 5.9.1
[2022-08-31T00:45:17.043Z] pandas version: 1.4.3
[2022-08-31T00:45:17.043Z] einops version: 0.4.1
[2022-08-31T00:45:17.043Z] transformers version: 4.21.2
[2022-08-31T00:45:17.043Z] mlflow version: 1.28.0
[2022-08-31T00:45:17.043Z] pynrrd version: 0.4.3
[2022-08-31T00:45:17.043Z] 
[2022-08-31T00:45:17.043Z] For details about installing the optional dependencies, please visit:
[2022-08-31T00:45:17.043Z]     https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
[2022-08-31T00:45:17.043Z] 
[2022-08-31T00:45:17.300Z] coverage
[2022-08-31T00:45:17.300Z] unittests
[2022-08-31T00:45:17.862Z] 1.9.1+cu102
```

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #5027 .
fixes #5037

### Description
This PR updated the PyTorch base docker to 22.08:
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
I have tested all the integration tests locally on V100 GPU, and passed successfully.

Thanks.

**Comment by wyli** [comment]
could you please update to test pytorch 1.12.1 which is released recently?

**Comment by Nic-Ma** [comment]
> could you please update to test pytorch 1.12.1 which is released recently?

Hi @wyli ,

Sure, I updated to PyTorch 1.12.1 and torchvision 0.13.1 for the compatible tests.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @YanxuanLiu @wyli ,

Do you have any other concerns about this update?

Thanks.

**Comment by wyli** [comment]
There are places still use 1.12.0 https://github.com/Project-MONAI/MONAI/blob/6690cbe496d877a2862d9d3351bd829d634b4c58/.github/workflows/pythonapp-min.yml#L54 we do need some documentation to guide the upgrade @YanxuanLiu.

**Comment by Nic-Ma** [comment]
> There are places still use 1.12.0
> 
> https://github.com/Project-MONAI/MONAI/blob/6690cbe496d877a2862d9d3351bd829d634b4c58/.github/workflows/pythonapp-min.yml#L54
> 
> we do need some documentation to guide the upgrade @YanxuanLiu.

OK, I thought you mean just to update 1 place to cover the 1.12.1 test.
Anyway, I already updated all the 1.12.0 tests to 1.12.1.
Could you please help review it again?

Thanks in advance.

**Review by wyli — APPROVED** [review]

**Pull request merged**
