### PR TITLE
backward compatible as discrete

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

follow up of https://github.com/Project-MONAI/MONAI/pull/3352

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
Hi @Nic-Ma, this changes the valueerror of using deprecated arguments to a warning, I think it's needed for 0.8 to avoid too much broken use cases.

**Review by Nic-Ma — APPROVED** [review]
Looks good to me, please double confirm the compatibility with some tutorials or examples.

Thanks.

**Comment by wyli** [comment]
tested with the tutorials: https://github.com/Project-MONAI/MONAI/runs/4265270026?check_suite_focus=true

**Pull request merged**
