### PR TITLE
PR to demonstrate that CI jobs work on gitlab.com w/ GPU runners.  Please comment.  Thank you.

### PR DESCRIPTION
**Pull request by IsaacYangSLA**
This is to verify if all CI tasks work as expected.  Please don't merge it.  Will close it once everything is verified.

### CODE REVIEW

**Comment by IsaacYangSLA** [comment]
Please review and verify if details of two checks can be viewed.  I am pretty sure the first one works without any issue.  The second one, from gitlab.com, requires confirmation.

**Comment by anfeng** [comment]
@ericspod @atbenmurray @wyli can you review this PR? This allow all contributors to see detailed integration tests. Our runner machine has 2+ GPUs

**Comment by IsaacYangSLA** [comment]
There is a queue in gitlab for all CI jobs.  So when there are more than one CI jobs with the same 'tag,' currently we only have 'test' and one runner handles that, jobs will be queued.

**Comment by wyli** [comment]
changes included in https://github.com/Project-MONAI/MONAI/pull/36

**Pull request closed without merging**
