### PR TITLE
Simplify code formatting tests

### PR DESCRIPTION
**Pull request by hjmjohnson**
Related to #429 

### Description
Formatting mistakes cause CI failure.  It is always better to identify and fix CI failures before submitting them.

This PR makes that process a little more transparent by doing both format checking and unit testing from the same script. 

### Status
**Ready**

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [X] New tests added to cover the changes
- [ ] Docstrings/Documentation updated

### CODE REVIEW

**Comment by hjmjohnson** [comment]
> looks nice, shall we create a `requirements-dev.txt`, with all the dependencies for testing:
> 
> ```
> # Requirements for testing
> -r requirements.txt
> flake8==3.8.1
> flake8-mypy
> flake8-bugbear
> flake8-comprehensions
> flake8-executable
> flake8-pyi
> mccabe pep8-naming
> coverage
> parameterized
> ```
> 
> and remove `coverage` and `parameterized` from `requirements.txt`
> 
> I ran into some issue with `flake8-pyi`, `pip install -U` resolved the issue.

:). ... I have already been working on that. Yes.  I'll update this PR with those changes.

**Comment by hjmjohnson** [comment]
> :). ... I have already been working on that. Yes. I'll update this PR with those changes.

@wyli Done.

**Comment by wyli** [comment]
the final step is to replace all `pip install -r requirements.txt` with `pip install -r requirements-dev.txt` in the ci config folder https://github.com/Project-MONAI/MONAI/tree/master/.github/workflows

perhaps update this as well:
https://github.com/Project-MONAI/MONAI/blob/master/.github/workflows/pythonapp.yml#L25-L28

**Comment by hjmjohnson** [comment]
> the final step is to replace all `pip install -r requirements.txt` with `pip install -r requirements-dev.txt` in the ci config folder https://github.com/Project-MONAI/MONAI/tree/master/.github/workflows
> 
> perhaps update this as well:
> https://github.com/Project-MONAI/MONAI/blob/master/.github/workflows/pythonapp.yml#L25-L28
> 
> then I think this is ready

Thanks.  This is now also done.

**Pull request merged**
