### PR TITLE
Test timing

### PR DESCRIPTION
**Pull request by rijobro**
From https://github.com/Project-MONAI/MONAI/issues/1137, I thought it would be a good idea to provide timing information for unit tests.

### Description
Create a runner script that stores the test times, at the end print the sorted results so we can have an idea of which tests are taking the most time.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by wyli — APPROVED** [review]
thanks it looks nice, just a minor comment that
some logic here are also in the perfcontext,  should we refactor to avoid duplication? https://github.com/Project-MONAI/MONAI/blob/7ce3a2ccfef8555e19c01c763c7657b41ccfe115/monai/utils/misc.py#L292

**Comment by rijobro** [comment]
Thanks @wyli . Unfortunately don't think I can reuse that logic as the timing here starts in one method and stops in another.

**Comment by rijobro** [comment]
For interest, some of our tests that take over 30s:

```
test_shape_1 (tests.test_compute_occlusion_sensitivity.TestComputeOcclusionSensitivity) (30.4s)
test_shape_0 (tests.test_cachedataset_parallel.TestCacheDatasetParallel) (38.4s)
test_fcn_shape_1 (tests.test_ahnet.TestFCN) (54.4s)
test_mcfcn_shape_2 (tests.test_ahnet.TestMCFCN) (54.8s)
test_121_2d_shape_0 (tests.test_densenet.TestDENSENET) (55.1s)
test_121_3d_shape_0 (tests.test_densenet.TestDENSENET) (57.1s)
test_fcn_shape_2 (tests.test_ahnet.TestFCN) (63.5s)
test_script (tests.test_basic_unet.TestBasicUNET) (64.9s)
test_169_2d_shape_0 (tests.test_densenet.TestDENSENET) (69.9s)
test_fcn_shape_0 (tests.test_ahnet.TestFCN) (70.1s)
test_mcfcn_shape_0 (tests.test_ahnet.TestMCFCN) (73.0s)
test_mcfcn_shape_1 (tests.test_ahnet.TestMCFCN) (75.8s)
test_169_3d_shape_0 (tests.test_densenet.TestDENSENET) (1.04e+02s)
test_201_2d_shape_0 (tests.test_densenet.TestDENSENET) (1.05e+02s)
test_201_3d_shape_0 (tests.test_densenet.TestDENSENET) (1.28e+02s)
test_264_2d_shape_0 (tests.test_densenet.TestDENSENET) (1.44e+02s)
test_script (tests.test_ahnet.TestAHNET) (1.47e+02s)
test_initialize_pretrained (tests.test_ahnet.TestAHNETWithPretrain) (1.62e+02s)
test_264_3d_shape_0 (tests.test_densenet.TestDENSENET) (1.63e+02s)
test_shape_1 (tests.test_cachedataset_parallel.TestCacheDatasetParallel) (4.7e+02s)
test_121_4d_shape_0 (tests.test_densenet.TestDENSENET) (5.54e+02s)
test_169_4d_shape_0 (tests.test_densenet.TestDENSENET) (9.66e+02s)
test_201_4d_shape_0 (tests.test_densenet.TestDENSENET) (1.22e+03s)
test_264_4d_shape_0 (tests.test_densenet.TestDENSENET) (1.44e+03s)
```

Think the longest at 24 mins is a little excessive!

**Comment by rijobro** [comment]
I'm not convinced, but maybe. I'll explore a little more next week.

**Pull request merged**
