### PR TITLE
2500 upgrade to use 21.06 base image

### LINKED ISSUE #2500: upgrade base image to pytorch 21.06
**Is your feature request related to a problem? Please describe.**
based on cuda 11.3 pytorch c3d40fd

### PR DESCRIPTION
**Pull request by wyli**
Fixes #2500

### Description
base image upgrade
tested:
- https://github.com/Project-MONAI/MONAI/actions/runs/988017864

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Do you know why `/integration-test` can't work in this PR?

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> Do you know why `/integration-test` can't work in this PR?
> 
> Thanks.

the failure is because of #2502, let me merge the fix in https://github.com/Project-MONAI/MONAI/pull/2503 first

**Comment by wyli** [comment]
This passes the integration and was tested https://github.com/Project-MONAI/MONAI/actions/runs/988017864, is there any other concern? @Nic-Ma

**Review by Nic-Ma — APPROVED** [review]
Thanks.

**Pull request merged**
