### PR TITLE
4814 Update PyTorch base docker to 22.07

### LINKED ISSUE #4814: Update PyTorch base container to 22.07
**Is your feature request related to a problem? Please describe.**
22.07 is released now:
CUDA 11.7 Update 1 Preview
CuBLAS 11.10.3.66
NCCL 2.12.12
CuDNN 8.4.1.67
TensorRT 8.4.1
DALI 1.15
Nsight Systems 2022.1.3.3

TensorRT 8.4 will be quite useful to support accelerated inference on the new A100 or 3090Ti GPUs.

Thanks.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #4814 .

### Description
This PR updated the PyTorch base docker to 22.07.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @YanxuanLiu ,

Could you please help update the corresponding Blossom CI config?

Thanks in advance.

**Comment by Nic-Ma** [comment]
Hi @Can-Zhao @wyli ,

I saw an issue in the box utils test:
```
======================================================================
ERROR: test_value_35 (__main__.TestCreateBoxList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "tests/test_box_utils.py", line 208, in test_value
    nms_box = non_max_suppression(
  File "/workspace/data/medical/MONAI/monai/data/box_utils.py", line 1082, in non_max_suppression
    idxs = idxs[to_keep_idx]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```
So I slightly changed the box utils function to fix it, could you please help review it?
Maybe it's not correct, please feel free to submit other fixes, and I didn't check deeper why the previous docker can pass the tests.

Thanks in advance.

**Comment by Can-Zhao** [comment]
> Hi @Can-Zhao @wyli ,
> 
> I saw an issue in the box utils test:
> 
> ```
> ======================================================================
> ERROR: test_value_35 (__main__.TestCreateBoxList)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
>     return func(*(a + p.args), **p.kwargs)
>   File "tests/test_box_utils.py", line 208, in test_value
>     nms_box = non_max_suppression(
>   File "/workspace/data/medical/MONAI/monai/data/box_utils.py", line 1082, in non_max_suppression
>     idxs = idxs[to_keep_idx]
> RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
> ```
> 
> So I slightly changed the box utils function to fix it, could you please help review it? Maybe it's not correct, please feel free to submit other fixes, and I didn't check deeper why the previous docker can pass the tests.
> 
> Thanks in advance.

Thanks Nic. I pushed another commit

**Comment by Nic-Ma** [comment]
Hi @wyli ,

All the integration tests passed locally on V100 GPU with this PyTorch 22.07 docker.

Thanks.

**Review by wyli — APPROVED** [review]
looks good to me if the cuda preview version doesn't affect our modules

**Comment by Nic-Ma** [comment]
let's wait a while for @deepib 's confirmation.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @YanxuanLiu ,

I clicked the `update` button and got the DCO error now, have you changed some CI setting about signing?

Thanks.

**Comment by pxLi** [comment]
> 

from the error page

Summary
Commit sha: [18c5d16](https://github.com/Project-MONAI/MONAI/pull/4815/commits/18c5d163d07b9f123f78dd0729841ae689a84404), Author: Can Zhao, Committer: GitHub; The sign-off is missing.

**Comment by YanxuanLiu** [comment]
> /build

re-build to run with latest image

**Comment by Nic-Ma** [comment]
Hi @wyli @YanxuanLiu ,

Thanks for the update in the Blossom CI, is it OK to merge this PR now?

Thanks.

**Comment by YanxuanLiu** [comment]
> Hi @wyli @YanxuanLiu ,
> 
> Thanks for the update in the Blossom CI, is it OK to merge this PR now?
> 
> Thanks.

Hi @Nic-Ma ,
Blossom CI modifications will be merged after all tests done.

**Comment by YanxuanLiu** [comment]
> > Hi @wyli @YanxuanLiu ,
> > Thanks for the update in the Blossom CI, is it OK to merge this PR now?
> > Thanks.
> 
> Hi @Nic-Ma , Blossom CI modifications will be merged after all tests done.

blossom ci changes merged

**Pull request merged**
