### PR TITLE
Utility to support dataset creation from ConSeP data for nuclick train

### PR DESCRIPTION
**Pull request by SachidanandAlle**
Utility to support dataset creation from ConSeP data for nuclick train

Signed-off-by: Sachidanand Alle <sachidanand.alle@gmail.com>

Fixes # .
- Utility to pre-process dataset
- Minor fix for nuclick transform to throw ValueError with description when invalid clicks result in zero patches

### Description
As part of app, we like to publish zoo models for NuClick + Classification models on ConSeP dataset.
The dataset needs some pre-processing.  This utility shall be used across bundles (scripts) and tutorials for users to use ConSep dataset and run training/eval.

A few sentences describing the changes proposed in this pull request.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @drbeh @wyli ,

Do you think it's necessary to put the CoNSeP dataset specific logic in apps?
I am not very sure about it.

Thanks.

**Comment by SachidanandAlle** [comment]
> Hi @drbeh @wyli ,
> 
> Do you think it's necessary to put the CoNSeP dataset specific logic in apps? I am not very sure about it.
> 
> Thanks.

Probably not.. but this confused me a bit.. 
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/decathlon_datalist.py#L86

Any other way to avoid coping this code across bundles and tutorials. 
For Pathology are we not officially using ConSeP dataset to highlight our possible solutions?

**Comment by drbeh** [comment]
@Nic-Ma @SachidanandAlle 
Although CoNSeP dataset is not as general purpose as decathlon dataset, I think it would nice to make it easier to use for MONAI users, and apps can be an option in my opinion.

**Comment by SachidanandAlle** [comment]
Normally not preferred, but for now, will keep a copy the code in individual bundles/tutorials.  We can revisit this problem later.

**Pull request closed without merging**
