### PR TITLE
Default prepare batch update

### PR DESCRIPTION
**Pull request by ericspod**
### Description
This allows `default_prepare_batch` to handle batches containing a single tensor or a pair of tensors. Normally if one uses array transforms you'll get an error saying the default batch function needs dictionaries so this will allow such transform sequences to be used without modification.

### Status
**Work in progress**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [x] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]
Looks good to me.
Should we also update the `PrepareBatch` class and its subclasses?
https://github.com/Project-MONAI/MONAI/blob/dev/monai/engines/utils.py#L120

Thanks.

**Comment by ericspod** [comment]
I updated the classes with more explanatory commentary and correct type annotations.

**Review by Nic-Ma — APPROVED** [review]

**Pull request merged**
