### PR TITLE
4531 test/update deps versions

### LINKED ISSUE #4531: update and test with new versions of dependencies
**Is your feature request related to a problem? Please describe.**
would be great to add tests with the latest dependencies
- pytorch-ignite 0.4.9 https://github.com/pytorch/ignite/releases/tag/v0.4.9
- pytorch docker image v22.05 https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags
- pytorch LTS 1.8.2

### PR DESCRIPTION
**Pull request by wyli**
Fixes #4531 
Fixes https://github.com/Project-MONAI/MONAI/issues/4606

### Description
- pytorch ~22.05~ 22.06
- pytorch 1.8.2, 1.12.0
- pytorch-ignite 0.4.9

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by yiheng-wang-nv — APPROVED** [review]

**Comment by wyli** [comment]
fyi, 22.05 has this error:
```
======================================================================
FAIL: test_consistency_0 (__main__.TestDynUNetWithInstanceNorm3dNVFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/opt/monai/tests/test_dynunet.py", line 151, in test_consistency
    torch.testing.assert_allclose(result, result_fuser)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_deprecated.py", line 32, in inner_wrapper
    return_value = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_deprecated.py", line 80, in assert_allclose
    torch.testing.assert_close(
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_comparison.py", line 1304, in assert_close
    assert_equal(
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 262127 / 262144 (100.0%)
Greatest absolute difference: 8.843761682510376 at index (0, 0, 35, 8, 34) (up to 1e-05 allowed)
Greatest relative difference: 2552812.792890017 at index (0, 1, 18, 3, 25) (up to 0.0001 allowed)
```

but 22.06 works fine. The base image is updated to 22.06.

**Pull request merged**
