### PR TITLE
3452 Correct cache_dir arg in PersistentDataset

### LINKED ISSUE #3452: Inconsistency of type hints/docstring VS codes for PersistentDataset
**Describe the bug**
There are inconsistencies in the PersistentDataset.
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/dataset.py#L100

In docstring it says the "cache_dir" can be None and type hint it shows Optional.
If we want to be consistent with the docstring, we should add a default value None to this cache_dir argument.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #3452 .

### Description
This PR corrected the arg type and logic of `cache_dir` in `PersistentDataset`.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by YuanTingHsieh — APPROVED** [review]
Logic LGTM, one thing that needs attention is the code coverage, but that can also be fixed later.

**Comment by Nic-Ma** [comment]
Close according to the discussion in #3452 .

Thanks.

**Pull request closed without merging**
