### PR TITLE
[WIP] 3482 Develop components for the model package MVP

### LINKED ISSUE #3482: Develop MVP of model package
**Is your feature request related to a problem? Please describe.**
Thanks for the interesting technical discussion with @wyli @atbenmurray @rijobro , we plan to develop the model package feature step by step. For the initial step, I will try to implement a MVP, referring to some existing solutions, like NVIDIA Clara MMAR, ignite online package, etc. Draft task steps:

- [ ] Search specified python packages and build python instances from dictionary config with `name` / `path` & `args`.
- [ ] Recursively parse configs in a dictionary with dependencies and executable code, for example:
       `{"dataset": {"args": {"data": "#load_decathlon_datalist()"}}, "dataloader": "args": {"data": "@dataset"}}`.
- [ ] Add support to load config from a JSON file, run program from shell commands.
- [ ] Add support to save the raw config dictionaries into TorchScript model.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #3482 .

### Description
Develop the complete prototype of model package in this branch as @wyli suggested: https://github.com/Project-MONAI/MONAI/pull/3518#issuecomment-998600114.
Then split into smaller PRs for review.

### Status
**Work in progress**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Thanks for @wyli 's offline review, changed `ModuleScanner` to `ClassScanner` to make the definition more clear. And moved all the `module import` or `class instantiation` related logic to `utils.module`.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @ericspod @rijobro @wyli ,

Seems we are almost aligned on the config parsing and instantiation parts of model package from the beginning, so I was developing these parts first, and I have completed the draft overall proposal in this PR.
It mainly contains: `ConfigParser`, `ConfigResolver`, `ConfigComponent`.
1. `ConfigComponent` is for every config item in the whole config.
2. `ConfigResolver` is used to recursively resolve dependencies in config items, like `dataloader` depends on `dataset`.
3. `ConfigParser` is upper API to recursively parse the whole config based on `ConfigResolver` and `ConfigComponent`.

I will try to split them into smaller and more clear PRs for your review soon.

Thanks in advance.

**Comment by ericspod** [comment]
The config parsing code looks good to me, submitting that separately to be integrated now separate from the other concepts here would work.

**Comment by Nic-Ma** [comment]
> The config parsing code looks good to me, submitting that separately to be integrated now separate from the other concepts here would work.

Hi @ericspod ,

Thanks for your review.
I started to split the features into smaller and clearer PRs for easier review and update, the first one is: https://github.com/Project-MONAI/MONAI/pull/3720.
It's not urgent to merge it, please review and discuss the solution within team.

Thanks in advance.

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

BTW, do you know any other solutions in other projects that parse / construct python instances from JSON / YAML config?
Maybe we can refer to them for unknown ideas or verify this current solution.

Thanks in advance.

**Comment by ericspod** [comment]
> Hi @ericspod ,
> 
> BTW, do you know any other solutions in other projects that parse / construct python instances from JSON / YAML config? I see something related: https://github.com/cwacek/python-jsonschema-objects https://pynative.com/python-convert-json-data-into-custom-python-object/ Maybe we can refer to them for unknown ideas or verify this current solution.
> 
> Thanks in advance.

These solutions are about creating new types or objects without classes from JSON. What I think we need is just a way to instantiate existing classes based on a name to find the right class and the values for constructor arguments given as JSON. Given a schema like

```javascript
{
    "object_type" : "foo.bar.baz",
    "arguments" : {
        "arg1":1,
        "arg2:[0,1,2]
    }
}
```
This would be interpreted as creating a new object of type `baz` taken from the module `foo.bar`. We can use `importlib.import_module` to load `foo.bar`, extract the member `baz` from it, then instantiate with `baz(arg1=1,arg2=[0,1,2])`. We can do this recursively if arguments are objects rather than literals or JSON structures, but we are still somewhat limited by the possible values JSON provides.

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Thanks for your explanation, I think your idea aligns with my proposal in this PR.
I will involve more guys to take a look and start to review the first separate PR: https://github.com/Project-MONAI/MONAI/pull/3720.

Thanks.

**Comment by wyli** [comment]
closing this one as the major part is now merged into dev, the others are tracked here https://github.com/Project-MONAI/MONAI/issues/3482

**Pull request closed without merging**
