### PR TITLE
add multi-modal (vision + language) transformers

### LINKED ISSUE #2775: Add multi-modality transformers
**Is your feature request related to a problem? Please describe.**
Add transformers that can be leveraged for processing multi-modal data (i.e. vision and language). The transformer block can be also used for creating cross-attention modules. 
**Describe the solution you'd like**
The architecture can be imported from HuggingFace.

### LINKED ISSUE #2776: Add transformer-based NLP pipelines
**Is your feature request related to a problem? Please describe.**
Create needed infrastructures to add transformer-based NLP pipeline.

**Describe the solution you'd like**
The pipeline is targeted for text classification and supports loading pre-trained weights (e.g. BERT).

### LINKED ISSUE #2777: Add transformer-based multi-modality pipelines
**Is your feature request related to a problem? Please describe.**
Create needed infrastructures to add transformer-based multi-modality(e.g. vision and language) pipeline.

**Describe the solution you'd like**
The pipeline is targeted for classification applications and supports loading pre-trained weights (e.g. BERT).

### PR DESCRIPTION
**Pull request by ahatamiz**
Fixes #2775 
Fixes #2776 
Fixes #2777 .

### Status
This pull request adds the full pipeline and support for multimodal (vision + language ) transformers. The transformers implementation follow Huggingface  repository. 

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by ahatamiz** [comment]
Hi @wyli , this PR allows for highly flexible specification of the model for BERT config. Users can simply specify them without any restrictions. 

It has passed all the tests. Let me know if anything else is needed, otherwise should be good for merging. 

Thanks

**Comment by wyli** [comment]
> Hi @wyli , this PR allows for highly flexible specification of the model for BERT config. Users can simply specify them without any restrictions.
> 
> It has passed all the tests. Let me know if anything else is needed, otherwise should be good for merging.
> 
> Thanks

thanks, it looks good to me. please remove the changes in `monai/_version.py`, they are probably automatically generated. (or I can do it later today)

**Comment by ahatamiz** [comment]
> > Hi @wyli , this PR allows for highly flexible specification of the model for BERT config. Users can simply specify them without any restrictions.
> > It has passed all the tests. Let me know if anything else is needed, otherwise should be good for merging.
> > Thanks
> 
> thanks, it looks good to me. please remove the changes in `monai/_version.py`, they are probably automatically generated. (or I can do it later today)

Thanks @wyli. Yes I think there were automatically generated. I think another PR will trigger creating them again.

**Comment by ahatamiz** [comment]
> > > Hi @wyli , this PR allows for highly flexible specification of the model for BERT config. Users can simply specify them without any restrictions.
> > > It has passed all the tests. Let me know if anything else is needed, otherwise should be good for merging.
> > > Thanks
> > 
> > 
> > thanks, it looks good to me. please remove the changes in `monai/_version.py`, they are probably automatically generated. (or I can do it later today)
> 
> Thanks @wyli. Yes I think there were automatically generated. They maybe triggered to be generated again in future PRs.

Just submitted another PR to address this.

**Comment by wyli** [comment]
I've added some basic docs, still this module needs better paper references and general info. this could be done in some follow-up PRs.

**Comment by ahatamiz** [comment]
> I've added some basic docs, still this module needs better paper references and general info. this could be done in some follow-up PRs.

This model is mainly based on our multi-modality paper, which is not yet publicly available. So I suppose there would not be a proper paper reference until we publish it. We can certainly address this in later PRs once paper become available.

**Review by wyli — APPROVED** [review]
looks good to me, it requires follow-up documentation/tutorial to show the usages

**Pull request merged**
