### PR TITLE
Fix deprecated argument in 'scipy.sparse.linalg.cg'

### LINKED ISSUE #7896: cg() got an unexpected keyword argument 'tol'
```
======================================================================
ERROR: test_against_official_code_using_cg (tests.test_ultrasound_confidence_map_transform.TestUltrasoundConfidenceMapTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/MONAI/MONAI/tests/test_ultrasound_confidence_map_transform.py", line 699, in test_against_official_code_using_cg
    output = transform(input_img)
  File "/home/runner/work/MONAI/MONAI/monai/transforms/intensity/array.py", line 2878, in __call__
    conf_map: NdarrayOrTensor = self._compute_conf_map(img_np, mask_np)
  File "/home/runner/work/MONAI/MONAI/monai/data/ultrasound_confidence_map.py", line 381, in __call__
    map_: NDArray = self.confidence_estimation(data, seeds, labels, self.beta, self.gamma)
  File "/home/runner/work/MONAI/MONAI/monai/data/ultrasound_confidence_map.py", line 338, in confidence_estimation
    x = self._solve_linear_system(lap, rhs)
  File "/home/runner/work/MONAI/MONAI/monai/data/ultrasound_confidence_map.py", line 288, in _solve_linear_system
    x, _ = cg(lap, rhs, tol=self.cg_tol, maxiter=self.cg_maxiter, M=m)
TypeError: cg() got an unexpected keyword argument 'tol'
```

### PR DESCRIPTION
**Pull request by KumoLiu**
Fixes #7896 

### Description

- 'scipy.sparse.linalg.cg' keyword argument `tol` is deprecated in favor of `rtol` and will be removed in SciPy v1.14.0. Until then, if set, it will override `rtol`. So update to use `rtol` in `cg`.

- Drop python 3.8 test in packaging and premerge-gpu-test.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by ericspod — APPROVED** [review]

**Review by mingxin-zheng — APPROVED** [review]

**Comment by KumoLiu** [comment]
Hi @ericspod and @Nic-Ma, I dropped Python3.8 test in ".github/workflows/pythonapp.yml" since scipy requires Python>=3.9.
https://github.com/Project-MONAI/MONAI/pull/7897/commits/fb28a3f239b0f08296e0b577ef5c5715deed3d74#diff-cbf97851bdfebccf2fcdd8848c6a93adb8d8affd5c6b1faf00238d528c3ef6cb

Since 3.8 has come to an end, do you have any concern on this change?

**Review by Nic-Ma — APPROVED** [review]

**Comment by KumoLiu** [comment]
Add a numpy version requirement as a workaround in this commit: https://github.com/Project-MONAI/MONAI/pull/7897/commits/5ce2be9600f0aa65318414cd9e295d6d30699b6e
Since multiprocessing with numpy 1.26.4 has some issue in Python3.0. Refer to 
https://github.com/pytorch/pytorch/blob/e7ab7b83bc36825c102987a26b4a199f97674561/.ci/docker/common/install_conda.sh#L83

**Pull request merged**
