### PR TITLE
1478 Fix TorchScript issue in AHnet

### LINKED ISSUE #1478: TorchScript can't work for AHNet when num_psp=0
**Describe the bug**
When set num_psp=0 in AHNet, can't use TorchScript to export the model:
```
RuntimeError: 
Module 'AHNet' has no attribute 'psp' :
  File "/workspace/data/medical/MONAI/monai/networks/nets/ahnet.py", line 514
        d4 = self.dense4(sum4)
        if self.psp_block_num > 0:
            psp = self.psp(d4)
                  ~~~~~~~~ <--- HERE
            x = torch.cat((psp, d4), dim=1)
        else:
```

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #1478 .

### Description
This PR fixed the TorchScript issue in AHNet when `num_block_psp=0`.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
thanks, could you add a test case to cover this change?

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your review.
I updated the PR according to your comments.
Could you please help review it again?

Thanks.

**Review by wyli — APPROVED** [review]

**Pull request merged**
