### PR TITLE
Implement dice cross entropy loss

### LINKED ISSUE #1157: Dice + Cross entropy loss
**Is your feature request related to a problem? Please describe.**
Dice + Cross entropy loss is discussed in #807 and implemented in https://github.com/Project-MONAI/tutorials/blob/master/modules/dynunet_tutorial.ipynb
it should be integrated into the main codebase

### PR DESCRIPTION
**Pull request by yiheng-wang-nv**
Signed-off-by: yiheng-wang-nv <vennw@nvidia.com>

Fixes #1157 .

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by wyli — APPROVED** [review]
thanks!

**Comment by sdesutter** [comment]
I was trying to import DiceCELoss as I found it in the documentation of MONAI, but I keep receiving an ImportError. Does this mean this is still in progress or might there be some kind of issue?

Thanks!

**Comment by yiheng-wang-nv** [comment]
> I was trying to import DiceCELoss as I found it in the documentation of MONAI, but I keep receiving an ImportError. Does this mean this is still in progress or might there be some kind of issue?
> 
> Thanks!

Hi @sdesutter , could you post the error message here? The loss should be imported without errors as the [corresponding unit test checked](https://github.com/Project-MONAI/MONAI/blob/master/tests/test_dice_ce_loss.py). I just downloaded the latest docker image ( docker pull projectmonai/monai:latest ) and tried to import this loss function and it also worked.

**Comment by sdesutter** [comment]
> > I was trying to import DiceCELoss as I found it in the documentation of MONAI, but I keep receiving an ImportError. Does this mean this is still in progress or might there be some kind of issue?
> > Thanks!
> 
> Hi @sdesutter , could you post the error message here? The loss should be imported without errors as the [corresponding unit test checked](https://github.com/Project-MONAI/MONAI/blob/master/tests/test_dice_ce_loss.py). I just downloaded the latest docker image ( docker pull projectmonai/monai:latest ) and tried to import this loss function and it also worked.

The error I'm getting is:
ImportError: cannot import name 'DiceCELoss' from 'monai.losses' (/opt/anaconda3/lib/python3.7/site-packages/monai/losses/__init__.py)

**Comment by rijobro** [comment]
Inside of python, could you run:

```
import monai
print(monai.config.print_config())
```
I wonder if, for example, you are using an older version of the code.

**Comment by sdesutter** [comment]
> Inside of python, could you run:
> 
> ```
> import monai
> monai.config.print_config()
> ```
> 
> I wonder if, for example, you are using an older version of the code.

This is what I got:

MONAI version: 0.4.0
Numpy version: 1.17.2+intel.0
Pytorch version: 1.5.1
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 0563a4467fa602feca92d91c7f47261868d171a1

Optional dependencies:
Pytorch Ignite version: 0.3.0
Nibabel version: 3.0.2
scikit-image version: 0.15.0
Pillow version: 6.2.0
Tensorboard version: 2.0.2
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.6.1
ITK version: NOT INSTALLED or UNKNOWN VERSION.
tqdm version: 4.50.2
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: 5.6.3

**Comment by rijobro** [comment]
Ok, you're using version 0.4.0, and this feature was implemented after that. You'll probably want the master branch:

```
pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI
```

Once you have the master branch, the printed config output should have something like: 

MONAI version: 0.4.0+22.ga4ef691.
Here, 22 is the number of commits since the previous tag, 0.4.0, and `ga4ef691` is the most recent git commit hash.

**Comment by sdesutter** [comment]
> Ok, you're using version 0.4.0, and this feature was implemented after that. You'll probably want the master branch:
> 
> ```
> pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI
> ```
> 
> Once you have the master branch, the printed config output should have something like:
> 
> ```
> MONAI version: 0.4.0+22.ga4ef691
> ```
> 
> Here, 22 is the number of commits since the previous tag, 0.4.0, and `ga4ef691` is the most recent git commit hash.

This worked, the import is working now. 
Thanks a lot for your help!

**Pull request merged**
