### PR TITLE
4822 remove deprecated class call in `EnsureChannelFirst`

### LINKED ISSUE #4822: EnsureChannelFirst calls AddChannel which is deprecated
**Describe the bug**
Using `EnsureChannelFirst` gives the warning: `<class 'monai.transforms.utility.array.AddChannel'>: Class `AddChannel` has been deprecated since version 0.8. please use MetaTensor data type and monai.transforms.EnsureChannelFirst instead.` This is because `EnsureChannelFirst` calls `AddChannel` internally.

### LINKED ISSUE #4828: Bug in deepgrow dataset
**Describe the bug**
It does't work when replace `AsChannelFirstd` with `EnsureChannelFirstd` in [deepgrow's dataset](https://github.com/Project-MONAI/MONAI/blob/dev/monai/apps/deepgrow/dataset.py). 
It mainly due to `_save_data_2d` only works on the image since `EnsureChannelFirstd` also makes the label 4-dimensional(with channel 1 at the first).
https://github.com/Project-MONAI/MONAI/blob/f317aeb1ed93f6d7c43d7d119eca0c00f5c6fdb3/monai/apps/deepgrow/dataset.py#L138-L148

**To Reproduce**
python -m unittest test_deepgrow_dataset.py

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/workspace/Code/MONAI/tests/test_deepgrow_dataset.py", line 87, in test_create_dataset
    deepgrow_datalist = create_dataset(datalist=datalist, output_dir=self.tempdir, **args)
  File "/workspace/Code/MONAI/monai/apps/deepgrow/dataset.py", line 105, in create_dataset
    data = _save_data_2d(
  File "/workspace/Code/MONAI/monai/apps/deepgrow/dataset.py", line 159, in _save_data_2d
    label = vol_label[sid, ...] if vol_label is not None else None
IndexError: index 1 is out of bounds for axis 0 with size 1

(cc @SachidanandAlle @diazandr3s @wyli @Nic-Ma)

### PR DESCRIPTION
**Pull request by KumoLiu**
Fixes #4822 .
Fixed #4828 .

### Description
Remove `AddChannel` and `AsChannelFirst` call in `EnsureChannelFirst`.
Update example in dataset's docstring.
Replace `AsChannelFirst` with `EnsureChannelFirstd` in deepgrow dataset
Replace `AsChannelFirst` with `EnsureChannelFirstd` in utils_create_transform_ims

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
Should this be updated @Nic-Ma https://github.com/Project-MONAI/MONAI/blob/9317d141541fde75640f2f372f5a9d5917dbad98/monai/bundle/utils.py#L59

**Comment by Nic-Ma** [comment]
> 
Definitely.

Hi @KumoLiu ,

Please also update this part.

Thanks.

**Comment by KumoLiu** [comment]
Should these also be updated? @Nic-Ma 
https://github.com/Project-MONAI/MONAI/blob/d0b8bc0e7bd8de924fb9f4b3998437f720bef629/monai/transforms/utils_create_transform_ims.py#L210-L212

https://github.com/Project-MONAI/MONAI/blob/d0b8bc0e7bd8de924fb9f4b3998437f720bef629/monai/apps/deepgrow/dataset.py#L126-L135

**Comment by Nic-Ma** [comment]
Hi @KumoLiu ,

Please update the DeepGrow one, I think we should keep the `utils_create_transform_ims.py` to provide the transform images in doc-string.
@wyli Could you please help confirm it?

Thanks in advance.

**Comment by wyli** [comment]
agreed, I think we should update the deepgrow one to use EnsureChannelFirstd instead of AsChannelFirstd (cc @SachidanandAlle @diazandr3s)

**Comment by KumoLiu** [comment]
Hi @wyli @Nic-Ma,

I confirmed that `AddChanneld` here won't change the transform images in doc-string. I will also update it. 
https://github.com/Project-MONAI/MONAI/blob/f317aeb1ed93f6d7c43d7d119eca0c00f5c6fdb3/monai/transforms/utils_create_transform_ims.py#L210-L212
Thanks!

**Review by wyli — APPROVED** [review]

**Pull request merged**
