### PR TITLE
Create iou_metric.py 

### LINKED ISSUE #4394: Implementation of IoU
**Is your feature request related to a problem? Please describe.**
Please include the IoU as additional counting based metric

**Describe the solution you'd like**
IoU is simply defined as TP/(2*TP+FP+FN) - However one should indicate point out in the documentation that IoU and F1 evaluate similar aspects and should therefore not be used in conjunction

### PR DESCRIPTION
**Pull request by yashika-git**
Signed-off-by: Yashika Jain <yashikajain201@gmail.com>
Fixes #4394

### Description
Implementation of IoU metric (Jaccard score).
Based upon the implementation of DiceMetric.
### Status
**Ready

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [x] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @yashika-git ,

Thanks for your contribution.
Please sign your commit with git command, refer to:
https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md#signing-your-work

Thanks.

**Comment by Nic-Ma** [comment]
Hi @yashika-git ,

I think the PR overall looks good to me, could you please help:
1. Sign your commits.
2. Add the class to `__init__.py`: https://github.com/Project-MONAI/MONAI/blob/dev/monai/metrics/__init__.py
3. Add to the doc: https://github.com/Project-MONAI/MONAI/blob/dev/docs/source/metrics.rst
4. Add unit tests, refer to: https://github.com/Project-MONAI/MONAI/blob/dev/tests/test_compute_meandice.py

Thanks in advance.

**Comment by Nic-Ma** [comment]
Hi @yashika-git ,

I think the PR overall looks good to me, could you please help:
1. Sign your commits.
2. Add the class to `__init__.py`: https://github.com/Project-MONAI/MONAI/blob/dev/monai/metrics/__init__.py
3. Add to the doc: https://github.com/Project-MONAI/MONAI/blob/dev/docs/source/metrics.rst
4. Add unit tests, refer to: https://github.com/Project-MONAI/MONAI/blob/dev/tests/test_compute_meandice.py

Thanks in advance.

**Comment by yashika-git** [comment]
@Nic-Ma, sure!

**Comment by yashika-git** [comment]
@Nic-Ma, I'm new to git and am figuring out how to sign commits. Will update the commits soon.

**Comment by yashika-git** [comment]
Hi @Nic-Ma, 
I've signed the commits, added the class to __init__.py and have added to the doc.
I will add unit tests soon.

**Comment by Nic-Ma** [comment]
Hi @yashika-git ,

Glad to see your contribution here.
You can refer to the contribution guideline for any PR process issue:
https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md

Thanks.

**Comment by yashika-git** [comment]
Hi @Nic-Ma,
I've closed this PR because the branch got very messy and have created a new pull request through another branch.
Here's the link to the same:
https://github.com/Project-MONAI/MONAI/pull/4663
I apologize for the inconvenience caused.

**Comment by Nic-Ma** [comment]
no problem, let's use the new PR for discussion.

Thanks for your contribution.

**Pull request closed without merging**
