### PR TITLE
5775 Fix `_get_latest_bundle_version` issue on Windows

### LINKED ISSUE #5775: `_get_latest_bundle_version` issue on Windows
https://github.com/Project-MONAI/MONAI/blob/69463a69637d4383056455b1b12bdff58294363e/monai/bundle/scripts.py#L185

On Windows, `os.path.join` will produce backslash rather than slash. Therefore, the created url will be wrong (`os.path.join(repo_owner, repo_name)`)
May need to handle this to avoid issues for Windows users.

### PR DESCRIPTION
**Pull request by yiheng-wang-nv**
Signed-off-by: Yiheng Wang <vennw@nvidia.com>

Fixes #5775 .

### Description

This PR fixes the issue of `_get_latest_bundle_version` on Windows (`os.path.join` will produce backslash which will create a wrong url) 
Thanks @SachidanandAlle for finding this issue.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by SachidanandAlle — APPROVED** [review]

**Review by Nic-Ma — APPROVED** [review]
Hi @yiheng-wang-nv ,

Could you please help remove this line to allow the windows tests:
https://github.com/Project-MONAI/MONAI/blob/dev/tests/test_bundle_download.py#L61
Actually, other bundle tests cover windows, like:
https://github.com/Project-MONAI/MONAI/blob/dev/tests/test_integration_bundle_run.py#L108

Thanks.

**Comment by yiheng-wang-nv** [comment]
> Hi @yiheng-wang-nv ,
> 
> Could you please help remove this line to allow the windows tests: https://github.com/Project-MONAI/MONAI/blob/dev/tests/test_bundle_download.py#L61 Actually, other bundle tests cover windows, like: https://github.com/Project-MONAI/MONAI/blob/dev/tests/test_integration_bundle_run.py#L108
> 
> Thanks.

Thanks Nic for the advice. I removed the line you mentioned. However, here I wish to double confirm that if `windows` and `macOS` will execute the unit tests that has `skip_if_quick`. Initially I followed `test_mmar_download` and avoid download and load tests if quick. I'm not sure if it is necessary to remove this decorator as well to ensure`windows` test is able to run.

Hi @wyli , could you please help to give some suggestions? Thanks!

**Comment by wyli** [comment]
there's only quick tests for windows/macos, because we don't have windows+gpu full tests anywhere, so please verify this manually.

**Pull request merged**
