### PR TITLE
Skip failed tests

### PR DESCRIPTION
**Pull request by KumoLiu**
### Description
- skip release_tag_docker for resource issue
- increase tolerance for tests/test_clip_intensity_percentiles.py
- skip tests/test_regularization.py for non-deterministic

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by ericspod — APPROVED** [review]
Looks good for a fix, what was the issue with generating the Docker release?

**Comment by KumoLiu** [comment]
> Looks good for a fix, what was the issue with generating the Docker release?

This one, github limited resource issue.
https://github.com/Project-MONAI/MONAI/issues/7449

**Pull request merged**
