### PR TITLE
fix #6630

### LINKED ISSUE #6630: Wrong spacing checking logic in DICOM series combination
**Describe the bug**

I found some issues in the following code snip:

https://github.com/Project-MONAI/MONAI/blob/2cbed6cfa7a007fa8853a7bd8cf09303172686c9/monai/data/image_reader.py#L510-L521

1. In line 520, spacing should be got from `slices[idx]` instead of `first_slice`; there's the same issue in line 521;
2. the default value in line 514 is `[1.0, 1.0, 1.0]`, which is a `list` instance, while the default value in line 520 is `(1.0, 1.0, 1.0)`, which is a `tuple` instance, and `(1.0, 1.0, 1.0) == [1.0, 1.0, 1.0]` will result in `False`.

### PR DESCRIPTION
**Pull request by function2-llx**
Fixes #6630.

### Description

Fix DICOM series combining checking

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.

### CODE REVIEW

**Comment by function2-llx** [comment]
By the way, the reference link of ITK here:

https://github.com/Project-MONAI/MONAI/blob/b8fbfc25f4cea2fa1a159bd1c00cf3a0a8e80c8c/monai/data/image_reader.py#L231-L235

seems to be broken, and migrate to https://examples.itk.org/src/io/gdcm/readdicomseriesandwrite3dimage/documentation.

**Comment by KumoLiu** [comment]
> By the way, the reference link of ITK here:
> 
> https://github.com/Project-MONAI/MONAI/blob/b8fbfc25f4cea2fa1a159bd1c00cf3a0a8e80c8c/monai/data/image_reader.py#L231-L235
> 
> seems to be broken, and migrate to https://examples.itk.org/src/io/gdcm/readdicomseriesandwrite3dimage/documentation.

Yes, you are right. Could you please help also update it in this PR?
Thanks in advance!

**Comment by function2-llx** [comment]
> > By the way, the reference link of ITK here:
> > https://github.com/Project-MONAI/MONAI/blob/b8fbfc25f4cea2fa1a159bd1c00cf3a0a8e80c8c/monai/data/image_reader.py#L231-L235
> > 
> > seems to be broken, and migrate to [examples.itk.org/src/io/gdcm/readdicomseriesandwrite3dimage/documentation](https://examples.itk.org/src/io/gdcm/readdicomseriesandwrite3dimage/documentation).
> 
> Yes, you are right. Could you please help also update it in this PR? Thanks in advance!

Sure thing. I've updated two ITK reference links.

**Review by KumoLiu — APPROVED** [review]
Thanks for the quick update, LGTM.

**Review by wyli — APPROVED** [review]

**Pull request merged**
