### PR TITLE
Epoch/Iteration interval

### PR DESCRIPTION
**Pull request by danieltudosiu**
### Description
Allowing the choice of epoch and iteration interval.

### Status
Ready

### Types of changes
- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [x] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by danieltudosiu** [comment]
@Nic-Ma  @wyli 

For the new code, how do we test that the event is fired x times in a given time frame?

Also, should we further normalize the steps of the loggers from epoch to iteration so we have the iteration and epoch-based loggers refer to the same time axis?

**Comment by Nic-Ma** [comment]
Hi @danieltudosiu ,

Thanks for your contribution.
May I know what's the feature request? When do you want to set intervals for TensorBoard logging? Maybe your training is too fast that every iteration doesn't have enough time to write TensorBoard?

Thanks.

**Comment by danieltudosiu** [comment]
Hi @Nic-Ma,

Not all networks need logging every epoch or every iteration (for example I log every 25 epochs in my research), so I am suggesting adding an interval argument so users can control the interval at which the logging happens. 

This falls in line with the usual Ignite handlers and it is more of a quality of life improvement.

Cheers!

**Comment by Nic-Ma** [comment]
Hi @danieltudosiu ,

OK, that makes sense.
The CI failure of your PR is because you didn't sign off it, please refer to:
https://github.com/Project-MONAI/MONAI/blob/master/CONTRIBUTING.md#signing-your-work

Others look good to me.


Thanks.

**Comment by danieltudosiu** [comment]
@Nic-Ma, perfect! Will do it today. Thanks!

**Review by Nic-Ma — APPROVED** [review]

**Pull request merged**
