### PR TITLE
2304 enhances image dataset to handle meta

### LINKED ISSUE #2304: Spacing transforms scale pixel dimensions or resample to specified pixel dimensions
Hello! 

Is the Spacing transform meant to resample a given volume to a specified the pixel dimensions? I have NiFTI images with different voxel dimensions and am trying to resample all of them to (2mm, 2mm, 2mm) using the following code. \

```python 

fpaths = ["img0.nii", "img1.nii"]
transform = Compose([
        AsChannelFirst(channel_dim=-1),
        Spacing(pixdim=(2, 2, 2), mode="bilinear", diagonal=True),
        ScaleIntensity(minv=0.0, maxv=1.0),
        ToTensor(),
    ])
check_ds = ImageDataset(image_files=fpaths, transform=transform)

for i, img in enumerate(check_ds):

    print(check_ds[i][0].shape)

```

```img0.nii``` has a pixel size of (2mm, 2mm, 2mm) to begin with so it should remain unchanged by the transform, but its dimensions were shrunk by a factor of 2 from (128, 128, 90) to (64, 64, 46) ```img1.nii``` has a pixel size of (2mm, 2mm, 3.27mm), its first two dimensions should remain unchanged whereas the third dimension should expand to account for the reduced pixel size. However, its dimensions were reduced from (128, 128, 47) to (64, 64, 24). It appears that the Spacing transform only scales the pixel dimensions by a factor of 2 instead of resampling them to the specified dimensions. Is this the normal behavior? 

I am using Mona 0.5.2 and you can find the aforementioned NiFTI files here (https://drive.google.com/drive/folders/1k__dds_31elP-zkelCNSguWIDrHPTDe5?usp=sharing)

Thank you for looking into this.

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Fixes #2304

### Description
adds a `transform_with_metadata` to ImageDataset

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your enhancement for ImageDataset.
I think the reason we kept `ImageDataset` after developed `ArrayDataset` is that: `ImageDataset` loads image data and meta_data in this dataset instead of transforms, so it can apply following typical transform chain only for the image data and still return both transformed image data and the meta_data.
For the use case you provided in this PR, it requires every transform in the chain must accept the meta_data arg, then why not use `ArrayDataset` directly?
And to support mixed transforms that some can accept meta_data and some not, users can refer to this example:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/dataset.py#L926
What do you think?

Thanks.

**Comment by wyli** [comment]
Hi @Nic-Ma, this API is used by multiple tutorials, but it's half baked. here I enhanced it and made a demo to show the usage. https://github.com/Project-MONAI/tutorials/pull/222

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your tutorial, may I know why we don't use `ArrayDataset` for the case in the tutorial? Maybe you can change to show `ArrayDataset` in the tutorial?
I think we only use `ImageDataset` in the case that we need the meta_data for the following operations(like saving files) and all the transforms don't need meta_data, otherwise, `ArrayDataset` may be a better choice.

Thanks.

**Comment by wyli** [comment]
with this enhancement the `imagedataset` has better handling of the metadata compared with the arraydataset, now it's a good complimentary to our dataset APIs

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I don't quite understand "ImageDataset has better handling of the metadata compared with the ArrayDataset", could you please help share more details?
I think we discussed to use `ArrayDataset` and delete `ImageDataset`, but `ImageDataset` has 1 benefit that can get both image data and meta_data but only run transform chain on the image data, so we keep it.

Thanks.

**Comment by wyli** [comment]
the current imagedataset doesn't work with the meta data as reported in #2304, this PR fixes the issue.

**Comment by Nic-Ma** [comment]
OK, I see your point now.
So you mean to support the case that: all the transforms in the Compose chain expect (img, meta) input and `ArrayDataset` can't support this case if using `Compose`, right?
That makes sense.

Thanks for your explanation.

**Review by Nic-Ma — APPROVED** [review]

**Pull request merged**
