### PR TITLE
1804 add pretrain for densenet senet by using subclass

### PR DESCRIPTION
**Pull request by yiheng-wang-nv**
Fixes the new comments in #1804 

### Status
**Work in progress**

### Types of changes

- [x] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by yiheng-wang-nv** [comment]
This PR modifies some updates in #1805

**Review by wyli — COMMENTED** [review]
thanks!

**Comment by yiheng-wang-nv** [comment]
Thanks @wyli for the reviews. I modified all places, and the tutorial PR is [here](https://github.com/Project-MONAI/tutorials/pull/147)

**Review by wyli — APPROVED** [review]
thanks!

**Pull request merged**
