### PR TITLE
3580 - create codeql-analysis.yml

### LINKED ISSUE #3580: enable auto detection of common vulnerability and coding errors via github workflow
**Is your feature request related to a problem? Please describe.**
would be great to adopt Github's code scanning tool for code analysis
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning

currently two issues are detected
https://github.com/Project-MONAI/MONAI/runs/4705382517

### PR DESCRIPTION
**Pull request by wyli**
### Description
fixes #3580 

default code scanning  by github
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]
Looks good to me.
@IsaacYangSLA do you have any other comments?

Thanks in advance.

**Comment by wyli** [comment]
> Looks good to me. @IsaacYangSLA do you have any other comments?
> 
> Thanks in advance.

Enabled the checking as required premerge tests, please let me know if there is any issue.

**Pull request merged**
