### PR TITLE
Metric: r2

### PR DESCRIPTION
**Pull request by rijobro**
### Description
Implements r2 metric to compare similarities between two tensors. This is a useful metric as it can be expressed as a percentage, as opposed to MSE for example which is arbitrary.

Useful in image regression.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]
Looks good to me.
@KumoLiu Could you please help double confirm this regression metric computation of R2?

Thanks in advance.

**Comment by KumoLiu** [comment]
Hi @Nic-Ma,
        I wonder why assign y.sum(1) to two different variables (n and sum_y).
       And I didn't find the definition of  the mean of the observed data which needed by R2 metric definition. I'm not sure whether it is a variation of the original formula?
Thanks.

**Comment by KumoLiu** [comment]
Hi @rijobro,
I wonder why assign y.sum(1) to two different variables (n and sum_y).
And I didn't find the definition of the mean of the observed data which needed by R2 metric definition. I'm not sure whether it is a variation of the original formula or maybe just I misunderstood.
Thanks.

**Pull request closed without merging**
