### PR TITLE
optional `strict_check` for EnsureChannelFirst(d)

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

### Description
adds a boolean flag `strict_check` to the `EnsureChannelFirst`

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your enhancement for `EnsureChannelFirstd`.
But I think if no `meta data` provided or no `original_channel_dim` found, `EnsureChannelFirstd` can't work as expected at all, so we should raise the exception instead of just a warning.
Maybe you have some use cases for it, could you please help share it for further discussion?

Thanks.

**Comment by wyli** [comment]
this is useful when customising preprocessors and composes, e.g. I was experimenting with this example, using ensure channel and changing the flags.
https://github.com/Project-MONAI/MONAI/blob/c1e06f5ada1e66a544965136d5029c0bf1f4d510/monai/data/dataset.py#L931-L943

**Comment by Nic-Ma** [comment]
Thanks for your explanation.
I feel when users use `EnsureChannelFirstd` transform, they expect it to automatically guarantee a `channel-first` data, if not, raise exception instead of "can't work and return the original data" with a warning.
For experiment purpose, maybe you can easily comment this transform when you change the code to test something?
Anyway, it's not a breaking change, if @ericspod and @rijobro agree with it, I am OK to approve it.

Thanks.

**Comment by wyli** [comment]
if that's the original intention then the previous function signature is also wrong `meta_dict: Optional[Dict] = None`, it shouldn't accept optional meta_dict

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your finding.
I agree to change the signature from `meta_dict: Optional[Dict] = None` to `meta_dict: Dict` as the original check in the function already strongly require it to be a `dict`. Maybe I made the mistake when developing this transform.
Could you please help change this PR to update the signature of the function?

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> Thanks for your finding.
> I agree to change the signature from `meta_dict: Optional[Dict] = None` to `meta_dict: Dict` as the original check in the function already strongly require it to be a `dict`. Maybe I made the mistake when developing this transform.
> Could you please help change this PR to update the signature of the function?
> 
> Thanks.

this PR addressed a previous error, added more flexibility, kept the previous behaviour. I really don't see an issue here.

**Comment by Nic-Ma** [comment]
But I think maybe the previous issue is that: the API signature is not defined clearly?
@ericspod @rijobro what do you think?

Thanks.

**Review by Nic-Ma — APPROVED** [review]
Since @ericspod @rijobro don't have any comments and this PR is a non-breaking enhancement, I am OK to merge it.

Thanks.

**Pull request merged**
