### PR TITLE
Update cuCIM min dependency to support random transforms

### PR DESCRIPTION
**Pull request by drbeh**
### Description
The new release of cuCIM (22.2.1) includes important updates to the random transforms, where the randomness is apply per-image instead of per-batch which was the case in the previous versions. Our updated pathology tutorials depend on this version to work so it should be set as the minimum version in MONAI.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Review by wyli — APPROVED** [review]

**Comment by wyli** [comment]
(there's an irrelevant issue affecting https://github.com/Project-MONAI/MONAI/issues/4003 I'll fix it and merge this PR)

**Comment by wyli** [comment]
looks like the cucim pypi update breaks a test here https://github.com/Project-MONAI/MONAI/runs/5695808906?check_suite_focus=true#step:7:22030

**Comment by drbeh** [comment]
That's weird. I'll check on the test.

**Review by Nic-Ma — APPROVED** [review]

**Pull request merged**
