### PR TITLE
dimension check for pretrained model weights

### PR DESCRIPTION
**Pull request by neuronflow**
This PR implements a dimension check, before trying to load pre-trained model weights.

Fixes # .

### Description
This PR implements a dimension check, before trying to load pre-trained model weights.

### Status
Ready

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
thanks for the PR! could you please sign: https://github.com/Project-MONAI/MONAI/pull/2984/checks?check_run_id=3656576890 (https://github.com/Project-MONAI/MONAI/blob/dev/CONTRIBUTING.md#signing-your-work)

**Comment by neuronflow** [comment]
sure, trying to find out how to do this in hindsight now :) I made the PR with the github web editor as it is so small.

**Review by wyli — APPROVED** [review]
thanks, the DCO looks good now, there is a minor style issue https://github.com/Project-MONAI/MONAI/pull/2984/checks?check_run_id=3663404181#step:7:116

**Pull request merged**
