### PR TITLE
1166 adds citable metadata

### LINKED ISSUE #1166: How do I cite this project?

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Fixes #1166

### Description
add citation.cff file according to https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files -- to be consistent with `setup.cfg`

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Comment by Nic-Ma** [comment]
@ericspod I think maybe you are more familiar with this topic? Could you please help review it?

Thanks in advance.

**Comment by wyli** [comment]
this is simply copying our zenodo info (https://zenodo.org/record/5083813) to the repo, as github provides this new feature https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files, nothing special here @Nic-Ma

**Review by Nic-Ma — APPROVED** [review]
Oh, I see.
Thanks.

**Pull request merged**
