### PR TITLE
2525 Add decollate logic to DeepGrow module (8/July)

### LINKED ISSUE #2525: Deepgrow `Interaction` is not compatiable with `decollate_batch` for v 0.6.0 (8/July)
**Describe the bug**
In deepgrow tutorial (https://github.com/Project-MONAI/tutorials/blob/master/deepgrow/ignite/train.py#L201), we can see there are two groups of transforms: `pre_transforms` and `click_transforms`, and `click_transforms` will be used in `monai.apps.deepgrow.interaction.Interaction`. So far, this way is not compatiable with our `decollate_batch` logic.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #2525 .

### Description
This PR updated the DeepGrow module based on the latest decollate logic.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @wyli @SachidanandAlle ,

There is a potential issue in this PR that I am not very sure how to fix and want to discuss with you guys here:
As DeepGrow is slightly different from regular training, it needs to run several iterations inference / interactions, so we need to `inference -> decollate -> click transforms -> collate -> inference` as what I changed in this PR.
But some random click transforms may output data with different size, so we can't `collate` them into a batch for next inference, like the "guidance" generated by `AddRandomGuidanced` here: https://github.com/Project-MONAI/tutorials/blob/master/deepgrow/ignite/train.py#L98

Can we pad the data and collate? Or any other idea to avoid `collate`?

Thanks in advance.

**Comment by SachidanandAlle** [comment]
This fix looks ok to me.. we can Vish to verify sample 2D deepgrow training.. for accuracy

**Comment by Nic-Ma** [comment]
> This fix looks ok to me.. we can Vish to verify sample 2D deepgrow training.. for accuracy

Hi @SachidanandAlle ,

Thanks for your review, do you mean to use `pad_collate` to solve the size issue when collating again?
@wyli @rijobro what do you guys think?

Thanks in advance.

**Review by SachidanandAlle — APPROVED** [review]

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for @SachidanandAlle 's analysis and help, this PR is ready for review now.
Could you please help also review it?

Thanks in advance.

**Review by wyli — APPROVED** [review]
looks good according to @SachidanandAlle

**Pull request merged**
