### PR TITLE
331 update cache related notebooks and examples

### LINKED ISSUE #331: update CacheDataset notebook example with multi-threads
**Is your feature request related to a problem? Please describe.**
As we just added multi-threads to CacheDataset, we need to update the examples and notebook.

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #331 .

### Description
As we add multi-threads and persistent cache recently, need to update all the related notebooks.

### Status
**Ready**

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [x] Docstrings/Documentation updated

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @hjmjohnson 

This is a WIP PR, but I got a question here that: why the time consuming of epoch 1 in persistent cache is much faster than regular dataset? I suppose it should be slightly slower because it needs to write cache to files at epoch 1, right?
Thanks.

**Comment by hjmjohnson** [comment]
@Nic-Ma I forgot to clean out the cache when running it a second time. It is persistent across runs. This is accurate if the cache really is persistent, but perhaps a bit misleading for the first time.

NOTE:  The fact that the cache persists across separate runs is a primary reason for using this mechanism!

**Comment by hjmjohnson** [comment]
This example is not a priority for me right now.  Feel free to close it with resolving.  I will come back to it when I have time later.

**Comment by hjmjohnson** [comment]
@Nic-Ma FYI:  I don't have the ability to change the WIP status.  It appears that you have taken this branch into the MONAI project that I do not have change permissions.

**Comment by Nic-Ma** [comment]
> @Nic-Ma FYI: I don't have the ability to change the WIP status. It appears that you have taken this branch into the MONAI project that I do not have change permissions.

Thanks @hjmjohnson ,

Don't worry, I am trying to train for this PR, just be curious why the first epoch is faster than regular cache.
Thanks.

**Comment by hjmjohnson** [comment]
A new merge conflict needs resolving.  Otherwise, it looks good to me.

**Comment by Nic-Ma** [comment]
> A new merge conflict needs resolving. Otherwise, it looks good to me.

Resolved conflicts, thanks for your review!

**Pull request merged**
