### PR TITLE
4217 Update PyTorch docker to 22.04

### LINKED ISSUE #4217: Upgrade PyTorch docker for release and CI tests
**Is your feature request related to a problem? Please describe.**
As `PyTorch` docker 22.04 is available, would be nice to update the base docker of MONAI docker and CI test dockers.
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch

### PR DESCRIPTION
**Pull request by Nic-Ma**
Fixes #4217 .

### Description
This PR updated the PyTorch base docker and CI tests docker to 22.04.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

When I try to run our CI tests on the latest PyTorch docker, got the same error from `MetaTensor` test cases, like:
```
======================================================================
ERROR: test_copy_9 (__main__.TestMetaTensor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "tests/test_meta_tensor.py", line 172, in test_copy
    a = deepcopy(m)
  File "/opt/conda/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 86, in __deepcopy__
    return handle_torch_function(Tensor.__deepcopy__, (self,), self, memo)
  File "/opt/conda/lib/python3.8/site-packages/torch/overrides.py", line 1394, in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)
  File "/workspace/data/medical/MONAI/monai/data/meta_tensor.py", line 187, in __torch_function__
    ret = super().__torch_function__(func, types, args, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 1178, in __torch_function__
    ret = func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 141, in __deepcopy__
    raise RuntimeError("The default implementation of __deepcopy__() for non-wrapper subclasses "
RuntimeError: The default implementation of __deepcopy__() for non-wrapper subclasses only works for subclass types that implement new_empty() and for which that function returns another instance of the same subclass. You should either properly implement new_empty() for your subclass or override __deepcopy__() if it is intended behavior for new_empty() to return an instance of a different type.
```
Do you have any idea?

Thanks in advance.

**Comment by Nic-Ma** [comment]
BTW, except for the MetaTensor tests, I manually executed all the **integration tests** on V100 locally, all passed OK.

Thanks.

**Comment by rijobro** [comment]
@wyli did any of your recent MetaTensor commits fix the issue @Nic-Ma is referring to, or do I still need to look into this? Thanks

**Comment by wyli** [comment]
> @wyli did any of your recent MetaTensor commits fix the issue @Nic-Ma is referring to, or do I still need to look into this? Thanks

yes, I forgot to get back to the `dev` branch, I'll look into this.

**Comment by wyli** [comment]
> > @wyli did any of your recent MetaTensor commits fix the issue @Nic-Ma is referring to, or do I still need to look into this? Thanks
> 
> yes, I forgot to get back to the `dev` branch, I'll look into this.

this seems to address the issue https://github.com/Project-MONAI/MONAI/pull/4218/commits/c095f92986f0d02b39063100093fa5aab89cd115 please let me know if there's a better way

**Comment by Nic-Ma** [comment]
@wyli @rijobro Thanks for your fix! This PR is ready for review now.

**Review by wyli — APPROVED** [review]
looks good to me, there might be a more efficient way to implement `new_empty` https://github.com/Project-MONAI/MONAI/blob/c095f92986f0d02b39063100093fa5aab89cd115/monai/data/meta_tensor.py#L244

**Pull request merged**
