### PR TITLE
refactor CommonKeys

### PR DESCRIPTION
**Pull request by rijobro**
Move `CommonKeys` to `enums.py` so that it can be used by the whole MONAI codebase. Addresses problem in this PR: https://github.com/Project-MONAI/MONAI/pull/1794#issuecomment-804013257.

### CODE REVIEW

**Review by wyli — APPROVED** [review]
thanks, ~this is a breaking change moves `CommonKeys` from `monai.engines.utils` to `monai.utils.enums`~ this is non-breaking

**Comment by rijobro** [comment]
How is this a breaking change? Do you think many people would be importing CommonKeys in their own code?

**Comment by wyli** [comment]
yes, people are building customised workflows similar to deepgrow  https://github.com/Project-MONAI/MONAI/pull/1825/files#diff-41ea322a0a24b98b7e0366343405c3e4e61716b2639f0acbaecea2079e74d127R18

**Comment by rijobro** [comment]
I see. Well at least the old import still works: `from monai.engines.utils import CommonKeys` (because it still gets imported into `monai/engines/utils.py`).

**Comment by wyli** [comment]
you're right, this is non-breaking, and we have access to `CommonKeys` even with the min. system setup (previously we can't have that)

**Pull request merged**
