### PR TITLE
232 revise rotate

### PR DESCRIPTION
**Pull request by wyli**
subtask of #232;

-Revises rotate/rotated, randrotate/randrotated, remove scipy.ndimage dependency
-remove unused imports/variables

### Status
**ready**

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or new feature that would cause existing functionality to change)
- [x] New tests added to cover the changes
- [x] Docstrings/Documentation updated

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@wyli Status can now be changed now that #511 is merged.

This looks good,

**Comment by wyli** [comment]
this is ready for review @Nic-Ma (needs to verify the integration tests)

**Comment by hjmjohnson** [comment]
```
All integration tests pass on my 2-GPU computer.
----------------------------------------------------------------------
Ran 671 tests in 715.862s

OK


tests/test_integration_classification_2d.py           157      2    99%   52, 244
tests/test_integration_determinism.py                  54      1    98%   86
tests/test_integration_segmentation_3d.py             163      1    99%   337
tests/test_integration_sliding_window.py               57      1    98%   91
tests/test_integration_stn.py                          84      1    99%   131
tests/test_integration_unet_2d.py                      30      1    97%   56
tests/test_integration_workflows.py                    94      1    99%   324
```

**Comment by Nic-Ma** [comment]
BTW, I ran the `test_integration_classification_2d` test locally and it passed as expected:
```
python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
root@apt-sh-ai:/workspace/data/medical/MONAI# python tests/test_integration_classification_2d.py
2020-06-12 01:46:12 URL:https://uc5475dca2aed9b1781ca040a338.dl.dropboxusercontent.com/cd/0/inline2/A5eCj0FMpyuhTWwnerfgs7YTX0r5vjQxopNCe1hw15gP-ZCeLKzSGGkbVclxI6rMJTNsD5lU3ngPWyRFcL8TDuliob3ZDtIG9V2DCsnW0qbz0Zsq2KOhhzUSiAXBQTDXWl7h1U3KI34Jt_wIShppnnOxeFnsLDQAxZdF1bPZe2x-IiGDai7RdUPns-wulJEEFRsJmX_cHZG3VYv01IGU0Aa0peMyrHio_ImQbvmRjsu67asu0DcOYuUHb4lWiotkzYvGDfQycEtlg1uZ2v8RlcDWznHVxdOydWTZdwEWWaHyejFKYJ4ZariueVeWmufmXWH-4WsWZDhRxmbwMdYF8E_EPgJCeSAfRiDfRdn19SN0pw/file [61834679/61834679] -> "/tmp/tmph0f5a7ya/MedNIST.tar.gz" [1]
MONAI version: 0+untagged.270.gb28c454
Python version: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)  [GCC 7.3.0]
Numpy version: 1.17.4
Pytorch version: 1.5.0
Ignite version: 0.3.0
----------
Epoch 1/4
epoch 1 average loss:0.7797
saved new best metric model
current epoch 1 current AUC: 0.9980 current accuracy: 0.9545 best AUC: 0.9980 at epoch 1
----------
Epoch 2/4
epoch 2 average loss:0.1618
saved new best metric model
current epoch 2 current AUC: 0.9996 current accuracy: 0.9831 best AUC: 0.9996 at epoch 2
----------
Epoch 3/4
epoch 3 average loss:0.0745
saved new best metric model
current epoch 3 current AUC: 0.9998 current accuracy: 0.9909 best AUC: 0.9998 at epoch 3
----------
Epoch 4/4
epoch 4 average loss:0.0460
saved new best metric model
current epoch 4 current AUC: 0.9999 current accuracy: 0.9935 best AUC: 0.9999 at epoch 4
train completed, best_metric: 0.9999  at epoch: 4
best metric 0.9999257360741627
MONAI version: 0+untagged.270.gb28c454
Python version: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)  [GCC 7.3.0]
Numpy version: 1.17.4
Pytorch version: 1.5.0
Ignite version: 0.3.0
----------
Epoch 1/4
epoch 1 average loss:0.7797
saved new best metric model
current epoch 1 current AUC: 0.9980 current accuracy: 0.9545 best AUC: 0.9980 at epoch 1
----------
Epoch 2/4
epoch 2 average loss:0.1618
saved new best metric model
current epoch 2 current AUC: 0.9996 current accuracy: 0.9831 best AUC: 0.9996 at epoch 2
----------
Epoch 3/4
epoch 3 average loss:0.0745
saved new best metric model
current epoch 3 current AUC: 0.9998 current accuracy: 0.9909 best AUC: 0.9998 at epoch 3
----------
Epoch 4/4
epoch 4 average loss:0.0460
saved new best metric model
current epoch 4 current AUC: 0.9999 current accuracy: 0.9935 best AUC: 0.9999 at epoch 4
train completed, best_metric: 0.9999  at epoch: 4
best metric 0.9999257360741627
.
----------------------------------------------------------------------
Ran 1 test in 266.217s

OK
```

**Pull request merged**
