### PR TITLE
Unify visualisation

### PR DESCRIPTION
**Pull request by rijobro**
Unify visualisation classes.

### Description
Beforehand, occlusion sensitivity was a function in `metrics`, whereas gradcam functionality was in classes inside the `visualize` module. Now, both can be called with similar calls:

```
from monai.networks.nets import densenet121
from monai.visualise import OcclusionSensitivity
from monai.visualise import CAM
model_2d = densenet121(spatial_dims=2, in_channels=1, out_channels=3)

cam = CAM(nn_module=model_2d, target_layers="class_layers.relu", fc_layers="class_layers.out")
result_cam = cam(x=torch.rand((1, 1, 48, 64)))

occ_sens = OcclusionSensitivity(nn_module=model_2d)
result_occ_sens = occ_sens(x=torch.rand((1, 1, 48, 64)), class_idx=None, b_box=[-1, -1, 2, 40, 1, 62])
```

We also had mixed American and British spelling, so changed all instances of `visualize` to `visualise`. Maybe I should have gone the other way, as it made lots of changes...

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh --codeformat --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by wyli** [comment]
I feel we should go for `visualize`... to be consistent with pytorch and numpy

**Comment by rijobro** [comment]
ok, updated.

**Comment by wyli** [comment]
thanks for the clean up! but I think it's too early to define a proper NetVisualizer API, we should keep the module simple for now, and it needs more discussions along with https://github.com/Project-MONAI/MONAI/issues/528

**Comment by rijobro** [comment]
> but I think it's too early to define a proper NetVisualizer API

I can remove it if you'd like but it's only a skeleton at the moment, with a constructor and `__call__` method. Just so that when future visualisations get added, they are more likely to conform (avoid the difference we saw with OccSens and GradCAM).

Up to you, I'll delete if you'd like, but I'm in favour of keeping it.

**Comment by wyli** [comment]
> > but I think it's too early to define a proper NetVisualizer API
> 
> I can remove it if you'd like but it's only a skeleton at the moment, with a constructor and `__call__` method. Just so that when future visualisations get added, they are more likely to conform (avoid the difference we saw with OccSens and GradCAM).
> 
> Up to you, I'll delete the base class if you'd like, but I'm in favour of keeping it.

I feel the benefit of having a `NetVisualizer` class is not very clear at the moment (and the interface is also not well documented), all the other changes look very nice. perhaps @Nic-Ma @ericspod could have more comments.

**Comment by rijobro** [comment]
Ok, I can remove it. 

I also created a `train_mode` context manager (opposite of `eval_mode`) [here](https://github.com/Project-MONAI/MONAI/pull/1381/files#diff-d3917404e925ec1a84e22f35ad430e32d6ca3b0de28bdcbf0fd2a8bf2d2b8777R283). We can use this when calculating the gradient for GradCam, which should avoid the problem you saw here: https://github.com/Project-MONAI/tutorials/pull/83#issuecomment-748003086.

**Review by wyli — APPROVED** [review]
thanks!

**Pull request merged**
