### PR TITLE
correct blossom trigger list format

### PR DESCRIPTION
**Pull request by YanxuanLiu**
### Description
Fix the issue `Cannot trigger pre-merge correctly`

Modifications:
1. add a missing ',' after usre ID.
2. switch the trigger list to new line pattern to avoid the issue.

### Status
**Ready/Work in progress/Hold**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by pxLi — APPROVED** [review]

**Comment by wyli** [comment]
Now I remember the issue, it's missing a comma after Yanxuan's id. Could you please add the comma instead?

**Comment by pxLi** [comment]
> Now I remember the issue, it's missing a comma after Yanxuan's id. Could you please add the comma instead?

we prefer to use `     wyli,` newline pattern. The previous one could also match substring of a long ID.
New list pattern makes sure that spaces before each ID

refer to https://github.com/Project-MONAI/model-zoo/blob/dev/.github/workflows/blossom-ci.yml#L45-L51

**Comment by wyli** [comment]
ok I'm sure why model zoo link is provided here as a reference. could you please help document for future reference?

**Comment by pxLi** [comment]
@wyli we use the newline pattern everywhere w/ blossom-ci, I guess the first time when adil add the file might not consider the issue

**Comment by pxLi** [comment]
@YanxuanLiu please help add the comment here maybe to describe how to correctly add a new ID

**Review by wyli — APPROVED** [review]

**Comment by YanxuanLiu** [comment]
> 

updated in description

**Comment by YanxuanLiu** [comment]
> @YanxuanLiu please help add the comment here maybe to describe how to correctly add a new ID

Updated in description

**Comment by pxLi** [comment]
@YanxuanLiu please help file a following PR to verify the change after merge, many thanks!

**Pull request merged**
