### PR TITLE
inverse adjust contrast

### PR DESCRIPTION
**Pull request by rijobro**
Starts to address https://github.com/Project-MONAI/MONAI/issues/2213.

### Description
Add inverse for `AdjustContrastd` and `RandAdjustContrastd`.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick --unittests`.
- [x] In-line docstrings updated.
- [x] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Review by wyli — APPROVED** [review]
thanks! there might be an implicit int->float casting in the forward, not sure whether we should consider that in the inverse, perhaps could refactor that later

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

I have a concern about this PR:
If we use `AdjustContrastd` in the transform chain for `image` during inference, and want to invert `pred` based on the transform_info of `image`. How to avoid inverting this transform but invert other spatial transforms?

Thanks in advance.

**Comment by rijobro** [comment]
The applied transforms are stored in a list, so we could simply manipulate the list as we need. Untested example might be like this:

```python
def remove_transforms(transforms: list, to_be_removed: list):
    return [t for t in transforms if t["class"] not in to_be_removed]

transforms = remove_transforms(data["image_transforms"], ["AdjustContrastd"])
```

We could potentially formalise this using a withable or putting it in the Inverter logic:


```python
ts = data["image_transforms"]
with InvertibleTransform.skipInverses(ts, ["AdjustContrastd"]):
    ts.inverse(data)
```

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

Thanks for your proposal, but is there any use case to avoid only 1 of same transforms?
For example:
```py
Resized(keys="img", spatial_size=[128, 128, 128]),
RandSpatialCrop(keys="img", random_size=True),
Resized(keys="img", spatial_size=[64, 64, 64]),
```
And only skip the first `Resized`.
So in summary, I am not sure we should skip transforms by **class name** or instance **unique ID**.
@wyli @ericspod , what do you think? Or any other ideas?
We also need to think about how to enhance the `Invertd` transform for this feature request.

Thanks.

**Comment by rijobro** [comment]
I think there could be lots of different reasons for wanting to do the inverse of some, but not all of the applied transforms, so there won't be any "one size fits all" solution.

I don't think we often use multiple instances of the same transform, but If the user wanted to skip the first `Resized`, then they could just do it via indexing: `d["image_transforms] = d["image_transforms][1:]`. Random transforms are appended even if `do_transform` was false (below threshold probability), meaning the length of invertible transforms will remain constant and indexing can be safely used.

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

Could you please help create a PR to enhance the `Invertd` transform for this issue?
Inverting is heavily used in our internal projects now, once users use `AdjustContrastd` transform, it will cause issue..

Thanks in advance.

**Comment by rijobro** [comment]
Glad to hear that the inverse functionality is being used! Sure, I'll create a draft PR and we can discuss if the solution is acceptable there.

**Comment by Nic-Ma** [comment]
Cool, sounds good!
Thanks.

**Comment by wyli** [comment]
perhaps could have a `SpatialTransform` interface? because in many cases we want to invert the spatial ones only.

**Comment by rijobro** [comment]
Similar to my suggestion here: https://github.com/Project-MONAI/MONAI/issues/2213#issuecomment-846906915.

I wonder if we're getting a little too complicated -- what about transforms that are a mix of spatial and intensity, what about invertible transforms that are neither spatial or intensity (we don't have any yet, but may in the future).

Would it be worth scheduling a meeting for our transforms? We may want to unify certain things to make them more future-proof.

**Comment by wyli** [comment]
sure @rijobro let's have a Teams chat soon...

**Pull request merged**
