### PR TITLE
854 sliding window infer less gpumemory

### LINKED ISSUE #854: sliding_window_inference uses to much gpu memory if roi_size is small and images to infer large
**Describe the bug**
sliding_window_inference runns ot of memory if roi_size is small and images to infer large

**To Reproduce**
evaluete a highres3dnet with images larger than 512x512x256 and roi_size of the sliding_window_inference option of [16,16,16] and the required gpu memory exceeds 8gb 

**Expected behavior**
less memory should be used

**Environment (please complete the following information):**
MONAI version: 0.2.0
Python version: 3.6.9 (default, Jul 17 2020, 12:50:27)  [GCC 8.4.0]
Numpy version: 1.19.0
Pytorch version: 1.5.0+cu101

**Additional context**
sliding window inference seems to be broken with the current nightlies, a runntime exception occures in monai.networks.utils in to_norm_affine at line: new_affine = src_xform @ affine @ torch.inverse(dst_xform). Seems that the segmentation saver is not correctely reading out the meta data dict from the batch.

Have the bug fixed at least for version 0.2.0 and will send a pull request

### PR DESCRIPTION
**Pull request by elitap**
Fixes #854 .

### Description
fixes the issue by keeping the slices in cpu memory and doing the anyways not parallelizible computations on cpu, by doing so the slicing_window_infernece functions gpu memory consumption is independent of the roi_size and image size. Runtime stays according to my measurements the same expect some small but irrelevant overhead of moving the memory

### Status
**Ready*

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Comment by wyli** [comment]
thanks for the PR @elitap , shall we have an optional `device` argument in the function signature, something like `device: Optional[torch.device] = None`, if the user doesn't provide a value (device is None), by default the result will be colocated with the input image

**Comment by elitap** [comment]
Thank you for considering to merge. I agree about the argument, a problem which I still have for my application is connected with line 141: output_image = (output_image / count_map).to(inputs.device), copying back the memory to its original location, again requires a fair amount of GPU memory if the output_image is large (too much in my case). On the other hand not doing so, results in a consecutive error when using for example the MeanDice handler. Accordingly I am still a bit unsure about the usability, wouldn't the user expect a tensor on the set device as a return value.

**Comment by wyli** [comment]
yes, I think the original version of line 141 looks fine, which means the output stays on `device`. it is a well-behaved module -- aggregating image windows on a user-specified device instead of forcing the output to be colocated with the inputs. the consecutive errors should be addressed outside of the module (e.g. for computing the dice metric, there's no need to move the ground truth label to gpu if the sliding window output is on cpu)

**Comment by Nic-Ma** [comment]
Hi @elitap ,

Thanks for your quick PR, could you please help provide some test result of memory usage?
with device=CPU/GPU.

Thanks.

**Comment by elitap** [comment]
@wyli well yes agree, changed the code to output an image on the device set. Also extended the tests to test the new param.
@Nic-Ma sure on an image with shape [1, 1, 229, 229, 239] and roi_size [16, 16, 16] the consumption on my system (GTX 1080 with 8Gb and 64Gb system mem) during the slw inference is:
cpu - 1563MiB / 8119MiB Time for the integration test 00:00:39 (I guess it needs to be seen relative to my system)
gpu - 3326MiB / 8119MiB Time for the integration test 00:00:36

for example if I use double resolution for the input image the slw inference runs out of memory for the gpu version whereas the cpu version still works using 3693MiB of memory.

**Pull request merged**
