### PR TITLE
4948 Enhance bundle API for getting model zoo info

### LINKED ISSUE #4948: Add script API to get info of all the available bundles and details in the model-zoo
**Is your feature request related to a problem? Please describe.**
To help developers or users easily get the information of all the bundles in the model-zoo, it would be nice to add script APIs to get the manifest of bundles and details of the specific bundle.

Similar to the existing script APIs:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/bundle/scripts.py#L154

### PR DESCRIPTION
**Pull request by yiheng-wang-nv**
Signed-off-by: Yiheng Wang <vennw@nvidia.com>

Fixes #4948 .

### Description
This PR is used to enhance the bundle API, and enable to get:

1. a list of all bundles as well as their latest versions (by function `get_all_bundles_list`)
2. a bundle's latest version, and all existing verions (by function `get_bundle_versions`)
3. a bundle's information, include "id", "name", "size", "download_count", "browser_download_url". The information are achieved from github API directly (by function `get_bundle_info`)

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [ ] Integration tests passed locally by running `./runtests.sh -f -u --net --coverage`.
- [ ] Quick tests passed locally by running `./runtests.sh --quick --unittests  --disttests`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated, tested `make html` command in the `docs/` folder.

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Thanks for the quick implementation.
I think we need the API to get the latest version of all the bundles and a specific bundle, and also need API to get all the versions.

Thanks.

**Comment by yiheng-wang-nv** [comment]
> Thanks for the quick implementation. I think we need the API to get the latest version of all the bundles and a specific bundle, and also need API to get all the versions.
> 
> Thanks.

Thanks @Nic-Ma , I will add these functions, and I think both of them can be based on `_get_all_bundles_info `

**Comment by yiheng-wang-nv** [comment]
Update:

According to the suggestions from @Nic-Ma , I did some changes. Now, we have the following functions:

1. `get_all_bundles_list`, all bundle names and latest versions will be returned. For example:
Screen Shot 2022-09-08 at 5 56 51 PM

2. `get_bundle_versions`, the latest version and all existing version of a specified bundle will be returned. For example:
Screen Shot 2022-09-08 at 6 00 36 PM

3. `get_bundle_info`, "id", "name", "size", "download_count", "browser_download_url" of a specified bundle and version will be returned. For example:
Screen Shot 2022-09-08 at 6 01 54 PM

If "version" is not specified, the information of the latest version will be used in default. For example:
Screen Shot 2022-09-08 at 6 02 48 PM

**Review by Nic-Ma — APPROVED** [review]

**Pull request merged**
